### ISSUE TITLE
Image uploading isn't working

### ISSUE THREAD

**Issue by 4uffin** [HeyPuter/puter#103]
At least for me, when I attempt to upload an image file to Puter, it gets stuck. My storage isn't full, so that can't be the issue.

Image for reference:
![Screenshot 2024-03-15 at 00-36-15 Puter](https://github.com/HeyPuter/puter/assets/16989538/112d86ec-b47d-4321-8845-f148ca060980)

**Comment by jelveh** [comment]
It should be resolved now. Please let us know if it happens again.

**Comment by jelveh** [comment]
Sorry about this. It's a known issue. @KernelDeimos

**Comment by jelveh** [comment]
@rhve could you try again? it should be fixed now.

**Comment by rhve** [comment]
now it works, thanks!
