### ISSUE TITLE
Add Escape key handling to close UIPrompt dialog

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#1032]
The UIPrompt component currently lacks the ability to be closed using the Escape key. This is a standard behavior in most modal dialogs and would improve user experience by aligning with common web platform patterns.

#### Current Behavior
- UIPrompt can only be closed by clicking the cancel button
- Pressing the Escape key has no effect when the prompt is active

#### Expected Behavior
- Pressing the Escape key while the UIPrompt is active should close the dialog
- This should trigger the same behavior as clicking the cancel button
- The promise returned by the prompt should resolve with `null` or reject (matching the cancel button behavior)

#### Technical Details
- Prompt component location: `src/gui/src/UI/UIPrompt.js`
- Need to add a keyboard event listener for the Escape key

**Comment by Agastya18** [comment]
let me try @jelveh

**Comment by jelveh** [comment]
Go for it 🫡
