### ISSUE TITLE
Implement 'Show Hidden Files' Feature for Desktop and File Explorer

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#11]
In traditional desktop environments, users have the option to view hidden files, which are often system files or user preferences that are not displayed by default to prevent accidental modifications. This functionality is crucial for advanced users who need to access or modify these files for configuration purposes. 

Expected Behavior:

- **Toggle Visibility**: Users should have the option in both the desktop environment and the file explorer to toggle the visibility of hidden files. This could be implemented as an option in a context menu or as a toggle button/icon within the file explorer.
- **Indicator of Status**: When hidden files are shown, there should be a clear indication in the UI that hidden files are being displayed. This could be a UI change, a message, or an icon change (e.g. decrease opacity).
- **Persistence of User Preference**: The user's choice to show or hide hidden files should persist across sessions until explicitly changed again by the user. Puter.js's `puter.kv` module could be used for this ([docs](https://docs.puter.com/KV/set/))
- **Visibility in Desktop and File Explorer**: The setting to show hidden files should apply universally across the desktop environment and within the file explorer, ensuring a consistent user experience.

**Comment by sunjc826** [comment]
Hello, I'd like to attempt this issue!

**Comment by jelveh** [comment]
Go for it 💪

**Comment by jelveh** [comment]
Let me know if you need help 🤗
