### ISSUE TITLE
Feature request: query parameters in app url get passed into the app

### ISSUE THREAD

**Issue by triptych** [HeyPuter/puter#111]
As a developer I want to be able to share an app url such as https://puter.com/app/editor but I want to pass parameters into the url that get sent in to the app as env variables that the app would have access to - the reason being that perhaps there's some state I want my app to be in based on those parameters.

For instance say I had a hypothetical image editor app, and a parameter passed to it might be the url of an image. https://puter.com/app/mycoolimageeditor?img=http://sample.com/foo.gif the foo.gif URL could be passed in to the app so that when it is launched it opens the foo.gif in the editor itself. 

another example might be that you have an RSS reader app, and you pass an RSS url into it on launch and it auto reads it

or imagine a dictionary app that automatically opens to the query word you passed in.

**Comment by jelveh** [comment]
We should do this. Implementation is straight forward, need to make sure there are no security/abuse possibilities or, if any, find a way to safeguard against them. This would make a good first issue.

**Comment by jelveh** [comment]
This is now implemented. Note that it's not available on Puter.com, yet. But this this repo supports it.
