### ISSUE TITLE
Icons under taskbar

### ISSUE THREAD

**Issue by KernelDeimos** [HeyPuter/puter#114]
Chrome 122, Android 14

I can't see the text on this icon when I open on mobile.

![Screenshot_20240316-111408](https://github.com/HeyPuter/puter/assets/7225168/3cea5708-e3a7-45b2-8208-8111fdf53ccf)

**Comment by SaiUddisa** [comment]
can you give me much more details about this issue.. I did not catch your point.

**Comment by meetqy** [comment]
![image](https://github.com/HeyPuter/puter/assets/18411315/9045bc6d-6f69-4fb6-95c7-b8d76b64d0b9)

The Problem also exits on computers.

**Comment by meetqy** [comment]
@jelveh Can I add a removable range to solve this problem?

**Comment by jelveh** [comment]
@meetqy could you elaborate? I'm not sure what that is.

**Comment by meetqy** [comment]
> @meetqy could you elaborate? I'm not sure what that is.

1. When the app icon moves, it detects whether it is outside the desired area.
2. If it is out of area, the app icon is fixed to the edge of the viewable area.

**Comment by jelveh** [comment]
This wouldn't work because the item should be able to move over the Taskbar. This is because we have a feature allowing users to drop files on apps in taskbar and opening them. A better alternative would be to revert a drop if it's outside the viewport.  (e.g. under the taskbar and not on any taskbar item).

**Comment by meetqy** [comment]
https://github.com/HeyPuter/puter/assets/18411315/c2d6ae28-725a-4928-8378-1b98a5219692

`New File.txt` also on taskbar?

**Comment by jelveh** [comment]
It would have to go back to its original position unless it's dropped on an app.

**Comment by jelveh** [comment]
In the long term we may want to allow for pinning files to the Taskbar, but this needs some user research. So for now, files should just return to their original position.
