### ISSUE TITLE
Default Puter Wallpaper

### ISSUE THREAD

**Issue by 4uffin** [HeyPuter/puter#115]
I want a copy of the default Puter wallpaper (the one I've provided below), but seeing as you can't inspect element Puter, I can't get it.
Am I allowed to get it? I just like the wallpaper and want a copy for personal use.

Puter Wallpaper for context:
![Screenshot 2024-03-16 at 20-00-01 Puter](https://github.com/HeyPuter/puter/assets/16989538/f455a294-7129-4849-b1d2-0bc014137edf)

Please and thank you :)

**Comment by jelveh** [comment]
The default wallpaper is created by [Milad Fakurian](https://unsplash.com/photos/blue-orange-and-yellow-wallpaper-E8Ufcyxz514) and published on [Unsplash](https://unsplash.com/).

(For reference, we have a copy of the above attribution in the Credits section of the README)
