### ISSUE TITLE
Add Cancellation Button for Ongoing Zip Operations

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#116]
## Description:
Currently, when performing a zip operation on files or folders, a progress window is displayed to inform the user of the ongoing process. However, this progress window lacks a cancellation option. This means that users have no way to interrupt the zipping process once it has started, aside from potentially having to refresh Puter, which is neither convenient nor safe.

## Suggested Solution
Implement a "Cancel" button within the progress window of zip operations. This button would allow users to safely terminate the zip process at any point.

**Comment by SaiUddisa** [comment]
can you elaborate more on this issue

**Comment by SaiUddisa** [comment]
i didnt see any progress window while using zip operation. Its just displaying a buffering  animation and doing the task. Should I add the cancel button there  or what?

**Comment by AtkinsSJ** [comment]
> i didnt see any progress window while using zip operation. Its just displaying a buffering animation and doing the task. Should I add the cancel button there or what?

Yes, that's the progress window. It doesn't currently show how complete the task is, but eventually it will.

**Comment by meetqy** [comment]
Has this issue been claimed? If not, I can try.

**Comment by meetqy** [comment]
https://github.com/Stuk/jszip/issues/594  

jszip unsupport cancel.

**Comment by jelveh** [comment]
this sucks. Let me think about it a little.

**Comment by AtkinsSJ** [comment]
`jszip` seems to have stopped being developed a couple of years ago, so it's unlikely we could get it modified to add cancellation. But maybe we could fork it.

Alternatively, [archiver](https://www.npmjs.com/package/archiver) looks like a decent alternative that does support aborting a request.

**Comment by 4nshuman** [comment]
Hey @jelveh, @AtkinsSJ,
I'd love to take a look at this issue. It might take some time given the fact that the original lib has not been updated in over 2 years. Our best bet might be to swtich over to a new lib. One that I had in mind was [fflate](https://github.com/101arrowz/fflate), as mentioned on the original jsZip issues page.

Please let me know in case I can take it up.

**Comment by jelveh** [comment]
Hey @4nshuman. Go for it!
I'm open to changing the module used for zim/unzip. fflate seems interesting, though it seems to have been inactive for several months. 

Let me know if you need help.

**Comment by 4nshuman** [comment]
Hi @jelveh, I looked into the available npm modules and I think I'll be proceeding with Archiver, it has better documentation and also has active development ongoing.
This is gonna take some time but rest-assured I'm working on this.

**Comment by jelveh** [comment]
Thank you for the update @4nshuman. Sounds like a good choice. Let me know if you need help along the way.

**Comment by 4nshuman** [comment]
Hey @jelveh.
So I tried integrating the Archiver library onto Puter's client side compression mechanism. But there's a hiccup.
Archiver is designed to be used server side and I tried to browserify it using polyfills and webpack, but the fs module just breaks the port.
As I understand the puter JSOS uses the puter SDKs fs system for file management, I tried to plug it onto the Archiver port but the webpack browserification still broke apart.
I feel that even if I manage to port Archiver at this point it'd be an overkill. Hence I'd like to proceed with fflate for time being.
Please let me know of your thoughts/ideas to better implement this issue.

PS: Attaching some snaps from my unsuccessful attempt at porting Archiver for client side.

<img width="1888" alt="Screenshot 2024-09-28 at 4 39 48 AM" src="https://github.com/user-attachments/assets/4d96527e-4c2b-4c26-a556-469dcab52e18">
<img width="1888" alt="Screenshot 2024-09-28 at 4 39 56 AM" src="https://github.com/user-attachments/assets/a34dc442-dabe-43c0-bedb-4b1f32c8e039">
<img width="1888" alt="Screenshot 2024-09-28 at 4 40 36 AM" src="https://github.com/user-attachments/assets/93619d74-7f77-489b-a5d4-f6f601d1a693">
<img width="1877" alt="Screenshot 2024-09-28 at 4 40 54 AM" src="https://github.com/user-attachments/assets/6c544da3-8453-4e0d-b097-92eaecadee54">
<img width="1877" alt="Screenshot 2024-09-28 at 4 41 00 AM" src="https://github.com/user-attachments/assets/17bbf77f-d3d1-46e1-a8c6-bb69daa35142">

**Comment by 4nshuman** [comment]
Hello @jelveh,

So I've been working on this issue for the last couple of weeks, and here's something interesting that I've noticed.
On the current instance of Puter, the zip functionality seems to be broken:

Puter.com:
![image](https://github.com/user-attachments/assets/a4cb1e0f-2ce1-4b61-8acf-323e69ca7fe8)
<img width="1904" alt="image" src="https://github.com/user-attachments/assets/0ea1b1f8-c3f6-49d8-9dfd-24ccd23c800f">

When zipping a file/folder the size does not reduce and the file remains bloated.
I was out to add a cancel functionality to the zipping mechanism but ended up fixing this issue as well: 
![image](https://github.com/user-attachments/assets/8a4f86f9-abd4-4fe1-95d7-07a56429c809)
![image](https://github.com/user-attachments/assets/0d88d9b7-4392-4abe-9b5b-b07241bd4fce)

I have a PR in draft with the zipping functionality complete. While I am still working on the unzip mechanism with the new fflate library, I'd appreciate your comments on the current draft PR : 
https://github.com/HeyPuter/puter/pull/787
