### ISSUE TITLE
Make puter actually interact with the system.

### ISSUE THREAD

**Issue by steveiliop56** [HeyPuter/puter#119]
So puter has an awesome interface right now but all the features it has aren't being implemented in the host system. I would recommend adding volumes like `/:/mnt/host` so you will have a file explorer pointing there. Then pass the shell of the host etc. After that you directly compete with the Synology ui lol

**Comment by jelveh** [comment]
Coming 2 weeks, please see this: [https://github.com/HeyPuter/puter/discussions/18](https://github.com/HeyPuter/puter/discussions/18)
