### ISSUE TITLE
Automatic Adjustment of Puter Windows to Stay Within Viewport on Browser Resize

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#12]
Users often adjust the size of their browser window for various reasons, such as multitasking or changing display settings. Currently, in Puter, resizing the browser can lead to open windows moving out of the viewport, making them inaccessible or partially hidden. This issue can disrupt the user's workflow and requires manual adjustment to bring these windows back into view. Implementing an automatic adjustment feature that ensures all windows remain within the viewport during and after a browser resize would improve usability and UX.

Expected Behavior:

- **Automatic Re-positioning**: When the browser window is resized, any Puter window (or windows) that ends up partially or fully outside of the viewport should automatically be re-positioned to ensure it remains visible within the new viewport dimensions.
- **Intelligent Placement**: The adjustment should not merely bring the window back into view but should do so intelligently to minimize disruption. For instance, if only a small portion of the window is out of view, the system should adjust it minimally to make it fully visible again.
- **Respect User Layout**: While ensuring window visibility, the system should strive to maintain the user's original layout as much as possible, avoiding drastic changes that could disorient the user.
- **Notification/Option to Revert**: Optionally, after an automatic adjustment, a subtle notification could be provided to inform the user of the change, with an option to undo the adjustment if desired.

**Comment by meetqy** [comment]
![image](https://github.com/HeyPuter/puter/assets/18411315/297dd811-39c2-4214-9e42-9c5e565b40c8)

I want to solve this problem by listening to the browser zoom, recalculating the position, is that possible?
