### ISSUE TITLE
Unable to login to puter.com

### ISSUE THREAD

**Issue by Traace** [HeyPuter/puter#124]
Hi, I'm unable to login. The site just freezes when clicking on the Login Button. Happens on Firefox, Chrome and Safari running MacOS 14.4

Steps to reproduce:
1. Create a account on puter.com
2. Try to Login with that account
3. Site freezes in browser. Unable to open developer tools. Needs a reload to make it work again (until next login attempt)

I also started up a docker and tried it via local access. Same issue and nothing is logged server side.

**Comment by jelveh** [comment]
This is resolved now.
