### ISSUE TITLE
Feature request: Add more programming languages to code apps with

### ISSUE THREAD

**Issue by DanielMo09** [HeyPuter/puter#131]
Please make it so that you like dont need to rewrite your (Windows) app to make it run on puter, it would also make it alot easier for people that arent good in HTML, CSS and JS (me included)

**Comment by jelveh** [comment]
This is happening gradually over time as we improve Puter. I'm going to close this issue because it's not really a one-off issue that could be done with a PR. Please follow the repo and maybe join our Discord/Twitter as well to stay updated as we add support for different languages.
