### ISSUE TITLE
Pass Locale Preferences to Apps

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#135]
Suggested by @SondreNjaastad 

## Description
Apps running within Puter should be able to retrieve the user's locale settings. 

## Proposed solution
For apps running within Puter, we could pass the locale preferences in the iframe URL of the app. An example would be the following query string appended to the URL `puter.local= en-US `.

**Comment by Pahul-Sidhu** [comment]
I would like to work on this

**Comment by jelveh** [comment]
@Pahul-Sidhu go for it, assigned :)

**Comment by Pahul-Sidhu** [comment]
Do we need to pass the local preferences to every app inside. If yes, then what that preferences exactly ?
