### ISSUE TITLE
I made a browser

### ISSUE THREAD

**Issue by o0101** [HeyPuter/puter#143]
I combined BrowserBox with puter to create a super puter browser. 

Check it out here: https://news.ycombinator.com/item?id=39759534

It's real

**Comment by o0101** [comment]
Hey @jelveh this will probably annoy you as I'm sure you have other stuff to do, but this little browser is currently broken for Safari users of the very awesome Puter web desktop and internet OS! 

This is not your fault, it is a [known issue](https://blog.certa.dev/third-party-cookie-restrictions-for-iframes-in-safari) with [cookies and iframes](https://www.codeproject.com/Articles/5330276/Cross-Domain-Embedding-Making-Third-Party-Cookies) [in Safari](https://www.google.com/search?q=safari+3rd+party+cookies+iframe). 

Thankfully there is a way to fix this, but unfortunately I need to bug you for assistance to do that, because of a missing sandbox attribute needed to enable this. 🥺 

For Safari to work (on Desktop and Mobile) is the embedding iframe needs an [`allow-storage-access-by-user-activation`](https://developer.mozilla.org/en-US/docs/Web/API/Document/requestStorageAccess#notallowederror) token in the sandbox attribute (the relevant iframe is highlighted on right below).

<img width="1264" alt="Screenshot 2024-03-20 at 1 25 52 PM" src="https://github.com/HeyPuter/puter/assets/22254235/f20906ea-22ef-46bc-9e61-489bc6b4cb6e">

This allows us to then call [`document.requestStorageAccess()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/requestStorageAccess#notallowederror) on user interaction. The first we ask, Safari then opens a permission prompt check with the human that they are cool to use cookies.

If they say yes, then we can set a cookie for `https://browse.cloudtabs.net` which let's us:

- take you back to the same browser sessions and prevent abuse, even across reloads
- helps prevent people creating wastefully too many browser sessions, preserving resources for everybody
- enhances security by using allowing a HttpOnly cookie, rather than just a JS-side CSRF token to authenticate requests.

I tested this flow works this morning by adding the token manually in the Developer Tools element inspector, and modifying the CloudTabs code to ask for this cookie access, so I'm excited if it's possible to get this on Puter officially! 🥺 

The reason this is necessary for Safari, but not Chrome browsers is because Safari has some pretty stringent requirements for these "3rd-party" cookies (cookies set from within a cross-origin iframe embedded on another site). This is a good idea to prevent user-tracking and ads, but can get in the way of embedded apps like this.

If you added this token to the sandbox attribute on your embedding iframes, I'd then take care of the rest needed to make CloudTabs work for Safari users! 😃 

I'm sure you probably have a reason for not turning this on before, so I totally get if there's nothing you can do -- but I don't think I can get the browser to work on Puter for folks who use Safari, without making it less secure or abusable. 

Anyway, I totally get if you're too busy to reply, no worries, just thanks for reading this far, @jelveh !

**Comment by jelveh** [comment]
Hi Cris! Thank you very much for adding your awesome browser to Puter, something that many users have asked for. Also thank you very much for the detailed comment explaining the Safari issue. For your own security I had to delete the comment because the screenshot was leaking one of your auth tokens :(

What you said makes sense, I'm going to merge your PR soon. Please let us know how we could make Puter better for your browser, we'd love to help out.

**Comment by o0101** [comment]
@jelveh It's ok my comment was probably a enormously too long anyway. So I'm sorry I'm going to do that again here! 😆  

I know you're super busy so I am sorry about that. I get if you just don't have time to get to this merge or whatever that's fine, no worries.

Also, I'm sorry my original comment probably sounded like it was questioning the security or privacy of puter! That was inconsiderate of me truly and I apologize. 

You have dragged this beautiful Desktop OS up out of nothing and built it, it's truly an incredible achievement! Only respect for you, man. I know you're not someone I would want to be on the bad side of, you are formidable!

Also, thank you for trying to protect some security by deleting that comment, that was the only way to get rid of the screenshot indeed. I did not know there was a token in there but I have made that mistake before with screenshots. I need to be more careful. I trust what you say and thank you. It was only a dev browser token tho and they're ephemeral anyway, but your commitment to security to privacy is very clear from this. Thank you! So I am very sorry it must have sounded like I was questioning it before. 

Let me flip your very generous comment, and praise and question around onto you: CloudTabs browser would be nowhere if it wasn't for your beautiful Puter Desktop Internet OS to run it on. So, I need you. So please tell me what *we* can do for you to make it better for Puter. 

Again, sorry, this comment is probably too long, but I want to dive into some specifics:

- I understand you guys may have your own reasons for not doing the merge and need to discuss and think carefully. I totally agree! 
- Even thinking about these 3rd-party / iframe cookies and tracking can be confusing and I don't fully understand it. 
- I think that because user consent is required for the situation, then adding this token is ideal. But does this open users up to tracking? What risks are there for apps that may abuse the ability to set cookies? These are important questions and I totally get if you want to delay this while you consider them. It's fine!
- Safari requires `requestStorageAccess` for these situations, which then grants access to "unpartitioned" storage. This means that the cookies set for a given embedded domain will be sent to that domain no matter where it's embedded, or even if it's top level. I mean, that is the way that traditional tracking for ads works, I think, right? 
- In trying to be more secure and respecting of user consent, Safari actually avoids allowing "partitioned" access where every "embedded page-embedding page" pair has its own isolated cookie storage, effectively preventing many tracking scenarios. But Safari doesn't allow this...in the name of *privacy*? 🤣 So we have the situation of request storage access and needing this token.
- Even if you merge it, I admit the UI/UX for CloudTabs embedded on Puter is not ideal: we need to request it 1 time for the User Auth domain, and one time for the Browser region (I think). In fact, we may only need to request it 1 time, but I don't know as I haven't yet been able to test it on a production change of puter. What I'm saying is, that UI/UX is a bit annoying. The "generating the token" thing. Ideally we only have to do this once, but with ephemeral browsers there's a chance this could be repeated. Ugh...
- Many people have asked for a browser here. So I was thinking perhaps they will be OK with a few extra steps? Maybe... but I also imagine you folks will want to think about the experience your provide (that's clear from your awesome UI/UX), and I totally get if you just want to put a pin in this and come back.
- With the merge the browser should work for Safari today. So that's good news! 😹 🤣 
- I'm trying to address the shortcomings of the above approach (crumby UX of having to click to 'generate' a token) but not sure when we'll have that work done. It involves removing the cookies and using a localStorage token solution.
- I get with such a important-to-Puter-users addition you'll likely want to take your time on it and be careful, so I didn't expect you to be happy about just merging it quickly anyway. Also, you understandably may not like the idea of using a 3rd-party app for such a thing and would rather have done this internally, so I imagine you are probably figuring out ways to do this right now. This is all OK. I totally understand the desire to own the platform. If I can be of any assistance to you in these efforts please let me know. 
- I think it would be beneficial to consider how we can partner on this to bring more power to more people, but I get if that idea of partnering does not sit well with you because you want to own the platform, and a browser is a key part, so having it run by a 3rd-party is likely going to meet resistance in the Puter steering committee, or whatever I imagine your leadership is called. I totally understand and accept if that's the way you want to go. 
- Theoretically you could even take a prior version of BrowserBox that was still AGPL and use it yourself while open sourcing your server infra that you use to run it. The more current alternative is to purchase commercial licenses but I think there's no way in hell that's what you are looking to do... because it would be a lot of money to provide this in a way you own for all the users you have.

I think there's a solution that advances both while delivering value for the people who use Puter. If you have any concerns would it be a bad idea for you and I to figure this out? 
Let me know if you want to jump on a call to discuss any of this: cris@dosyago.com

Alternately, maybe I've got you wrong and this is just as simple as a merge queue! 🤣 Anyway, I get if you're too busy to reply just thanks for reading this far.

**Comment by jelveh** [comment]
I just merged it! It was merge queue 😅
One thing to note though is that puter.com is behind this repo so it might take a while before we push all the changes to prod. 
Thanks again for adding your **awesome** browser to Puter! I'd like to dig deeper into this, I think we could do a lot of cool stuff. I'll send you an email :)

**Comment by o0101** [comment]
Dude you are the best! Thank you kind, sir. Lookin' forward to your email. Stay strong out there - it can get wild!

**Comment by o0101** [comment]
Hi @saleh-mir if you sign in to CloudTabs you can embed it in any site. You may need to create an index.html file for the app to embed your signed in browser locally.

Alternately you could run BrowserBox on your own machine (as long as it's non commercial purpose you don't need to purchase a license!), and then create a wrapper index.html to embed it.

By index.html I mean the deploy file you need for a Puter app. 

We have not built this yet, and likely would not get to it any time soon. Super busy is not a priority right now. But, I recognize it's usefulness - if you are interested in doing the work we'd happily accept a PR of the setup required and any documentation to make that easy. :)

BTW - I am curious in general what is the attraction of running Puter locally rather than just using the website? I see a lot of folks nowadays looking to self-host. I just don't get it. Why? :) Haha

**Comment by saleh-mir** [comment]
Thank you for your detailed explanation. You really rock, man. I have also followed your contributions to this project, and they are amazing.

Regarding your question, I can't speak for others, but what caught my eye about this project is the ability to have my own desktop environment using a browser. I need to open the browser in that environment, browse the web, download and upload files. Hosting BrowseBox alone is not sufficient for me; I need it to be integrated into Puter (for that download and upload part).

I am aware that I can achieve this with a remote desktop environment like Ubuntu GNOME, but that would require running on a different port. Since BrowseBox is a website, it can be challenging to block in certain countries.

As for why I need to self-host it is because I need to run this on a server location that is probably not available to purchase from those services. And even if they were, I need to make sure that my IP address belongs to me and it never changes or is shared with anyone else.
