### ISSUE TITLE
txt2img in terminal breaks terminal 

### ISSUE THREAD

**Issue by RELNO** [HeyPuter/puter#15]
great project. after running txt2img in the shell (and waiting ~15sec) the terminal became unusable:
<img width="653" alt="Screenshot 2024-03-04 at 6 07 58 PM" src="https://github.com/HeyPuter/puter/assets/14296774/77438e14-55d1-4fd7-a626-90835e25b998">

**Comment by KernelDeimos** [comment]
Moving this issue [to the shell](https://github.com/HeyPuter/phoenix/issues/44)

For now you can use the txt2img with a redirect operator (`>`), for example `txt1img "a red fish" > fish.png`.
