### ISSUE TITLE
"My Websites" does not explain how to publish websites

### ISSUE THREAD

**Issue by AtkinsSJ** [HeyPuter/puter#153]
The "My Websites" shows this message if you have no published websites, but does not explain *how* to publish a website:

![image](https://github.com/HeyPuter/puter/assets/222642/7ad10e52-0760-4fb2-a2b7-e59e8aecc230)

People have asked about this multiple times, so it would be good to add some explanation there, or a link to some documentation.

**Comment by Choon38** [comment]
@AtkinsSJ I'm interested in addressing this. Please assign it to me.

**Comment by AtkinsSJ** [comment]
> @AtkinsSJ I'm interested in addressing this. Please assign it to me.

Sure!

**Comment by micheledinelli** [comment]
Hi! I was about to ask how to publish websites and I saw this issue.
I opened a [PR](https://github.com/HeyPuter/puter/pull/571)  , basically the same opened by Choon38 but I saw it was not merged so I guess it's still needed at least I would have needed it 😄

**Comment by jelveh** [comment]
Thanks again @micheledinelli 

closed via #571
