### ISSUE TITLE
Make showing/hiding the clock configurable

### ISSUE THREAD

**Issue by AtkinsSJ** [HeyPuter/puter#159]
Puter's taskbar has a clock, which currently is hidden normally, but visible in full-screen mode. (Because when you're not in full-screen mode, the system's clock is already visible.)

Add a setting to control when this clock is shown:
- 'Show': Always visible
- 'Hide': Always hidden
- 'Auto': The current behaviour, visible only in full-screen mode.

For now, this could be added to the taskbar's context menu. Eventually it would be good to put it in the Settings app. (See #60)

**Comment by jelveh** [comment]
Note to me #60

**Comment by meetqy** [comment]
![image](https://github.com/HeyPuter/puter/assets/18411315/0070dced-7aa7-44c5-a249-b0df44485262)

Add a clock menu here? And add one page select `show` `hide` `auto`

**Comment by AtkinsSJ** [comment]
I think it would be good to group other similar settings together with that. Maybe the category could be "Appearance" or "Desktop", and have the desktop background setting in there too, instead of the separate window we currently have for that.

**Comment by meetqy** [comment]
OK, I'll try later.

**Comment by AtkinsSJ** [comment]
Great! I'll assign you

**Comment by meetqy** [comment]
https://github.com/HeyPuter/puter/assets/18411315/3d5c426f-3d48-496a-a0d1-10e16c248399

I need to save the selected state to the server, which request interface should I use?

**Comment by AtkinsSJ** [comment]
> I need to save the selected state to the server, which request interface should I use?

I believe you want to use `window.mutate_user_preferences()`, like this:
https://github.com/HeyPuter/puter/blob/fc5bdf61152300523941647aff8f21fdcd2d538f/src/i18n/i18nChangeLanguage.js#L20-L25

As a side note, I see you got the descriptions the wrong way around for "show" and "hide".

**Comment by AtkinsSJ** [comment]
Fixed in #191
