### ISSUE TITLE
Organize languages alphabetically

### ISSUE THREAD

**Issue by sebe324** [HeyPuter/puter#166]
Languages are currently organized by export default in translations.js
This menu would be easier to navigate if there was some sort of a function that organizes them in an alphabetical order.
![obraz](https://github.com/HeyPuter/puter/assets/58781463/4f4461aa-26d6-4586-81d9-e87e16c31ef0)

**Comment by AtkinsSJ** [comment]
The language selection is now done inside the Settings app:
![image](https://github.com/HeyPuter/puter/assets/222642/7e3ac48e-eb14-46ca-9e14-a8a93f4d8d51)

Some kind of sorting would still be useful though.

**Comment by jelveh** [comment]
I think this is fine now. All other improvement will be ongoing...
