### ISSUE TITLE
Make the Settings App Responsive

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#174]
Currently the Settings app is only optimized for larger screens (laptops, desktops, ...). It needs to be responsive for tablets, phones, ...

**Comment by Runanka** [comment]
I would like to work on this

**Comment by jelveh** [comment]
Hi @Runanka, any updates on this? Let me know if I should do this instead.

**Comment by Runanka** [comment]
Sorry for holding you up @jelveh. Due to some private matters, I'm not equipped to contri right now. Please de-assign me for now. I'll make it up to you on a later date. Apologies.

**Comment by jelveh** [comment]
No worries! hope everything is fine :)
