### ISSUE TITLE
"undefined" appearing in Usage tab of Settings app

### ISSUE THREAD

**Issue by AtkinsSJ** [HeyPuter/puter#180]
I get three different items listed as "undefined". These correspond to entries of the `changes` output that have no `service -> driver.interface` field set:

![image](https://github.com/HeyPuter/puter/assets/222642/8cda2fb5-5b72-4261-bc67-43ab5a78ab9e)

I don't know what these refer to, but presumably these don't use a driver, and so we need some fall-back text displayed if `driver.interface` is missing. cc @jelveh

**Comment by jelveh** [comment]
@AtkinsSJ This is not a GUI issue but more of a driver usage reporting issue.

@KernelDeimos 
The `/drivers/usage` endpoint doesn't seem to return complete information for some drivers such as `hosting`:
```
{
    "user": [
        {
            "service": {
                "driver.method": "get",
                "driver.interface": "puter-kvstore",
                "driver.implementation": "public-kvstore"
            },
            "year": 2024,
            "month": 4,
            "monthly_limit": null,
            "monthly_usage": 8
        },
        {
            "service": {
                "driver.method": "list",
                "driver.interface": "puter-kvstore",
                "driver.implementation": "public-kvstore"
            },
            "year": 2024,
            "month": 4,
            "monthly_limit": null,
            "monthly_usage": 1
        },
        {
            "service": {
                "driver.method": "select"
            },
            "year": 2024,
            "month": 4,
            "monthly_limit": null,
            "monthly_usage": 2
        }
    ],
    "apps": {},
    "app_objects": {}
}
```
In the example above, specifically, `driver.interface` and `driver.implementation` are missing and there is only `"driver.method": "select"` provided for the `hosting` driver.

**Comment by KernelDeimos** [comment]
I am happy to report, this has finally been fixed :)
