### ISSUE TITLE
Feature Request: Add some tools

### ISSUE THREAD

**Issue by cptxxx** [HeyPuter/puter#182]
I started using Puter recently & I'm having a great experience so far, but I feel like some tools like `curl` and a web browser is missing (Personally, I think a browser in a Web-based os in another browser looks cool).

**Comment by AtkinsSJ** [comment]
Hi there! Thanks for checking it out.

You're definitely right, a lot of things are missing that we'd like to have. A browser inside Puter is a lot more complicated than you'd think, but it's on the to-do list.

As for tools in the terminal, there are a lot of ones recommended by POSIX that [we're missing](https://github.com/HeyPuter/phoenix/issues/43) if you ever feel like helping out with that. But also, letting apps have terminal commands is something we're looking into. Someone implemented a [Python port](https://puter.com/app/python) recently but it can't run directly in the terminal yet.

As always, lots of things to do, and everything takes time, but we'll get there! :muscle:
