### ISSUE TITLE
Task Manager app

### ISSUE THREAD

**Issue by Zac0511** [HeyPuter/puter#189]
A Task Manager app would be useful when apps are laggy or anything like that, so a Task Manager that would allow multiple things to the user could be cool !

**Examples :**
Closing process
See RAM/CPU usage
Start tasks

**Comment by jelveh** [comment]
We should def have this. 
Aside from the mentioned uses, there's also been instances when a window refuses to close for no apparent reason, this would be helpful and a task manager would be handy!

**Comment by KernelDeimos** [comment]
Planned work in #220 is a prerequisite for this

**Comment by Zac0511** [comment]
The task manger is now in Puter, so i can close this.
