### ISSUE TITLE
Docker Image does not have self-hosted funtionality

### ISSUE THREAD

**Issue by Hiya-its-Aya** [HeyPuter/puter#194]
Os :  Sonoma 14.2.1,  M1Pro Macbook Pro 14  

As the title says. I was able to access self-hosted functionality via `npm start` in my terminal, but running `docker compose up` has produced the same functionality as it did pre-self-host alpha. Below are the logs in the application's terminal in the Docker application. 

![image](https://github.com/HeyPuter/puter/assets/74701789/08e54f7d-9c2d-4c24-9d7a-218891d4938e)

**Comment by jelveh** [comment]
PR #195 should solve this soon

**Comment by Hiya-its-Aya** [comment]
Awsome! Thank you @shuguet !
