### ISSUE TITLE
Welcome screen

### ISSUE THREAD

**Issue by Zac0511** [HeyPuter/puter#196]
I was thinking that a **welcome screen** for new users would be useful, so that new users can know how to **manage their files**, **use apps from the store**

### Examples :

- The welcome screen could explain how to manage files
- How to change settings (when the settings app will be out)
- How to use apps from the store
- How to add multiples accounts
- And other things

**Comment by KernelDeimos** [comment]
@jelveh would it be appropriate to add the `good first issue` label to this?

**Comment by jelveh** [comment]
@Zac0511 I'm going to close this in favor of the other more detailed issue you created a few days ago (#588)
