### ISSUE TITLE
Allow Clipboard API?

### ISSUE THREAD

**Issue by o0101** [HeyPuter/puter#197]
I'll investigate and aim to provide additional details as they become available, but it seems that the iframe `allow` attribute puter currently uses prevents embedded apps from using the Clipboard API, even if it would otherwise be allowed?

**Comment by KernelDeimos** [comment]
I see `clipboard-read` and `clipboard-write` in the `"allow"` attribute so I'm surprised this isn't working. Tagging @jelveh in case he has more information about this.

**Comment by o0101** [comment]
Me too! @KernelDeimos I just tested the Notepad app and it's Copy into native local clipboard works fine. So this must be a BrowserBox / CloudTabs specific issue. 

I'll close to look at a fix there. Thank you for your reply! :)
