### ISSUE TITLE
Docker deployment

### ISSUE THREAD

**Issue by q20** [HeyPuter/puter#20]
Thank you for open sourcing this project!
In my eyes, this is a perfect fit for Docker deployment, used perhaps as a way to manage/access devices at a remote site. 
Is Docker on the roadmap?

**Comment by jelveh** [comment]
There is some discussion about this [here](https://github.com/HeyPuter/puter/discussions/17) and [here](https://github.com/HeyPuter/puter/discussions/18). Let us know if you need more clarification.

**Comment by q20** [comment]
> There is some discussion about this [here](https://github.com/HeyPuter/puter/discussions/17) and [here](https://github.com/HeyPuter/puter/discussions/18). Let us know if you need more clarification.

Gotcha. Thanks.   👍
