### ISSUE TITLE
`unexpected token` error

### ISSUE THREAD

**Issue by JeffreyKroonenberg** [HeyPuter/puter#200]
Unfortunately, the following error occurred, causing it not to work: unexpected token.

**Comment by KernelDeimos** [comment]
Hello, are you able to sent a screenshot or some more context from the logs?

**Comment by spyderr67** [comment]
Not sure if this screenshot would help, I am guessing this is the same error, running on POPos
![Screenshot from 2024-04-03 20-20-02](https://github.com/HeyPuter/puter/assets/30530160/35da6104-91e8-4c1d-833c-f8bd3c7038f6)

**Comment by AtkinsSJ** [comment]
What version of node do you have? (`node --version`)

**Comment by KernelDeimos** [comment]
You're using a version of `node` that does not support the optional chaining operator. This means you're using node version 13 or earlier. The version of `node` you have installed is [past its End-of-Life date](https://endoflife.date/nodejs) for security support, so you should upgrade and ensure the old version is not still installed.

**Comment by KernelDeimos** [comment]
We have [a plan](https://github.com/HeyPuter/puter/issues/225) to make errors about this more descriptive
