### ISSUE TITLE
Docs: Local hosting with Docker needs rootless buildkit daemon running

### ISSUE THREAD

**Issue by christophberger** [HeyPuter/puter#201]
On my Manjaro (Arch)  Linux system, `docker-compose up` returned errors about a missing buildkit.

Please mention that `Rootlesskit` and `Buildkit` have to be installed, and `buildkitd` needs to run in rootless mode to make `docker-compose up` work:

```sh
rootlesskit buildkitd
git clone https://github.com/HeyPuter/puter
cd puter
docker compose up
```

**Comment by KernelDeimos** [comment]
Is this our concern or a `docker-compose` concern? tagging @shuguet for help with this

If it happens to be a `docker-compose` concern though, I'm all for including out-of-scope instructions that will help people get started. Maybe we add a file (`doc/docker-compose.md`) with any specific instructions for various distros.

**Comment by shuguet** [comment]
I am not familiar with Manjaro/Arch, all I can say is that, if you read the instructions currently on the README, it (on purpose) does not require a `git clone` of Puter to run.

I think this is most likely specific to Arch/Manjaro, and only related to #209 in the sense that I took the precaution of running as a non-root user (standard production best practice) and maybe Manjaro has additional requirements for this?
Again, I have no experience with that OS, so I can't think of anything else at the moment.

**Comment by christophberger** [comment]
Thank you for looking into it!

I guess that [this commit](https://github.com/HeyPuter/puter/commit/ab4f222e92a693ecbc6c465dc82025941ee6a6f2#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3L5) has fixed the problem by commenting out the `build: ./` statement in `docker-compose.yml`.

Now `docker compose` only pulls the image and does not attempt a local build.
