### ISSUE TITLE
Error when running Putter

### ISSUE THREAD

**Issue by ManucrackYT** [HeyPuter/puter#203]
![Screenshot_2024-04-01-02-09-33-506_com android chrome](https://github.com/HeyPuter/puter/assets/71397795/254f5d3f-5fad-4f19-88ca-b76a3cc8ca44)

**Comment by AtkinsSJ** [comment]
This suggests that `process.stdout.columns` is set to 0 for some reason. `generateSeparator()` probably does need to handle terminal widths that are less than the text's length, but even so, it's odd to get a 0 here.

**Comment by ManucrackYT** [comment]
I didnt touch anything, it just loaded that

**Comment by KernelDeimos** [comment]
The latest commit patches this issue and makes this work properly in very small terminal widths, which is where I'm able to reproduce the error.

However, you don't have a very small terminal width in your screenshot. You're likely to encounter visual glitches which could potentially make the dev console unusable even if you don't get this exception thrown. If you provide the following I'll investigate further:
- operating system this happening on
- terminal emulator used (if applicable)
- shell used

**Comment by ManucrackYT** [comment]
I'm using a NodeJS server, made on Pterodactyl. This is hosted on Debian 11

**Comment by AtkinsSJ** [comment]
OK, looks like Pterodactyl uses Docker internally, so this would apply:
> I figured it out - Docker doesn't provide the terminal width so this is actually expected behavior
> https://github.com/HeyPuter/puter/issues/208#issuecomment-2031381495

So we just need to make sure nothing assumes that the terminal size is reasonable.

**Comment by ManucrackYT** [comment]
Everything works with the latest Puter version, thanks
