### ISSUE TITLE
Default user does not work 

### ISSUE THREAD

**Issue by PalRist** [HeyPuter/puter#204]
When trying the default credentials, a red box appears when trying to log in. Using my ipad pro i’ve tried several browsers, all with the same result.

I am hosting release 92b3f4f on a RPi5.
![IMG_0131](https://github.com/HeyPuter/puter/assets/10531653/1fed6c66-e499-44a6-b50d-0892f843c81c)

**Comment by zarevskaya** [comment]
Same thing here :) You are not alone...

**Comment by KernelDeimos** [comment]
@PalRist @zarevskaya this default password was removed, the password is now randomized and it's printed in the dev console. Any ideas on what we could change to make this update more visible?

**Comment by zarevskaya** [comment]
Hello, thanks for the information.

Yes, remove:

Default User

By default, Puter will create a user called default_user with the password changeme 

by the new information.

Have a nice day. 😃

**Comment by KernelDeimos** [comment]
Thanks, README.md is updated

**Comment by KernelDeimos** [comment]
Login error above is likely due to domain config mismatch. Config documentation in README.md was updated - also added [this issue](https://github.com/HeyPuter/puter/issues/230) to track changes that will avoid errors like this
