### ISSUE TITLE
Creation of account fails when using Firefox 123

### ISSUE THREAD

**Issue by ninalanyon** [HeyPuter/puter#21]
I followed the instructions to install puter locally.  I then pointed Firefox at locahost:4000 and got a log in dialog that offered to create an account.  Fillied in the username, etc. and hit the button but it simply reopened  the dialog.  In Vivalid it works.

**Comment by jelveh** [comment]
It shouldn't ask you to create an account at all, but when you try to create one does it give you an error? if not, is there anything in the developer console?

**Comment by jelveh** [comment]
Is this still an issue?
