### ISSUE TITLE
Setting to change user storage amount

### ISSUE THREAD

**Issue by KernelDeimos** [HeyPuter/puter#211]
### Self-hosters are not supposed to have a storage limit

I'm pinning this issue because I want everyone to know we're working on it.

The production version of puter (puter.com) has a storage limit for each user. The storage limit is tied into various parts so a little bit of refactoring is needed to remove the limit for self-hosters.

This issue thread will track our progress.

**Comment by nimit2801** [comment]
I can pick this up! Let me know if this is something we would want to focus on

**Comment by AtkinsSJ** [comment]
Likewise, references to getting referrals also don't make a lot of sense when self hosted.

**Comment by KernelDeimos** [comment]
> I can pick this up! Let me know if this is something we would want to focus on

You may, we have a few requirements for this feature that you'll need to keep in mind:
- turning on/off storage limits should be a configuration option (default will be off)
- the apparent "storage limit" should appear as the actual capacity of the filesystem Puter is running on for all users when storage limits are off

**Comment by nimit2801** [comment]
> > I can pick this up! Let me know if this is something we would want to focus on
> 
> You may, we have a few requirements for this feature that you'll need to keep in mind:
> 
>     * turning on/off storage limits should be a configuration option (default will be off)
> 
>     * the apparent "storage limit" should appear as the actual capacity of the filesystem Puter is running on for all users when storage limits are off

Interesting case, self host once and will reflect on how to make this option available. Because certainly a users motivation for using this would be to get more space and if that we cannot suffice somewhere we're not giving the freedom to the user.

**Comment by KernelDeimos** [comment]
@nimit2801 I added you to assignees. Let me know if at any point you get busy and can't dedicate as much time to this and I'll take over in the case - this is something that's high-priority and I was planning to do myself, but if you're willing to take it on that gives me room to fix some other issues instead.

**Comment by nimit2801** [comment]
> @nimit2801 I added you to assignees. Let me know if at any point you get busy and can't dedicate as much time to this and I'll take over in that case - this is something that's high-priority and I was planning to do myself, but if you're willing to take it on that gives me room to fix some other issues instead.

Thank you for assigning this to me! I actually related a lot to this bug/issue and that's why wanted to work on this.

**Comment by nimit2801** [comment]
![image](https://github.com/HeyPuter/puter/assets/53462249/57e9df83-6ed5-42cd-8a62-72f02af587ed)
I started development, I'm on my windows machine, but couldn't go beyond this. There is this blank screen, should I change anything else in config?

**Comment by nimit2801** [comment]
> ![image](https://private-user-images.githubusercontent.com/53462249/319113720-57e9df83-6ed5-42cd-8a62-72f02af587ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMzk0MDIsIm5iZiI6MTcxMjIzOTEwMiwicGF0aCI6Ii81MzQ2MjI0OS8zMTkxMTM3MjAtNTdlOWRmODMtNmVkNS00MmNkLThhNjItNzJmMDJhZjU4N2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDEzNTgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMjI3MjI4YzlhMWIxMDE5ZjgyM2I5OTk2MzBlYjk1YjZjYzg1ZmNkMmZmOWM5ZjE4MmZhN2M1M2Y3NTJiZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Eqh4WK-tRH-dxGriewTjLuvUT_3vAJ5uYD2VRythArE) I started development, I'm on my windows machine, but couldn't go beyond this. There is this blank screen, should I change anything else in config?

@KernelDeimos any suggestions on how to fix this? is this common issue?

**Comment by vineeth-vk11** [comment]
Hey @nimit2801 this is not a common issue. Below points might help.

1. Make sure you have the latest commits
2. Check your node version, I am running v20.11.1 and it works fine
3. Try opening the URL in incognito mode of your browser

If you need help, reach out to me on discord, username - vineethvk11

**Comment by KernelDeimos** [comment]
Also check the dev console for CORS errors or anything like that. This screenshot is what it looks like when it can load the gui but can't talk to the API. Oh, also maybe Windows doesn't allow subdomains on the `localhost` domain without configuration; [try adding api.puter.localhost manually](https://github.com/HeyPuter/puter/blob/main/doc/self-hosters/domains.md#windows) and please let me know if that turns out to be the issue because if that's the case I need to update the documentation.

**Comment by KernelDeimos** [comment]
@nimit2801 I merged [the fix vineeth contributed](https://github.com/HeyPuter/puter/pull/223), but there are further improvements which can be made:
- capacity is shown as free storage instead of total, which might not always be applicable
- I think `diskusage` might not always report the storage of the device that's being used (that's a speculation)
- the storage shown isn't accurate on my system (Arch linux)
