### ISSUE TITLE
Little mistake in Using Docker Compose

### ISSUE THREAD

**Issue by zarevskaya** [HeyPuter/puter#213]
Hi ;)

There is a problem maybe, **I think**.

mkdir puter && cd puter
mkdir -p puter/config puter/data
sudo chown -R 1000:1000 puter
wget https://raw.githubusercontent.com/HeyPuter/puter/main/docker-compose.yml
docker compose up

Otherwise we have a puter folder with a puter folder inside.

It's not better to do that?:

mkdir -p puter/config puter/data
sudo chown -R 1000:1000 puter
cd puter
wget https://raw.githubusercontent.com/HeyPuter/puter/main/docker-compose.yml
docker compose up

But edit like this in the docker-compose:

volumes:
      - ./config:/etc/puter
      - ./data:/var/puter

Have a nice day!

**Comment by KernelDeimos** [comment]
This was actually intentional; see [this discussion](https://github.com/HeyPuter/puter/issues/209#issuecomment-2031095673) for an explanation.

I'll keep this issue open for a bit though while I think of a better way to reflect this in the documentation. Maybe we shouldn't include the parentmost directory to avoid confusion - @shuguet, what are your thoughts on this?

**Comment by zarevskaya** [comment]
Ok, thanks for the answer!

**Comment by shuguet** [comment]
Well, that's what I initially suggested, as unless there are plans to have more containers in the future (additional services running in different containers, external database, etc.) it is bound to cause this kind of confusion.

While what's being done right now is idiomatic to docker compose *when there's more than one service* it might me confusing when there isn't.

I think we can get away with maybe a bit of explanation in the docs?
Or simply revert to my initial suggestion of `config` and `data` for now, and add a migration step later (stop containers, create service folder, move data & config folder into newly created top level folder, update docker-compose, done).

**Comment by KernelDeimos** [comment]
`README.md` is updated
