### ISSUE TITLE
no keyboard typing in terminal from Android

### ISSUE THREAD

**Issue by strusty** [HeyPuter/puter#217]
just open up terminal on brave on Pixel 7

keyboard should work, but it is not acknowledged

cool system.

**Comment by KernelDeimos** [comment]
I get the same issue well. An xtermjs demo seems to work on my phone (Pixel 7a), but Puter's terminal somehow does not. I've known about this for some time but I'm not entirely sure how to start investigating this. I think remote debugging with chrome dev tools might be where I start.

**Comment by AtkinsSJ** [comment]
This is a known issue, see also https://github.com/HeyPuter/phoenix/issues/18 and https://github.com/HeyPuter/terminal/issues/6. My best explanation is [here](https://github.com/HeyPuter/phoenix/issues/18#issuecomment-1954122314).
