### ISSUE TITLE
change_username endpoint is not working

### ISSUE THREAD

**Issue by MohamedElashri** [HeyPuter/puter#222]
**Issue Description**
When trying to change the username of the session (or account) you will get 500 error (Internal Server Error)

**Steps to Reproduce**

Follow the guidelines to start puter server
```
git clone https://github.com/HeyPuter/puter
cd puter
npm install
npm start
```

go to 
http://puter.localhost:4100/

then go to account and try to change the username to anything

This also happens if you are using the docker container 

**Expected & Actual Behavior**

Changing the username should work, and actually changing the username. 
**Addition Information or Screenshots (if applicable)**

**Tooling**
- [x] Development (`npm run start`)
- [x] Docker (via `docker run`)
- [x] Docker (via `docker-compose`)

**Puter version (if accessible)**
Version: v2.0.2-42-ga04cac6

**Comment by jelveh** [comment]
Seems to be caused by the syntax differences between sqlite and mysql. looping in @KernelDeimos .

**Comment by KernelDeimos** [comment]
I just [pushed a commit](https://github.com/HeyPuter/puter/commit/b055c5cdad74f2bfafb253b297eb301ff696715d) - please pull the latest version and let me know if this is working for you now

**Comment by jelveh** [comment]
It's fixed for me.

**Comment by MohamedElashri** [comment]
I can confirm that it is now fixed.
