### ISSUE TITLE
Add a version check to the start script

### ISSUE THREAD

**Issue by AtkinsSJ** [HeyPuter/puter#225]
Currently, if someone has too old a version of Node.js, the errors they get are confusing - often complaining about an unexpected `.` somewhere, (eg [this](https://github.com/HeyPuter/puter/issues/200#issuecomment-2034438349)) or other syntax issues. It would be more helpful if we could check the version when starting Puter, and display a clearer error.

[`process.version`](https://nodejs.org/api/process.html#processversion) or [`process.versions.node`](https://nodejs.org/api/process.html#processversions) might be useful for this. The startup script is [`run-selfhosted.js`](https://github.com/HeyPuter/puter/blob/main/run-selfhosted.js).

It's not entirely clear what our lowest supported version is, so that will need some testing too.

**Comment by KernelDeimos** [comment]
I may have went over the top a little
![image](https://github.com/HeyPuter/puter/assets/7225168/1c398f94-2500-4aec-b247-911edf0840be)

**Comment by KernelDeimos** [comment]
[this is done now](https://github.com/HeyPuter/puter/commit/4a2fa5a29f4e0127a416534c969ccb3987144ab4)

**Comment by AtkinsSJ** [comment]
> I may have went over the top a little

Nah, this is great! Should help cut down on support tickets
