### ISSUE TITLE
It seems that the API call to obtain websites is broken

### ISSUE THREAD

**Issue by kveroneau** [HeyPuter/puter#228]
When I went to use [Puter Blogger](https://puter.com/app/puterblogger) today, it now hangs, and when looking at the **Network console**, it shows that I got a `401: Unauthorized` from the api endpoint.  I checked this repo to see if anything was added for auth in here, and I couldn't find anything with that sort of change. I should open a new issue, but [Puter Docs](https://docs.puter.com) is also down, which I was going to use as a potential resource to see if any API got changed overnight.  The blogger app did work yesterday.

If you need anymore information from me, please reach out and let me know what I should provide, or if an API did change, let me know that and close the issue.  Many thanks.

**Comment by KernelDeimos** [comment]
[this has been fixed](https://github.com/HeyPuter/puter/commit/08838c989ecb464774a446739c5ee7410dc2a836). I'm leaving this PR open for a bit longer - let me know whether everything seems to be working as expected
