### ISSUE TITLE
@heyputer/backend import error

### ISSUE THREAD

**Issue by says112** [HeyPuter/puter#236]
![Снимок экрана (762)](https://github.com/HeyPuter/puter/assets/22127398/88c1ab06-ae13-48da-8f92-1fe8ea4a112d)
He's not going to.

**Comment by Kreijstal** [comment]
Nooooo they lied to me, I'll never recover

**Comment by KernelDeimos** [comment]
@says112 @Kreijstal - did you run `npm install`?

**Comment by KernelDeimos** [comment]
I tested a fresh clone without running `npm install` and successfully reproduced the error, so I'm closing this issue. I'm also going to put the original title back because it's funny.
