### ISSUE TITLE
It is not possible to log in.

### ISSUE THREAD

**Issue by says112** [HeyPuter/puter#239]
It is not possible to log in. Where can I change the settings?
![Снимок экрана (763)](https://github.com/HeyPuter/puter/assets/22127398/af075557-8b52-4e9b-b341-a43a2f36244b)
![Снимок экрана (765)](https://github.com/HeyPuter/puter/assets/22127398/18f05c15-9bb8-41c4-b8f3-0c3f50e53db6)

**Comment by KernelDeimos** [comment]
Hi, this is happening because you're accessing the page with an IP address directly, so it can't access the `api.` subdomain.

Check our documentation for [setting up a domain](https://github.com/HeyPuter/puter/blob/main/doc/self-hosters/domains.md)

Also relevant is issue #230 - we're planning on making this setup step easier

**Comment by says112** [comment]
changed the settings now only the blue screen.blue
![Снимок экрана (766)](https://github.com/HeyPuter/puter/assets/22127398/e8a3d422-5fc2-448a-b71d-9454e710c1b2)
![Снимок экрана (765)](https://github.com/HeyPuter/puter/assets/22127398/a72bf5a9-8a92-4a5e-a58e-840c793fa5f8)

**Comment by says112** [comment]
![Снимок экрана (768)](https://github.com/HeyPuter/puter/assets/22127398/2db85646-463c-4a3d-9d52-e71565f9690c)

**Comment by says112** [comment]
![Снимок экрана (769)](https://github.com/HeyPuter/puter/assets/22127398/faa5c6a6-8a2f-430c-aca9-ed5ea8a450b0)

**Comment by says112** [comment]
![Снимок экрана (770)](https://github.com/HeyPuter/puter/assets/22127398/770e177e-66c9-47bc-b9f6-c2f528e0c8a6)

**Comment by says112** [comment]
I do it through the domain name, an interface error is written
![Снимок экрана (772)](https://github.com/HeyPuter/puter/assets/22127398/4210129f-a613-459a-834e-0d28d531189b)

**Comment by KernelDeimos** [comment]
It looks like you're adding the domain to `/etc/hosts` on a remote computer, and then attempting to access that from your current machine. Unfortunately that won't work; the domain needs to resolve on the client (the computer you're accessing from)

**Comment by says112** [comment]
I added it to Windows, but the blue screen still doesn't work.

**Comment by KernelDeimos** [comment]
I have an idea... I'll update in a few minutes

**Comment by KernelDeimos** [comment]
Are you able to join our Discord server or a Google Meet room? It might be easier to help that way. I was going to try adding an experimental flag to disable the subdomain but it's baked in pretty deep

**Comment by says112** [comment]
Yes Discord

**Comment by KernelDeimos** [comment]
Resolved on Discord
