### ISSUE TITLE
preserve the search part of a puter app url

### ISSUE THREAD

**Issue by triptych** [HeyPuter/puter#242]
When I pass a url param to my puter app, it gets stripped after passed into the application. This is odd and could be considered "data loss". Especially if I wanted to copy and share the url.

so https://puter.com/app/args-app-test-s1sut8rqixf?foo=monkey becomes https://puter.com/app/args-app-test-s1sut8rqixf

but I am requesting that the puter.com site keep the query params in the browser url

**Comment by jelveh** [comment]
As discussed on discord, I think this is a good idea. It's also a great good first issue, if nobody takes it on in a few days I'll just do it.

**Comment by Xiayucheng1212** [comment]
Hi, @jelveh I would like to work on this issue.

**Comment by jelveh** [comment]
@Xiayucheng1212 awesome, go for it :)
