### ISSUE TITLE
*** SYSTEM IS IN AN INVALID STATE ***

### ISSUE THREAD

**Issue by MILO123PRO** [HeyPuter/puter#243]
**Issue Description**
Console starts spamming:

 
(
I
N
V
A
L
I
D
 
S
Y
S
T
E
M
 
S
T
A
T
E
.
.
.
)
:
 
f
a
i
l
e
d
 
t
o
 
i
n
i
t
i
a
l
i
z
e
 
s
e
r
v
i
c
e
s
 
(
1
)

[
3
1
;
1
m
 
[
a
l
a
r
m
]

[
0
m
 
a
c
t
i
v
e
-
t
r
u
m
p
e
t
-
4
6
6
3
 
(
p
r
o
c
e
s
s
:
u
n
h
a
n
d
l
e
d
R
e
j
.
.
.
)
:
 
C
a
n
n
o
t
 
r
e
a
d
 
p
r
o
p
e
r
t
i
e
s
 
o
f
 
u
n
d
e
f
i
n
e
d
 
(
r
e
a
d
i
n
g
 
'
p
r
e
p
a
r
e
'
)
 
(
5
)
 *** WARNING ** WARNING ** WARNING ***
 *** SYSTEM IS IN AN INVALID STATE *** 
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                     ┃
┃  Puter is now live at: http://puter.localhost:4100  ┃
┃  Type web:dismiss to dismiss this message           ┃
┃                                                     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
**Steps to Reproduce**
Try to install puter inside an server on pterodactyl
**Expected & Actual Behavior**
To propertly work
**Addition Information or Screenshots (if applicable)**
![imagen](https://github.com/HeyPuter/puter/assets/64213421/32274e41-43a1-4dd8-8d83-c5df7c44fc10)
**Tooling**
- [ ] Development (`npm run start`)
- [x] Self-Hosted (`node run-selfhosted.js`)
- [ ] Docker (via `docker run`)
- [ ] Docker (via `docker-compose`)

**Puter version (if accessible)**
Right now's latest version.
> Click the profile button on the top-right, then "Settings". The version number will be printed at the bottom

**Comment by nottherealsanta** [comment]
update this file : `/packages/backend/src/services/database/sqlite_setup/0003_user-permissions.sql`

```sql
DROP TABLE `user_to_user_permissions`;
CREATE TABLE `user_to_user_permissions` (
    "issuer_user_id" INTEGER NOT NULL,
    "holder_user_id" INTEGER NOT NULL,
    "permission" TEXT NOT NULL,
    "extra" JSON DEFAULT NULL,

    FOREIGN KEY("issuer_user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY("holder_user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY ("issuer_user_id", "holder_user_id", "permission")
);

DROP TABLE "audit_user_to_user_permissions";
CREATE TABLE "audit_user_to_user_permissions" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,

    "issuer_user_id" INTEGER NOT NULL,
    "issuer_user_id_keep" INTEGER DEFAULT NULL,

    "holder_user_id" INTEGER NOT NULL,
    "holder_user_id_keep" INTEGER DEFAULT NULL,

    "permission" TEXT NOT NULL,
    "extra" JSON DEFAULT NULL,

    "action" TEXT DEFAULT NULL,
    "reason" TEXT DEFAULT NULL,

    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY("issuer_user_id") REFERENCES "user" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY("holder_user_id") REFERENCES "user" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
```

**Comment by MILO123PRO** [comment]
I did it, but it didnt change anything because its the same, here is the old one without any change even if its the same:
[0003_user-permissions.sql](https://github.com/HeyPuter/puter/files/14898007/0003_user-permissions.txt)
I still get the error, i tried NodeJS 14, 16 and 19.
Also between those 1 line-per-letter line i see this:
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃  Node.js version 19 is past EOL by at least 10 months;                ┃
┃  Everything should work, but you should still upgrade.                ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
 *** WARNING ** WARNING ** WARNING ***
That error appears no matter what version i use.
My current NodeJS version is: v19.0.0

**Comment by AtkinsSJ** [comment]
A small note about Node versions: Node treats even numbered versions as long-term support, but odd-numbered ones are only supported for a few months. You can see [here](https://nodejs.org/en/about/previous-releases) that currently, NodeJS 18, 20 and 21 are actively supported by them.

**Comment by nottherealsanta** [comment]
Just dropped the table before recreating them.

**Comment by KernelDeimos** [comment]
OP: can you type `alarm:info active-trumpet-4663` into the console?

**Comment by KernelDeimos** [comment]
> Just dropped the table before recreating them.

Do you know why this was necessary? The version number in sqlite PRAGMA `user_version` is supposed to increment, and then 
SQLiteDatabaseAccessService is not supposed to attempt to apply this file again

**Comment by KernelDeimos** [comment]
@nottherealsanta this is now fixed properly: https://github.com/HeyPuter/puter/commit/eb66848aeecab888da86cbbe22dfbc0c90503fc0
