### ISSUE TITLE
Broadcast to apps when certain settings change

### ISSUE THREAD

**Issue by AtkinsSJ** [HeyPuter/puter#247]
It would be useful for apps to be able to match Puter's colour scheme, language, and such. To make this possible, Puter could broadcast this information to apps whenever it changes, and also send it when an app first reports that it is `READY`.

For example, the theme broadcast could be something like:
```js
{
  name: 'theme',
  palette: {
    windowHue: '200',
    // ...
  },
  darkMode: true,
}
```
and then apps can do what they want with this. Eventually, fonts could be included in there once we have that as a setting.

- [x] Broadcast messages
- [x] Puter.js event listeners to make broadcasts easier to deal with
- [x] Send broadcast messages to newly launched apps
- [x] Theme broadcast
- [x] Language broadcast

**Comment by jelveh** [comment]
Done! :)
