### ISSUE TITLE
The code app doesnt work if I run puter locally

### ISSUE THREAD

**Issue by GerardPolloRebozado** [HeyPuter/puter#25]
It gives error accessing the page code.puter.com
Using another browser gives the same error.
Why is the app hosted on another server and not integrated directly using the [vscode page](https://vscode.dev/)

**Comment by jelveh** [comment]
What error are you seeing? also, what browser?

> Why is the app hosted on another server and not integrated directly using the [vscode page](https://vscode.dev/)

Because we had to create a whole integration for it.

**Comment by GerardPolloRebozado** [comment]
Ok now its working the code app but other apps like recorder are showing the same error as code was showing before.
the error is the connection has closed unexpected. 
Im using chrome 122.0.6261.95

**Comment by jelveh** [comment]
ooof! Looking into it.

**Comment by KernelDeimos** [comment]
> > Why is the app hosted on another server and not integrated directly using the [vscode page](https://vscode.dev/)
>
> Because we had to create a whole integration for it.

A bit more on this in case you find it interesting, we first tried making an extension for vscode but there were limitations in the filesystem provider interface available for extensions that weren't present in the internal one. We also wanted to override menu actions to use Puter file dialogs. We eventually realized that the correct approach was to fork vscode, because what we needed wasn't an extension, but instead platform support.

**Comment by GerardPolloRebozado** [comment]
> Another user experienced an issue like this earlier today. Can you check the "About" app (Puter logo in taskbar) and copy the line of text before the storage bar?
> 
> ![image](https://private-user-images.githubusercontent.com/7225168/310269907-ff0dfe25-44fe-4ac8-98d5-2292e68a28c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NzY5MjAsIm5iZiI6MTcwOTY3NjYyMCwicGF0aCI6Ii83MjI1MTY4LzMxMDI2OTkwNy1mZjBkZmUyNS00NGZlLTRhYzgtOThkNS0yMjkyZTY4YTI4YzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMjIxMDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2Y5NDRhNTBmNjhiOTA3ZWE5Mjc3NWUwOGFlZWZjZGUzNDdmNmY4NzE1ZDI5MDEyNmRmN2Q3MjdjY2U2OTIxYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.crqByefqEGpQuge4xkPBYNLIDDYsPYOlXvaHEGQYZNQ)


This is what appears: Version: v1.2.40-beta • Server: london • Deployed: Tue Mar 05 2024 22:47:07 GMT+0100 (hora estándar de Europa central)
Now all apps seem to work

**Comment by GerardPolloRebozado** [comment]
> > > Why is the app hosted on another server and not integrated directly using the [vscode page](https://vscode.dev/)
> > 
> > 
> > Because we had to create a whole integration for it.
> 
> A bit more on this in case you find it interesting, we first tried making an extension for vscode but there were limitations in the filesystem provider interface available for extensions that weren't present in the internal one. We also wanted to override menu actions to use Puter file dialogs. We eventually realized that the correct approach was to fork vscode, because what we needed wasn't an extension, but instead platform support.

I discovered this idea on the selfhosted reddit so I suppose the idea of the project is for selfhosting and not as a cloud product, are there any plans on making the apps like the fork of vscode to be able to run locally? Also with the errors I got I saw that the recorder is also on another server and not running localy. Does this happens with all apps? or only some of them?

**Comment by KernelDeimos** [comment]
All apps for the moment. We're working towards allowing apps to be discovered from a local instance as well as puter.com (when we open source the "kernel")

**Comment by jelveh** [comment]
Also in case you're wondering about self-hosting [it's coming soon](https://github.com/HeyPuter/puter/discussions/18)
