### ISSUE TITLE
Set and update TrayIcons

### ISSUE THREAD

**Issue by aurium** [HeyPuter/puter#256]
I see you have a `src/UI/UITaskbar.js` and a `toolbar` element, but as far as I could see, it has no system tray.

That is a useful UI for permanent notification and can replace windows for background services.

A SystemTray implementation needs:
- TrayIcon creation with linked app ownership.
- TrayIcon update for all features.
- TrayIcon destruction.
- TrayIcon features:
  - icon from any kind of image (from JPG to SVG), as a url or data url.
  - title to inform the user with a mouse-over.
  - drop-down menu, allowing to expose methods to the user.

**Comment by KernelDeimos** [comment]
This will be tracked by #435 - please watch that issue for updates
