### ISSUE TITLE
Windows Host Doesn't Work

### ISSUE THREAD

**Issue by RamboRogers** [HeyPuter/puter#26]
I've attempted to build on LTS and current node version in two different Windows 11 machines. The app starts, but the browser shows a connection error.

![image](https://github.com/HeyPuter/puter/assets/7763805/ef13eff7-98bc-487d-aaf8-b3bc12067fc1)

**Comment by jelveh** [comment]
Are you using a VPN? If yes, turn it off.

**Comment by RamboRogers** [comment]
This is a new Windows host running in Proxmox with the firewall turned off.  I used an older windows host and have the same error.  There is no VPN and no changes to the OS outside of windows updates.

I think i figured it out, it says in the documentation is uses the next free port, this isn't true.  It's trying to listen on the SAME port as another process I think.  This is the default port for NX/Nomachine remote desktop.

![image](https://github.com/HeyPuter/puter/assets/7763805/08935263-a66a-4237-9187-41ae1f843232)

I'm changing the port to test.

![image](https://github.com/HeyPuter/puter/assets/7763805/b6280ea6-b2e8-471f-a371-658b17328644)

It works! This is such a cool product!!!!

![image](https://github.com/HeyPuter/puter/assets/7763805/57674867-0953-45dd-839b-a64adc0351e2)

**Comment by RamboRogers** [comment]
I think the port contention issue is a bug, but maybe a feature enhancement?

**Comment by jelveh** [comment]
Nice! Glad it's working now. I'm gonna keep this issue open because the port discovery should work consistently. I'll debug it on a Windows machine later today, in the meantime if you find the fix please do a PR 💪

**Comment by jelveh** [comment]
I'm having a hard time reproducing this. The port increment is working as expected on Windows for me.

**Comment by RamboRogers** [comment]
I'm using windows 11 pro and the other is windows 11 home.

**Comment by jelveh** [comment]
For the life of me I can't reproduce this. I'll try more creative ways and will let you know if I can reproduce/fix.

**Comment by KernelDeimos** [comment]
@RamboRogers have you tried the new self-hosted server yet? I'm curious if you'll reproduce the same issue there; it's a pretty massive update so it may have conveniently slipped away
