### ISSUE TITLE
Consider enabling PWA installation 

### ISSUE THREAD

**Issue by waynebloss** [HeyPuter/puter#27]
It would be great if puter.com worked as a PWA. I tried installing it on my phone but the home screen icon simply opened the site in my default browser.

As a PWA, the address bar and other browser controls would be hidden, giving more space to work.

**Comment by jelveh** [comment]
Sounds like a good idea. I'm gonna look into this. In the meantime, if you're good at building PWAs, feel free to submit a PR 🔥
