### ISSUE TITLE
Self-hosted Docker Compose starts but container stops shortly after

### ISSUE THREAD

**Issue by mikesellt** [HeyPuter/puter#287]
**Issue Description**
Running Puter via Docker Compose on a Synology NAS.  Container seems to start, but then stops with the error: "Cannot find module '/opt/puter/app/run-self-hosted.js'"  The config files are not created in the /config folder, and Puter isn't available on port 4100.

**Steps to Reproduce**
Run container

**Expected & Actual Behavior**
Container remains running and Puter is reachable

**Addition Information or Screenshots (if applicable)**
Here's a screenshot of the error:
![image](https://github.com/HeyPuter/puter/assets/67391933/6dcad162-6ac2-4d5c-aa27-8642134e991b)

And here's a copy of my Docker Compose, which is altered slightly for user permission and volumes:
services:
  puter:
    container_name: puter
    image: ghcr.io/heyputer/puter:latest
    pull_policy: always
    # build: ./
    restart: unless-stopped
    ports:
      - '4100:4100'
    environment:
      TZ: America/Boise
      # CONFIG_PATH: /etc/puter
      PUID: 1026
      PGID: 100
    volumes:
      - ./config:/etc/puter
      - ./data:/var/puter
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://puter.localhost:4100/test || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s

**Tooling**
- [ ] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [ X] Docker (via `docker-compose`)

**Puter version (if accessible)**
> Click the profile button on the top-right, then "Settings". The version number will be printed at the bottom

**Comment by ArthurMTX** [comment]
Hi! Same issue here. Cloned the while repo and started the container and I've got the same error. 

Container is exiting and config files aren't created.

![image](https://github.com/HeyPuter/puter/assets/78091139/c74c38c1-5868-47ff-a886-dd16d3e76827)

**Comment by KernelDeimos** [comment]
@mikesellt @ArthurMTX can you re-test and let me know if this persists? I think I just fixed it

**Comment by mikesellt** [comment]
Looks like it made it further!  Getting another error now.  Looks like a permissions issue.

**Comment by KernelDeimos** [comment]
That's puzzling... it shouldn't be trying to access `/var/puter` unless that directory already exists, but the Dockerfile doesn't create it.

**Comment by KernelDeimos** [comment]
@mikesellt I made a change to the Dockerfile - let me know if you have any luck with it

**Comment by ArthurMTX** [comment]
For me it works perfectly!

**Comment by ArthurMTX** [comment]
Also got the error 'Cannot write to /var/puter'. Fixed it by setting the rights permissions :
`sudo chown -R 1000:1000 puter`

**Comment by KernelDeimos** [comment]
> Also got the error 'Cannot write to /var/puter'. Fixed it by setting the rights permissions : `sudo chown -R 1000:1000 puter`

I see now that it's the docker compose file, not the Dockerfile or image, which uses /etc/puter and /var/puter, and I now recall that it was done this way by my own recommendation, and my recent change breaks the mount :sweat_smile: so your solution is ideal.

Is this generally expected for docker volumes?

**Comment by brhahlen** [comment]
The `PUID` and `PGID` environment variables seem to be disregarded on startup for me.
I've set them to 1001 and 900 respectively, but Puter actively asks for 1000:1000

**Comment by ArthurMTX** [comment]
The user UID 1000 and GID 1000 correspond to the `node` user inside the container image, that's why Puter keep asking for 1000:1000, because its environment is specifically configured to operate under the `node` user.

Therefore, setting `PUID: 1000` and `PGID: 1000` may seem redundant and have no impact on the container, but it may be useful for documentation, standardization, and future protection (may be wrong).
