### ISSUE TITLE
Error "authentication token not supported" while downloading a file

### ISSUE THREAD

**Issue by Zac0511** [HeyPuter/puter#288]
I tried downloading an **HTML file** to edit it with my local text editot, but when i open the file, there is `{"code":"token_unsupported","$":"heyputer:api/APIError","message":"This authentication token is not supported here.","status":401}` written inside.

If it can help, here's some info about the file i tried modifing and downloading :

- File type : **HTML**
- File size : **60.69 MB**
- File is used as a website's **index.html file**

Also it takes a **really long time** to be saved in the Puter's code app, but at least it works this way.

**Comment by KernelDeimos** [comment]
this should be fixed now

**Comment by Zac0511** [comment]
> this should be fixed now

Yeah its fixed now
