### ISSUE TITLE
Official website down

### ISSUE THREAD

**Issue by onlineapps-cloud** [HeyPuter/puter#30]
https://puter.com/
500 Internal Server Error
nginx/1.18.0 (Ubuntu)

**Comment by jelveh** [comment]
What country are you accessing Puter from? I have to ask since we have servers in different countries and we're not getting any alerts from the monitors.

**Comment by onlineapps-cloud** [comment]
hi, from Poland, right now, all work fine.

**Comment by shamrat05** [comment]
Hey is it down currently? I get no response from playground
