### ISSUE TITLE
Guest account username/password modification while un-logged in

### ISSUE THREAD

**Issue by Zac0511** [HeyPuter/puter#300]
I discovered that it is possible to modify the guest's account password and username from the settings :
![image](https://github.com/HeyPuter/puter/assets/83874244/f5d5392a-37fa-4e3c-acde-a6ca43777e4f)
Because this a **guest account**, this should be disabled while in guest

**Comment by jelveh** [comment]
I think this would make for a good starter issue and I've labeled it as such. If nobody picks it up in a few days, I'll do it.
Basically, the option to change password should not even show up if the user account is temporary.
