### ISSUE TITLE
which prerequsites are needed

### ISSUE THREAD

**Issue by LeOS-GSI** [HeyPuter/puter#301]
I have tried to install on PoP!OS and on Mint 20. on both system, the script is failing.

Could you please add a section with which prerequsites are needed in your Readme file ?

**Comment by half-real-SCRACX** [comment]
Are you having similar (or the same) issues to #294?

**Comment by LeOS-GSI** [comment]
Yes, seems so. But I habe ignored that, because I habe tried in 2 different Linux distros

**Comment by KernelDeimos** [comment]
Hello, this issue has been here for some time so I'm going to check-in before closing it. Was this ever resolved?

Prerequisites are simple: node. If the version of node is too old, Puter's launch script will complain about it and tell you what necessary features are missing from that version.

Windows is supported in development builds (`main` branch) - this just happened today.
