### ISSUE TITLE
Null Error Message in Puter PDF

### ISSUE THREAD

**Issue by subhadipbhowmik** [HeyPuter/puter#302]
**Issue Description**
When attempting to Open the PDF Application it Showing a Message Missing PDF: "https://pdf.puter.com/null"

**Steps to Reproduce**
1. Click on the Start Button
2. Find PDF Application
3.  Choose it. Open the Application

**Expected & Actual Behavior**
There should be no warning message like this.

**Addition Information or Screenshots (if applicable)**
<img width="960" alt="putter-pdf" src="https://github.com/HeyPuter/puter/assets/57017965/0f1bfcbf-2423-4fcf-b782-1f7dd2fa275f">

**Puter version (if accessible)**
Version: 2.1.0

**Comment by jelveh** [comment]
I've decided to keep this in for now since we're going to open-source the reader (well, it's 99.999 pdf.js anyway!) and hopefully somebody can pick up error handling.
