### ISSUE TITLE
Unable to revert to original puter desktop background

### ISSUE THREAD

**Issue by Eric-Lighthall** [HeyPuter/puter#318]
**Issue Description**
Users can change their desktop background to a solid color or uploaded picture but there is no way to revert to the original puter background.

**Steps to Reproduce**

1. Right-click on screen
2. Change desktop background...
3. Choose color/image and apply changes
4. Unable to revert to original desktop background

**Expected & Actual Behavior**
Users should have the option of resetting to the default puter background

**Addition Information or Screenshots (if applicable)**
https://github.com/HeyPuter/puter/assets/55029902/8511c2b6-f4b6-4cc5-a7e6-9cdb286c88aa

**Tooling**
- [x] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [ ] Docker (via `docker-compose`)

**Puter version (if accessible)**
4.1.0

**Comment by Eric-Lighthall** [comment]
I'd like to work on this issue. Could I be assigned to it or start working on a fix? Thanks.

**Comment by jelveh** [comment]
Assigned. Go for it @Eric-Lighthall :)

**Comment by KernelDeimos** [comment]
Maybe we should allow contributors to self-assign for now, and then change it back when we notice people start to abuse it.
