### ISSUE TITLE
X-Frame-Options error in the latest version

### ISSUE THREAD

**Issue by everrr1025** [HeyPuter/puter#331]
**Issue Description**
navigate to puter.com, desktop won't show up, open devtools, you will see the error in console

**Steps to Reproduce**
descripted as above

**Expected & Actual Behavior**

**Addition Information or Screenshots (if applicable)**
![image](https://github.com/HeyPuter/puter/assets/4454065/3742a375-1881-4061-8745-95cc930ded00)
![image](https://github.com/HeyPuter/puter/assets/4454065/614d4b7d-9aa6-490d-bb87-6bf3ace4f28b)

**Deployment**
- [x] Production (puter.com)
- [ ] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [ ] Docker (via `docker-compose`)

**Puter version (if accessible)**
2.2.0
> Click the profile button on the top-right, then "Settings". The version number will be printed at the bottom

**Comment by KernelDeimos** [comment]
I think the error with the desktop not loading is unrelated to the error message in the console, since I see the same error but the desktop is loading for me.

If you ping `puter.com` what IP address do you get?

**Comment by everrr1025** [comment]
@KernelDeimos, u right, the desktop is loading right now. i visit puter.com from china via a proxy, looks like the connection is not that stable sometimes.

PING puter.com (16.162.251.160): 56 data bytes
