### ISSUE TITLE
Publish phoenix shell to npm?

### ISSUE THREAD

**Issue by Freed-Wu** [HeyPuter/puter#340]
I notice phoenix has released many version (latest is 0.2.4) Can it be published to npm to let user `npm install` to install it? It can make installation eaiser and stop any others seize this name on npm.

TIA!

**Comment by KernelDeimos** [comment]
Hello again, we're going to go with a slow and gradual approach for this since each package we publish needs a different degree of maintenance. For example [kv.js](https://github.com/HeyPuter/kv.js) is already in its own package.
