### ISSUE TITLE
failed to create new account

### ISSUE THREAD

**Issue by scropion86** [HeyPuter/puter#353]
**Issue Description**

**Steps to Reproduce**

**Expected & Actual Behavior**

**Addition Information or Screenshots (if applicable)**

**Deployment**
- [ ] Production (puter.com)

**Puter version (if accessible)**
> Click the profile button on the top-right, then "Settings". The version number will be printed at the bottom

failed to create new account and error shows `{"message":"Response timed out.","code":"response_timeout"}`

![image](https://github.com/HeyPuter/puter/assets/5569470/985775d3-e575-42db-a5f4-714996002764)

**Comment by jelveh** [comment]
This issue should be resolved now. Could you confirm?

**Comment by flxhaas** [comment]
Same problem here
