### ISSUE TITLE
File Explorer table view is far too wide

### ISSUE THREAD

**Issue by Bashamega** [HeyPuter/puter#355]
**Issue Description**
In file explorer there is a huge white space with no use
**Steps to Reproduce**
1. Open File Explorer
2. Select a theme other than the huge icons
**Expected & Actual Behavior**
There should not be a huge scroll bar
**Addition Information or Screenshots (if applicable)**

**Deployment**
- [x ] Production (puter.com)
- [ ] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [ ] Docker (via `docker-compose`)

**Puter version (if accessible)**
2.1.0
> Click the profile button on the top-right, then "Settings". The version number will be printed at the bottom

**Comment by AtkinsSJ** [comment]
Hi, I'm not sure what the issue is. It looks like the items are showing up, you just need to scroll left to see their names. Could you clarify?

**Comment by Bashamega** [comment]
https://github.com/HeyPuter/puter/assets/110662505/5ac05e31-6dda-4411-9ec2-f1e4cd90f182

It is just a blank space. This is the bug. Even there is not visible details

**Comment by Bashamega** [comment]
@AtkinsSJ

**Comment by AtkinsSJ** [comment]
Oh I see. The width of the table is set to `100vw`, which makes it the browser window's width. I don't know what the right solution here is.

**Comment by Bashamega** [comment]
> Oh I see. The width of the table is set to `100vw`, which makes it the browser window's width. I don't know what the right solution here is.

Can i fix it?

**Comment by AtkinsSJ** [comment]
> Can i fix it?

Sure, please do!

**Comment by Bashamega** [comment]
> > Can i fix it?
> 
> Sure, please do!

Please assign, because i will probably forget

**Comment by Bashamega** [comment]
I don't know what happened, but the website is not opening locally or remotely(from the web) for me.
![image](https://github.com/HeyPuter/puter/assets/110662505/ffe3e3ed-7961-4f6c-8c57-b0dc6ae32435)

**Comment by bill-c-law** [comment]
This is an interesting issue for me to work on, if it is still available.

**Comment by jelveh** [comment]
Yep, this is still available. Go for it. Let me know if you need any help.
