### ISSUE TITLE
Setup dialog

### ISSUE THREAD

**Issue by Bashamega** [HeyPuter/puter#361]
Hello:)
My idea is that if the user is new to the site to prompt it with a setup wizard. similar to the setup wizard of Ubuntu. For example the user will accept the policy and choose a username and password and maybe how much storage she/he needs.

**Comment by Zac0511** [comment]
This is a cool idea ! I posted an idea about this too (#196), so i'm putting a 👍 to this !

**Comment by jelveh** [comment]
Thank you for this issue, we're going to implement a setup wizard.

This has been requested multiple times and I'm going to close it in favor of #588 since it's more detailed.
