### ISSUE TITLE
Browser mouse middle-button issue

### ISSUE THREAD

**Issue by TryVoidMain** [HeyPuter/puter#366]
Steps to reproduce:
1. Open browser
2. Open tab in browser
3. Click mouse middle-button on tab

Expected behaviour:
Opened tab in putter browser is closed

Actual behaviour:
A new tab is opened in your local browser

Putter version: 2.1.0
Server: frankfurt
Deployed: 30.04.2024

**Comment by AtkinsSJ** [comment]
Hi there! The Browser isn't made by Puter, I think @o0101 might be able to help you though.

**Comment by o0101** [comment]
Hey @TryVoidMain that's interesting! :) Thanks for that report, I can reproduce. [I've copied your issue across to our repository]() ([BrowserBox](https://github.com/BrowserBox/BrowserBox)). Please come and say hi there if you'd like to participate further on this. 

It's not a major for us, but we expect to fit it in an upcoming release. This is the first time we've seen this bug reported, a very interesting one, thank you! :)

Really appreciate your report, and @AtkinsSJ thanks for the tag! :)

**Comment by o0101** [comment]
Hey @TryVoidMain that's interesting! :) Thanks for that report, I can reproduce. [I've copied your issue across to our repository](https://github.com/BrowserBox/BrowserBox/issues/848) ([BrowserBox](https://github.com/BrowserBox/BrowserBox)). Please come and say hi there if you'd like to participate further on this. 

It's not a major for us, but we expect to fit it in an upcoming release. This is the first time we've seen this bug reported, a very interesting one, thank you! :)

Really appreciate your report, and @AtkinsSJ thanks for the tag! :)
