### ISSUE TITLE
Admin Console and "root" User

### ISSUE THREAD

**Issue by secondtruth** [HeyPuter/puter#368]
Introduce a "root" user and an Admin Console in Puter to centralize control and streamline administration processes, accessible exclusively to the "root" user (and other administrative users).

## Details

The proposal entails creating a "root" user with a stronger default password during the initial setup of the system, distinct from the normal default user. This user would possess exclusive access rights to an Admin Console enabling comprehensive management and monitoring of the system.

In addition to this, a role-based access control system could be implemented to delegate limited administrative functions within the Admin Console to other trusted users.

The console would feature several critical sections:

- **Dashboard**: Displays real-time statistics such as overall system health, the number of registered and currently logged in users, and an overview of host resource utilization (CPU load, memory usage, disk space, network activity).
- **User Management**: Offers a detailed list of all users, showing their online status, data quota usage, and provides administrative actions like modify, delete, or suspend user accounts.
- **App Management**: Enables adding, editing, and removing of system-wide apps.
- ...

## Potential Future Enhancements

- Develop a Host Terminal app to access a host system (or container) shell directly from Puter.
- Create a plugin system to extend the Admin Console's functionalities with additional management features and complete custom modules.

**Comment by Zac0511** [comment]
This is a cool idea, like if Puter is used in big places, managers can see the server's status and everything, or log off users if they are not working but **playing games** 😅

**Comment by jelveh** [comment]
Thanks for this @secondtruth. I'm going to close this so that we can track the progress in #580.
