### ISSUE TITLE
Prevent guests from creating apps or websites

### ISSUE THREAD

**Issue by AtkinsSJ** [HeyPuter/puter#376]
On the one hand, these are cool features of Puter and it's good for guests to see that they are an option. But, having anonymous users able to host arbitrary files seems like a really bad idea to me. At least if someone is registered, that gives us a way to know who they are, and provides a bit of friction to them creating a new account if they get banned.

**Comment by jelveh** [comment]
Abuse/spam prevention is an ongoing issue. I'm against making life difficult for everybody before we try to control the minority of abusers. To that end, we're still not going to enforce account creation... yet :P
