### ISSUE TITLE
Basic testing of Puter in CI

### ISSUE THREAD

**Issue by AtkinsSJ** [HeyPuter/puter#377]
It would be helpful to have automated testing that Puter can build and run correctly. This can help prevent issues appearing in setups that the dev team don't use. (eg, Windows and Docker.)

The general process would be something like:

1. Get a copy of the repo
2. `npm ci`, and check for errors
3. `npm start`, and check for errors
4. Access the hosted Puter website
	- This could start out as a simple `curl` call to check the response code, but ideally we'd run some basic tests using something like `selenium-webdriver` to interact with the page.
5. End the puter process

Ideally there would also be a variation of this that creates a Docker container from the repo and runs that - we get some issues when running in Docker that don't occur otherwise.

At a basic level, this would ensure that Puter at least can be installed and run, on whichever OSes we configure the CI task for. If we want to get fancy though, we could test that individual parts of the UI, like signing up, logging in, and creating files all work as expected, and across different web browsers.

**Comment by jelveh** [comment]
I'm going to close this as it's going to be an ongoing effort. Also, you've added a few nice CI actions which set things into motion ✌️
