### ISSUE TITLE
Why does my local deployment communicate with https://puter.com

### ISSUE THREAD

**Issue by s-geissler** [HeyPuter/puter#38]
Hi everyone,

What is the reason my local reployment wants to establish a websocket with puter.com?

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://puter.com/socket.io/?auth_token=XYZ. (Reason: CORS request did not succeed). Status code: (null).

Firefox can’t establish a connection to the server at wss://puter.com/socket.io/?auth_token=XYZ&transport=websocket&sid=xgBTosy78HgA20tOAK-2. bundle.min.js:126:17426

```

Is there a way to host the service fully locally, i.e. on a machine without access to the Internet?

**Comment by AtkinsSJ** [comment]
Hi there! Thanks for trying it out. :^)

We don't yet have a self-hosting back-end available, so all deployments have to make use of puter.com for that. This repository is just the front-end. But, self-hosting is a very popular request and we want to get that working as soon as possible. You can find a bit of a discussion about that [here](https://github.com/HeyPuter/puter/discussions/18).

So yes, it's coming! But it's not as straightforward as it sounds, so it will take a little while to get there.

**Comment by jelveh** [comment]
@fchamieh We're actively working to open-source it, it'll be out in less than 3 weeks. @KernelDeimos is working on this day and night right now.

**Comment by mostcute** [comment]
happy to wait for the great work

**Comment by jelveh** [comment]
Thank you, stay tuned :)
