### ISSUE TITLE
Puter account pictures

### ISSUE THREAD

**Issue by ghost** [HeyPuter/puter#382]
I use puter's official domain (puter.com) and I thought the user icon (![The puter user icon on the top right](https://github.com/HeyPuter/puter/assets/116188960/0b470184-7eae-46e5-9180-5bed02da997f)) could be set as a personal user picture, and instead of making a new directory, it should grab the picture from a url or one of the user's files to save space.

**Comment by AtkinsSJ** [comment]
Makes sense. We could then also show those here, which I think is `UIWindowSessionList`
![image](https://github.com/HeyPuter/puter/assets/222642/fb5f59c6-e14b-4366-8362-148d1c8b47b8)

**Comment by lucasgames8957** [comment]
moving into #support at https://discord.com/channels/1071986474041495705/1241005032904851630

**Comment by jelveh** [comment]
Coming soon 😎

**Comment by jelveh** [comment]
Finally donzo!
