### ISSUE TITLE
Git & Github support in vscode

### ISSUE THREAD

**Issue by phonemyatt** [HeyPuter/puter#39]
Hey guys, do you have road map to support git and github support in code? It will be really great feature for everybody using puter for development. 

Btw, I really love the work you guys done.

**Comment by KernelDeimos** [comment]
Hello, thanks for the kind works! The vscode running on Puter is a fork with our platform integration, which I believe we're going to release under an open-source license soon. I'll leave this issue open so we can transfer it there when this happens.

**Comment by jelveh** [comment]
Git has been merged.
