### ISSUE TITLE
Outdated gihub links displayed in the Terminal welcome message

### ISSUE THREAD

**Issue by ohm69** [HeyPuter/puter#393]
**Issue Description**
When Terminal starts, it shows a message 
```
This shell and Puter's Terminal Emulator are free software:
- phoenix: https://github.com/HeyPuter/phoenix
- terminal: https://github.com/HeyPuter/terminal
```

The urls are outdated as both repositories has been migrated to monotepo.

**Steps to Reproduce**
Start Terminal and look

**Expected & Actual Behavior**
It should be:
```
https://github.com/HeyPuter/puter/tree/main/packages/phoenix
and
https://github.com/HeyPuter/puter/tree/main/packages/terminal
``` 
respectively.

**Addition Information or Screenshots (if applicable)**
Problem seems to be in packages/phoenix/src/puter-shell/main.js , lines 48-49

**Deployment**
- [x] Production (puter.com)
- [ ] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [ ] Docker (via `docker-compose`)

**Puter version (if accessible)**
2.1.0

**Comment by AtkinsSJ** [comment]
Thanks! I can't believe I didn't notice this before. :laughing:

**Comment by parmarKaran01** [comment]
Hey, can i work on this?!

**Comment by Jai0401** [comment]
@parmarKaran01 are you still working on this issue?

**Comment by parmarKaran01** [comment]
@Jai0401 Yes Sir!
