### ISSUE TITLE
A pop-up prompt keeps popping up to save

### ISSUE THREAD

**Issue by good-ideal** [HeyPuter/puter#394]
**Issue Description**

After creating a text file and renaming it, the file cannot be saved when opened. A pop-up prompt keeps popping up to save, but after saving, it still prompts whether to save or not

**Steps to Reproduce**

Create new file ->rename ->double-click to open file ->enter content ->close file ->click save button

**Expected & Actual Behavior**

**Addition Information or Screenshots (if applicable)**

![image](https://github.com/HeyPuter/puter/assets/41094378/500c41f0-e79a-40ca-95ac-fa978b500566)

**Deployment**
- [x] Production (puter.com)
- [ ] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [ ] Docker (via `docker-compose`)

**Puter version (if accessible)**
> Click the profile button on the top-right, then "Settings". The version number will be printed at the bottom

Version: 2.1.0 • Server: hong-kong • Deployed: 2024/5/12 04:29:21
Google Chrome Version 124.0.6367.156 (official version) (64 bit)

**Comment by Xiayucheng1212** [comment]
@good-ideal  Hi, I tried to reproduce it, but there was no pop-up prompt shown up. Could you please demonstrate how this happened?

**Comment by good-ideal** [comment]
> @good-ideal Hi, I tried to reproduce it, but there was no pop-up prompt shown up. Could you please demonstrate how this happened?

@Xiayucheng1212 

https://github.com/HeyPuter/puter/assets/41094378/bbc9fe39-0891-4805-a383-e8d46f8b573f

**Comment by Xiayucheng1212** [comment]
I see, thank you. Maybe it's better to revise your description from "save -> close file" to "close file -> click save button".

**Comment by good-ideal** [comment]
> I see, thank you. Maybe it's better to revise your description from "save -> close file" to "close file -> click save button".

ok.
