### ISSUE TITLE
Show app descriptions in oembed

### ISSUE THREAD

**Issue by AtkinsSJ** [HeyPuter/puter#398]
When linking to a Puter app in a place that supports oembed, currently we show a description of Puter itself:

![Screenshot_20240514-214651-444.png](https://github.com/HeyPuter/puter/assets/222642/79ee82fc-d13c-4538-9ddb-dc67c9cecbcf)

That's valuable when linking to puter.com, but when linking to a specific app, it would be nice to show a description and picture of that specific app instead. Perhaps it would still mention running that app on Puter, but I don't know what the text limit is for these.

**Comment by Zac0511** [comment]
Yeah this would be cool, i thinked about this too, since i see this in every #share-your-app post.
