### ISSUE TITLE
Implement Keyboard Shortcuts for Permanent File Deletion

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#4]
When a user selects a file(s) and presses the appropriate keyboard shortcut, the system should prompt the user to confirm the permanent deletion of the selected file(s). Upon confirmation, the file(s) would be permanently deleted from the user's filesystem, bypassing the trash.

**Comment by srpcoder** [comment]
What are the places to add this feature?

**Comment by vineeth-vk11** [comment]
@jelveh I have opened a PR for this - #46

**Comment by jelveh** [comment]
@vineeth-vk11 all set, thank you! closing this issue
