### ISSUE TITLE
Can't download file

### ISSUE THREAD

**Issue by Zac0511** [HeyPuter/puter#409]
**Issue Description**
When i try to download a file, i get a JSON file instead. By downloading `image.png`, i get `image.png.json`

**Steps to Reproduce**
Download any file from Puter

**Expected & Actual Behavior**
Get the actual file on my computer

**Addition Information or Screenshots (if applicable)**
The JSON file that i get contains the following :
`{"message":"incorrect anti-CSRF token"}`

**Deployment**
- [x] Production (puter.com)
- [ ] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [ ] Docker (via `docker-compose`)

**Puter version**
2.1.0 (Deployed: 17/05/2024 01:16:23)

**Comment by jelveh** [comment]
@Zac0511 are you still having this issue? I can't reproduce it.

**Comment by Zac0511** [comment]
> @Zac0511 are you still having this issue? I can't reproduce it.

Yes, i still can't download any file.

**Comment by Zac0511** [comment]
Its working now, it got fixed

**Comment by AtkinsSJ** [comment]
I think this is back, at least in the repo version.
- Right click on a directory and choose "Download" -> works fine.
- Right click on a file and choose "Download" -> file contents are just `{"message":"incorrect anti-CSRF token"}`

**Comment by jelveh** [comment]
Fixed for good! currently available in self-hosted. Will be pushed to puter.com later on.
