### ISSUE TITLE
Translate more system apps

### ISSUE THREAD

**Issue by Zac0511** [HeyPuter/puter#411]
At the moment, only Puter's **main UI** is translated, but the system apps (except `settings` and `task manager`) are not translated, like the file explorer, app center, dev center, notepad, etc...
They should be translatable too, and could be added to the [translation files](/HeyPuter/puter/tree/main/src/i18n/translations).

**Comment by AtkinsSJ** [comment]
File Explorer can use the same system we already use for translation.

The others though, are iframe apps, and that means they can't access the usual `i18n()` function. Maybe we could add an SDK function for it though.

**Comment by jelveh** [comment]
This is important but I'm going to close the issue since translation is an ongoing effort and not a one-off issue.
