### ISSUE TITLE
Way to use proxy or vpn / fingerprints on websites

### ISSUE THREAD

**Issue by BenutzerEinsZweiDrei** [HeyPuter/puter#414]
Having a way to hide your OS is awesome when you are banned on a website/app.

But sadly puter and cloudtabs and its IP are banned basically everywhere...

Would be awesome if during development you watch out for this usecase 

That needs way to use proxy/vpn and private browsing and new fingerprint for OS and browser every restart.

**Comment by jelveh** [comment]
Hey, sorry this slipped through the cracks. We're going to be way more responsive from now on.

This is an interesting idea but it's out of scope for the Puter project. Could be a pretty cool app built on top of Puter.
