### ISSUE TITLE
Can't create shortcut

### ISSUE THREAD

**Issue by Zac0511** [HeyPuter/puter#415]
**Issue Description**
When i try to create a shortcut from the file manager, it doesn't work.

**Steps to Reproduce**
Right-click on any folder in the file manager, then click on `Create shortcut`

**Expected & Actual Behavior**
Create a shortcut in the same folder as the shortcut's target

**Addition Information or Screenshots (if applicable)**
I also have tried refreshing the file explorer, but the shortcut was still not appearing

**Deployment**
- [X] Production (puter.com)
- [ ] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [ ] Docker (via `docker-compose`)

**Puter version**
Version: 2.1.0 • Server: london • Deployed: 18/05/2024 05:13:45

**Comment by AtkinsSJ** [comment]
Can confirm, this doesn't work either on puter.com or on the latest self-host version.

When trying this locally, on a directory on my desktop named `Stuff`, the request to `/batch` fails:

Request:
```
------WebKitFormBoundaryndWXdG11sY4HSZKt
Content-Disposition: form-data; name="operation_id"

c827c120-bb92-4d98-8466-1d5cc6bd4a65
------WebKitFormBoundaryndWXdG11sY4HSZKt
Content-Disposition: form-data; name="socket_id"

cAkGXchDsTZ6QKAlAAAE
------WebKitFormBoundaryndWXdG11sY4HSZKt
Content-Disposition: form-data; name="original_client_socket_id"

cAkGXchDsTZ6QKAlAAAE
------WebKitFormBoundaryndWXdG11sY4HSZKt
Content-Disposition: form-data; name="operation"

{"op":"shortcut","dedupe_name":true,"overwrite":false,"operation_id":"c827c120-bb92-4d98-8466-1d5cc6bd4a65","path":"/Sam/Desktop","name":"Stuff - Shortcut","item_upload_id":0,"shortcut_to":"/Sam/Desktop/Stuff","shortcut_to_uid":"/Sam/Desktop/Stuff"}
------WebKitFormBoundaryndWXdG11sY4HSZKt--
```

Response:
```
{"results":[null,{"$":"heyputer:api/APIError","status":"batch_missing_file"}]}
```

**Comment by Zac0511** [comment]
So i'm not the only one to have the bug. Maybe some bugs are server specific (london, ect...), and some others are not.

**Comment by jelveh** [comment]
@Zac0511 yep, I can confirm it's a bug. Looking into it.
