### ISSUE TITLE
Access to all server files from puter web panel?

### ISSUE THREAD

**Issue by omidmousavi** [HeyPuter/puter#416]

**Comment by AtkinsSJ** [comment]
Hi, can you clarify this? There are a few different ways I could interpret what you're asking for.

**Comment by omidmousavi** [comment]
Hi, i want to access to all files on the server through puter panel...
For example, i like to delete `file1.txt` in my linux desktop or change Apache configurations in (/etc/...)
Is it possible to do it?

**Comment by AtkinsSJ** [comment]
Currently, no.

Puter has its own filesystem, using a database. The only files it can show you are the ones in that database.

We have plans to let it also see parts of the "real" filesystem, but I don't know the exact details of that. Exposing your entire computer, editable, on a website, sounds like a bit of a security nightmare. :sweat_smile:

**Comment by omidmousavi** [comment]
Okay👌👍
Thanks for your reply...
Yes, it's sounds like a bit of a security nightmare😁
I just wanted to work with my VPS which has no graphics connection
