### ISSUE TITLE
Feature Request: code app and folders 

### ISSUE THREAD

**Issue by triptych** [HeyPuter/puter#429]
I work with folders a lot in puter, and I use the code editor a lot.
If you are in `code` you can open a new folder and get working. 
But.
You cannot right click on a folder, choose open with, and see "code" as an option. Can you add this?
You cannot drag and drop a folder onto `code` and have it open the folder in code for editing. Can you add this?

**Comment by AtkinsSJ** [comment]
> You cannot right click on a folder, choose open with, and see "code" as an option. Can you add this?

This is an interesting one. On Windows for example, any app can add context menu items like this. But Puter doesn't have the concept of an app being installed. If any app could do this, you could quickly end up with hundreds of these options in "open with" which you've never heard of. 🤔

For now, it could be added to the hard-coded list though.

> You cannot drag and drop a folder onto `code` and have it open the folder in code for editing. Can you add this?

That sounds reasonable to me!

**Comment by jelveh** [comment]
Do I have news for both of you. Refresh your session, right-click on a directory, and select `Open With...`
