### ISSUE TITLE
Add `ctrl-click` as equivalent to `right-click`

### ISSUE THREAD

**Issue by triptych** [HeyPuter/puter#430]
I can open context menus in puter by 'right clicking' - however on macs there's no 'right click' you usually choose `ctrl-click` but in puter that does nothing.

For example ctrl-click on a folder. It should open the context menu. Now right click on the folder, boom there's the menu.

So please add `ctrl-click` functionality to puter.

**Comment by jelveh** [comment]
This should work as expected. Are you using Windows?

**Comment by triptych** [comment]
I've tried this on both windows and mac, and it does not work.

**Comment by jelveh** [comment]
Just fixed this! The fix is not available on Puter.com yet though. Right now we're focused on building features and will push them to prod afterward.
