### ISSUE TITLE
add a puter.fs.download to compliment puter.fs.upload

### ISSUE THREAD

**Issue by triptych** [HeyPuter/puter#436]
as a user I would like to have the ability to download / backup files and folders I have in puter.
I would like to be able to specify a list of files or a folder and have puter zip it up and download it to my local machine.

**Comment by jelveh** [comment]
I thought about this a lot. I don't think this should be part of the SDK as the use case is specific. Maybe I could build a quick module for this or separate out the zip code in the GUI. I'll look into it a bit later.
