### ISSUE TITLE
Is there any API documentation for the backend?

### ISSUE THREAD

**Issue by victor-erss** [HeyPuter/puter#44]
I would like to build my API server for this front end. It would be helpful if you make the backend open-source as well. I just need the API requests payload's JSON format and the response JSON structure. By the way awesome project man hats off

**Comment by murtaza030** [comment]
please can you explain more

**Comment by victor-erss** [comment]
For example what should i send as json payload for signup or login and what will be the response.

**Comment by victor-erss** [comment]
even if the backend API code is available as opensource it would be helpful

**Comment by victor-erss** [comment]
https://github.com/HeyPuter/puter/issues/38#issuecomment-1983248701

**Comment by victor-erss** [comment]
https://github.com/HeyPuter/puter/discussions/18

**Comment by victor-erss** [comment]
i'm asking for a self hosted feature.

**Comment by jelveh** [comment]
This is definitely on the roadmap, we should have an initial spec doc soon. also, the backend design has a driver concept which makes it much easier to provide your own apis and not write it from scratch. I'm gonna keep this open for more updates coming soon.

**Comment by victor-erss** [comment]
if you need any contribution please let me know

**Comment by jelveh** [comment]
Thank you. We're gonna open a branch for it in the next couple of weeks to develop it in the open. Make sure to check in regularly for the progress 🔥
