### ISSUE TITLE
Help! I can't deploy to Cyclic

### ISSUE THREAD

**Issue by TrapjawwS** [HeyPuter/puter#45]
Hi! I have been trying to deploy to Cyclic for about 3 hours now. (I use Cyclic because I'm broke and I can't afford paid site hosting) I'm a bit of a beginner so sorry if I've made any stupid mistakes. I started by building it with npm run build. I then created index.html outside of the /dist directory. For the index.html file I used the provided code in the production tutorial. I then tried to deploy it to Cyclic, but it gave me some error about the package.json file saying that nodemon is for development only, not production. I set the root path and the output path just to /. I have even tried changing them both, but it hasn't helped. I've been playing around with the package.json file for a while now trying to get it to work. Here is the current package.json file: 
`{
  "name": "puter.com",
  "version": "1.0.0",
  "author": "Puter Technologies Inc.",
  "license": "AGPL-3.0-only",
  "description": "Desktop environment in the browser!",
  "homepage": "https://puter.com",
  "directories": {
    "lib": "lib"
  },
  "devDependencies": {
    "chalk": "^4.1.0",
    "clean-css": "^5.3.2",
    "html-entities": "^2.3.3",
    "webpack": "^5.88.2",
    "express": "^4.18.2",
    "nodemon": "^2.0.22",
    "uglify-js": "^3.17.4",
    "webpack-cli": "^5.1.1"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node --exec \"node dev-server.js\" ",
    "build": "node ./build.js"
  },
  "nodemonConfig": {
    "ext": "js, json, mjs, jsx, svg, css",
    "ignore": [
      "./dist/",
      "./node_modules/"
    ]
  }
}`

Here is a screenshot of the current error: 
![image](https://github.com/HeyPuter/puter/assets/145371179/87d4b97e-4732-492b-b1a5-af3cd4ed769c)

I'm new to Github, sorry if I formated the code wrong

I was reading the Cyclic docs, and it says that the failed to run error comes from the package.json not being in the build folder, but if the build folder is /, and the package.json is in that directory, why can't it run?

Note: Changing it back to nodemon in the start script allows it to work in the terminal, but not Cyclic.

Help would be appreciated. Thanks!

**Comment by KernelDeimos** [comment]
It looks like Cyclic expects the server to run on port `3000`. I haven't used Cyclic before though so I'm making a few assumptions. Is there any place you can configure to use port `4000` instead? If not, try changing the port to `3000` manually in `dev-server.js` and let us know if that works.

**Comment by TrapjawwS** [comment]
Unfortunatly, there is now way to select the port in Cyclic. I changed it in dev-server.js, and it gave this error: 
![image](https://github.com/HeyPuter/puter/assets/145371179/018de882-828a-4f97-ba33-280520dd60e4)

**Comment by KernelDeimos** [comment]
`nodemon` restarts the server when source files are changed. Is this useful in a cyclic deployment? If not you can try replacing the `start` property in package.json with just `node dev-server.js`.

**Comment by TrapjawwS** [comment]
That didn't seem to fix it :( 
![image](https://github.com/HeyPuter/puter/assets/145371179/91844ada-06e7-47ba-aeaf-b6587177cb91)

Maybe it has to do with the root and output paths. Any idea what I should put for those?

**Comment by KernelDeimos** [comment]
The text `Exited with code: 1` leads me to believe it's running `node dev-server.js` but it immediately exits with an error. Is there any way to get the error logs from node?

**Comment by TrapjawwS** [comment]
I couldn't find any error logs, but when I clicked the error, this popped up, but I don't know if it's of any use
![Screenshot 2024-03-07 2 49 01 PM](https://github.com/HeyPuter/puter/assets/145371179/8e35839a-e7d6-443e-8390-c70f897a9560)

**Comment by KernelDeimos** [comment]
Added the "help wanted" label. I'm not familiar enough with Cyclic to help in a meaningful way, but I might have time to try it out later and see if I get the same error.

**Comment by TrapjawwS** [comment]
Ok, thank you.
