### ISSUE TITLE
AI doens't work in Editor app when Self Hosting Puter

### ISSUE THREAD

**Issue by pinjiang** [HeyPuter/puter#450]
**Issue Description**
AI doesn't work in Editor app when self hosting puter. A windows pops indicate 
“Error: No implementation available for interface `puter-chat-completion”

**Steps to Reproduce**
Deploy puter in self-hosting mode. 

**Expected & Actual Behavior**
AI works as puter.com

**Addition Information or Screenshots (if applicable)**
<img width="537" alt="Capture" src="https://github.com/HeyPuter/puter/assets/30993195/5c81e1c8-8255-495d-89a7-1ad29d35183e">

**Deployment**
- [ ] Production (puter.com)
- [ ] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [*] Docker (via `docker-compose`)

**Puter version (if accessible)**
> Click the profile button on the top-right, then "Settings". The version number will be printed at the bottom
version 2.1

**Comment by jelveh** [comment]
This is because you need to provide your own API keys for AI to work in self-hosted. We're going to document this process better. Ideally, I'd like to have a wizard allowing users of self-hosted to set their keys, but we're busy with more critical work right now.
