### ISSUE TITLE
Phoenix: FileCompleter.getCompletions() freezes if the input path doesn't exist

### ISSUE THREAD

**Issue by AtkinsSJ** [HeyPuter/puter#455]
**Issue Description**
Tab-completing a path that includes directories that do not exist, or are not directories, breaks Phoenix.

**Steps to Reproduce**
Assuming that the current directory has these entries:
- Things (directory)
- notes.txt (file)

Then pressing tab to complete the following will throw an error in `FileCompleter.getCompletions()` when it calls `readdir()`, and make Phoenix non-responsive:
- `cat fake/a<TAB>` - No directory named `fake`. Throws a "File or directory not found" error.
- `cat notes.txt/a` - notes.txt is not a directory. Throws an "Unknown error" error. (`readdir()` on a file returns an internal server error)

**Expected & Actual Behavior**
I'd expect FileCompleter to just not return any results. What it does is make Phoenix non-responsive. Basically, FileCompleter is naive and needs to expect and catch errors.

**Addition Information or Screenshots (if applicable)**

**Deployment**
- [x] Production (puter.com)
- [x] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [ ] Docker (via `docker-compose`)

**Puter version (if accessible)**
2.1.0 in production. 2.3.0 locally (on commit 41f378e40356458d5b447ba5ce481465f5238c24)

**Comment by tejhande** [comment]
We'll modify the getCompletions method to handle errors properly. Here's how you can do it:

Catch Exceptions: When calling readdir, we need to catch any errors that occur.
Return Empty Results on Error: If an error is caught, we should return an empty list of completions.
