### ISSUE TITLE
feature request: Link to the app-dev discord from the Dev Center app

### ISSUE THREAD

**Issue by triptych** [HeyPuter/puter#464]
As a puter app developer I would like to have a link to the app-dev puter channel in discord under the developer documentation link in the Dev Center app.

![image](https://github.com/HeyPuter/puter/assets/8691/4cbc8ce2-9085-4061-a6af-067cbbb54000)

**Comment by triptych** [comment]
https://discord.com/channels/1071986474041495705/1224431787808129138

**Comment by jelveh** [comment]
Great idea! Done. [https://puter.com/app/dev-center](https://puter.com/app/dev-center)
