### ISSUE TITLE
Add a button to download the entire Puter;js documentation

### ISSUE THREAD

**Issue by Zac0511** [HeyPuter/puter#470]
A download button should be added to the [Puter.js documentation](https://docs.puter.com/), allowing to download a page or the entire documentation as **PDF**, or **HTML**, for accessing the documentation offline, or feeding it to a local AI (probably what i'l do)

**Comment by jelveh** [comment]
This is available now: [https://docs.puter.com/prompt.md](https://docs.puter.com/prompt.md)
Alternatively, you can go to the [docs](https://docs.puter.com/) and scroll the sidebar all the way down and find the link.
