### ISSUE TITLE
Puter on subfolders

### ISSUE THREAD

**Issue by theMackabu** [HeyPuter/puter#48]
Currently, when you try to run puter on a subfolder, it redirects to the index after opening/closing applications. Puter works fine until you reload the page. I tried setting the `gui_origin` to my subfolder, but it seems to still redirect.

**Comment by jelveh** [comment]
Could you elaborate on "run puter on a subfolder"? I don't fully understand this.

**Comment by theMackabu** [comment]
> Could you elaborate on "run puter on a subfolder"? I don't fully understand this.

I currently have this directory tree with the provided nginx config, so the website can be accessed from domain.tld/desktop, but opening any app (Ex. File Manager) sets the path back to domain.tld
```
/static
└── desktop
    ├── dist
    ├── index.html
    └── puter
```

```conf
location / {
  root /static;
  try_files $uri $uri/ = @not_found;
}
```

**Comment by jelveh** [comment]
Sorry for the delay, at the moment it's strongly recommended to place Puter at the root of your domain/subdomain. I'm going to open a separate issue for this so we can allow for it later on.

**Comment by theMackabu** [comment]
Alright, sounds good!
