### ISSUE TITLE
Promise returned by `puter.ui.createWindow()` never resolves

### ISSUE THREAD

**Issue by AtkinsSJ** [HeyPuter/puter#483]
**Issue Description**
`puter.ui.createWindow()` returns a Promise that never resolves.

**Steps to Reproduce**
Run this and observe that the alert never happens.
```js
await puter.ui.createWindow({ content: 'I am a window' });
alert("Hello!");
```

**Expected & Actual Behavior**
I'm not sure when the Promise should resolve. But either we should resolve it (perhaps when the window is created) or we shouldn't return one.

**Addition Information or Screenshots (if applicable)**

**Deployment**
- [ ] Production (puter.com)
- [x] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [ ] Docker (via `docker-compose`)

**Puter version (if accessible)**
> Click the profile button on the top-right, then "Settings". The version number will be printed at the bottom

**Comment by jelveh** [comment]
Done. This should work now:

```js
let win = await puter.ui.createWindow({ content: 'I am a window' });
puter.ui.setWindowTitle('New Title', win);
puter.ui.setWindowHeight(100, win);
puter.ui.setWindowWidth(100, win);
...
```
