### ISSUE TITLE
Add Security Policy to the Repository

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#49]
We need a SECURITY.md file in the root of this repository, outlining:

- How and where to report security vulnerabilities.
- The process we will follow after a vulnerability report is received.
- Any responsible disclosure policies.

This will guide users and contributors to report security concerns responsibly.

**Comment by B0073D** [comment]
May be able to use this for some guidance https://docs.hackerone.com/en/articles/8494485-good-policies

**Comment by jelveh** [comment]
Thanks for this. Will publish one very soon.

**Comment by jelveh** [comment]
Any suggestions for bug bounty platforms? I'm setting it up rn
