### ISSUE TITLE
Disallow Uploading Files Directly to Trash

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#5]
Currently, users are able to upload files directly into the Trash folder. This behavior is counterintuitive, as the Trash is typically used for storing files intended to be deleted, not for receiving new uploads. Allowing uploads directly to Trash can lead to confusion and potential data loss, as users may not realize files have been uploaded to Trash and could permanently delete them.

The Trash folder should not accept any uploads directly from the user interface or via drag-and-drop actions. Attempting to upload files to the Trash should fail with a warning message alert indicating that uploads to Trash are not allowed.

**Comment by Arin13-03** [comment]
I am on it. Please assign it to me!!

**Comment by jelveh** [comment]
Let's go 🔥

**Comment by jelveh** [comment]
This has been resolved by @vineeth-vk11
