### ISSUE TITLE
can you add a browser app in the virtual desktop?

### ISSUE THREAD

**Issue by jiojiojackson** [HeyPuter/puter#50]
can you add a browser app in the virtual desktop?

**Comment by JonahZa** [comment]
I'm not sure if that's possible since there's no browser built in. As far as I can tell there isn't a way to open anything like that.

**Comment by jelveh** [comment]
Yes. Will take some time though. This an awesome app added by one of the devs check it out:  [browser](https://puter.com/app/puter-chrome)

**Comment by jiojiojackson** [comment]
> Yes. Will take some time though. This an awesome app added by one of the devs check it out: [browser](https://puter.com/app/puter-chrome)

Great! How can I use this browser app in my deployment? Thank you

**Comment by jelveh** [comment]
@jiojiojackson you should be able to use it without any modifications. The URL to access the app directly would change, e.g. http://localhost:4000/app/puter-chrome
