### ISSUE TITLE
Having problems when try close Start Menu on mobile devices

### ISSUE THREAD

**Issue by guicazaroto** [HeyPuter/puter#512]
### Description
When I try to close the navigation menu on my smartphone (Xiaomi Redmi 13 Pro), it doesn't work because the search input is overlapping the X button.

### How to reproduce
Open Puter using a mobile device.
In the taskbar, click on "Start".
Try to open the start modal.

### Snapshot
<img width="349" alt="Screenshot 2024-07-01 at 7 24 40 PM" src="https://github.com/HeyPuter/puter/assets/9921030/8dc8b0c0-8258-43a5-aafb-0d7e45dd4adb">

**Comment by guicazaroto** [comment]
I'm adding a small fix to solve this issue here: https://github.com/HeyPuter/puter/pull/513/files

As future improvement we could use relative units of measurement like (rem, em, %, vw, vh, ch, ex), instead of just use px. In this way we could make it work for different devices easily

**Comment by jelveh** [comment]
Oops! We fixed it at the same time!
