### ISSUE TITLE
Complete Arabic translation based on English file

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#529]
The Arabic translation file (`ar.js`) needs to be updated to include all translations present in the English file (`en.js`). Currently, the Arabic translation may be incomplete or outdated compared to the English version.

### Steps to resolve
1. Compare the contents of `src/gui/src/i18n/translations/en.js` and `src/gui/src/i18n/translations/ar.js`
2. For each translation key in `en.js`, ensure a corresponding translation exists in `ar.js`
3. If a translation is missing in `ar.js`, add it with an appropriate Arabic translation
4. If any translations in `ar.js` are outdated or incorrect, update them to match the current English version

### Additional notes
- Please ensure that the translations are culturally appropriate and maintain the intended meaning of the English text
- If certain terms or phrases don't have a direct Arabic equivalent, consider adding translator notes or using transliteration where appropriate

### Files to be updated
- `src/gui/src/i18n/translations/ar.js`

### Related files
- `src/gui/src/i18n/translations/en.js` (reference file)

Thank you for helping to improve the Arabic localization of our project!

**Comment by stronkexe** [comment]
working on it!

**Comment by jelveh** [comment]
Thank you very much! Assigning this to you 😇

**Comment by stronkexe** [comment]
https://github.com/HeyPuter/puter/pull/567

**Comment by Zain-Bin-Arshad** [comment]
@jelveh are you guys interested in Urdu translation? I can help with that if required!

**Comment by jelveh** [comment]
close #567
