### ISSUE TITLE
Complete Portuguese translation based on English file

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#531]
The Portuguese translation file (`pt.js`) needs to be updated to include all translations present in the English file (`en.js`). Currently, the Portuguese translation may be incomplete or outdated compared to the English version.

### Steps to resolve
1. Compare the contents of `src/gui/src/i18n/translations/en.js` and `src/gui/src/i18n/translations/pt.js`
2. For each translation key in `en.js`, ensure a corresponding translation exists in `pt.js`
3. If a translation is missing in `pt.js`, add it with an appropriate Portuguese translation
4. If any translations in `pt.js` are outdated or incorrect, update them to match the current English version

### Additional notes
- Please ensure that the translations are culturally appropriate and maintain the intended meaning of the English text
- If certain terms or phrases don't have a direct Portuguese equivalent, consider adding translator notes or using transliteration where appropriate

### Files to be updated
- `src/gui/src/i18n/translations/pt.js`

### Related files
- `src/gui/src/i18n/translations/en.js` (reference file)

Thank you for helping to improve the Portuguese localization of our project!

**Comment by matheussss1** [comment]
#566 done with chatgpt + my own revision

**Comment by felprangel** [comment]
Hi! I would like to work on this issue @jelveh

**Comment by felprangel** [comment]
Just a quick question: there's Portuguese from Portugal and Portuguese from Brazil, with slight differences between them. Which Portuguese is the translation going to be in? Or, if that's the case, will there be two different translations in two different files?

**Comment by jelveh** [comment]
This is for Portuguese from Portugal. 🙌

**Comment by felprangel** [comment]
So maybe I'm not the best person for this 😅 sorry for the inconvenience.

**Comment by jelveh** [comment]
No worries! thank you for trying to contribute. We do have Brazilian Portuguese as well. If you'd like to contribute you're more than welcome to review and improve that one 😇

**Comment by jelveh** [comment]
That one is in 'br.js'
