### ISSUE TITLE
Complete Spanish translation based on English file

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#532]
The Spanish translation file (`es.js`) needs to be updated to include all translations present in the English file (`en.js`). Currently, the Spanish translation may be incomplete or outdated compared to the English version.

### Steps to resolve
1. Compare the contents of `src/gui/src/i18n/translations/en.js` and `src/gui/src/i18n/translations/es.js`
2. For each translation key in `en.js`, ensure a corresponding translation exists in `es.js`
3. If a translation is missing in `es.js`, add it with an appropriate Spanish translation
4. If any translations in `es.js` are outdated or incorrect, update them to match the current English version

### Additional notes
- Please ensure that the translations are culturally appropriate and maintain the intended meaning of the English text
- If certain terms or phrases don't have a direct Spanish equivalent, consider adding translator notes or using transliteration where appropriate

### Files to be updated
- `src/gui/src/i18n/translations/es.js`

### Related files
- `src/gui/src/i18n/translations/en.js` (reference file)

Thank you for helping to improve the Spanish localization of our project!

**Comment by Koppeks** [comment]
Hi, I would like to do this issue @jelveh

**Comment by jelveh** [comment]
Thank you very much! Assigned 😇
Let me know if you need help with anything ✌️

**Comment by Koppeks** [comment]
Hi @jelveh I started with the issue. And I have a problem with the translation for plural_suffix: 's',
![image](https://github.com/user-attachments/assets/1ec3b078-a911-4fb4-bc74-654b931ed1a9)

In Spanish we have multiple plural suffix and this would be translated as plural_suffix: 'as' || "es" || "os", 
Because we use for feminine, masculine and neutral. In that order. There's no simple suffix for making words plural in Spanish.

This is clearly a edge case, but what should I do here?

**Comment by jelveh** [comment]
Thanks for bringing this up. This is indeed a problem with our i18n implementation right now; however, the good news is that the `plural_suffix` key is only used in one place and that's to pluralize the word `item`.  I used ChatGPT to determine the plural suffix for items and it seems to be `os` as in `artículos`, correct? in that case `plural_suffix` would be `os` for now.

(Obviously, this is not the ideal solution but we're going to revamp the pluralization in the near future to account for different languages)

**Comment by Koppeks** [comment]
Okay in that case I will leave it as `s` because accurate translation of  `item` is `elemento` and the plural translation is `elementos`.

Thanks for answering, I probably will finish today 🙌

**Comment by jelveh** [comment]
Perfect! Thank you.

**Comment by jelveh** [comment]
closed via #600 😇
