### ISSUE TITLE
Complete German translation based on English file

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#534]
The German translation file (`de.js`) needs to be updated to include all translations present in the English file (`en.js`). Currently, the German translation may be incomplete or outdated compared to the English version.

### Steps to resolve
1. Compare the contents of `src/i18n/translations/en.js` and `src/i18n/translations/de.js`
2. For each translation key in `en.js`, ensure a corresponding translation exists in `de.js`
3. If a translation is missing in `de.js`, add it with an appropriate German translation
4. If any translations in `de.js` are outdated or incorrect, update them to match the current English version

### Additional notes
- Please ensure that the translations are culturally appropriate and maintain the intended meaning of the English text
- If certain terms or phrases don't have a direct German equivalent, consider adding translator notes or using transliteration where appropriate

### Files to be updated
- `src/i18n/translations/de.js`

### Related files
- `src/i18n/translations/en.js` (reference file)

Thank you for helping to improve the German localization of our project!

**Comment by mklr19** [comment]
Philipp and Me will take it :) we are both german

**Comment by jelveh** [comment]
Thank you guys! Let me know if you need help with anything

**Comment by PhilippJindra** [comment]
Hello, My Name is Philipp, i come from Germany. My friend Marcel and Me will take the issue. 
Our professor have us the task to solve an issue.

**Comment by jelveh** [comment]
@PhilippJindra That's awesome! Thank you for helping us with translating Puter into German. I assigned this issue to both of you.

**Comment by PhilippJindra** [comment]
No problem and thank you :)

**Comment by mklr19** [comment]
@jelveh We changed and added some stuff according to the english refecrence. There are still minor grammatical errors, which we will correct while doing a Puter walkthrough with the german language. If we still have questions or can't find the corresponding words in Puter, we'll come back to you tomorrow

**Comment by jelveh** [comment]
Awesome! Thank you for your effort. Let me know if you need any help.

**Comment by PhilippJindra** [comment]
We have some questions:
line 168:         move: 'Move',   do you mean "the move" or "to move"?
line: 209:  plural_suffix: 's',   in german we have many plural_suffixes like "e", "en", "s", ...
line: 297: type_confirm_to_delete_account: "Type 'confirm' to delete your account.",:   to you need to write "confirm" or the german word "bestätigen"?

There are also a few words that are hardcoded. We didn't find any lines in the file.

**Comment by jelveh** [comment]
> line 168: move: 'Move', do you mean "the move" or "to move"?

This key seems to be redundant and not used anywhere any longer. You don't have to do anything though, I'll look into it and if confirmed will remove it from translation files

> line: 209: plural_suffix: 's', in german we have many plural_suffixes like "e", "en", "s", ...

This is a shortcoming we're aware of. At the moment no action is needed until we overhaul the pluralization feature.

> line: 297: type_confirm_to_delete_account: "Type 'confirm' to delete your account.",: to you need to write "confirm" or the german word "bestätigen"?

> line: 297: type_confirm_to_delete_account: "Type 'confirm' to delete your account.",: to you need to write "confirm" or the german word "bestätigen"?

You brought up a great point here. I think it should work with either (also due to backward compatibility). Let's keep the English 'confirm' for now. I'll patch this later today.

**Comment by jelveh** [comment]
Thanks again for your contribution. Just merged your PR! 😇
