### ISSUE TITLE
Complete Finnish translation based on English file

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#536]
The Finnish translation file (`fi.js`) needs to be updated to include all translations present in the English file (`en.js`). Currently, the Finnish translation may be incomplete or outdated compared to the English version.

### Steps to resolve
1. Compare the contents of `src/gui/src/i18n/translations/en.js` and `src/gui/src/i18n/translations/fi.js`
2. For each translation key in `en.js`, ensure a corresponding translation exists in `fi.js`
3. If a translation is missing in `fi.js`, add it with an appropriate Finnish translation
4. If any translations in `fi.js` are outdated or incorrect, update them to match the current English version

### Additional notes
- Please ensure that the translations are culturally appropriate and maintain the intended meaning of the English text
- If certain terms or phrases don't have a direct Finnish equivalent, consider adding translator notes or using transliteration where appropriate

### Files to be updated
- `src/gui/src/i18n/translations/fi.js`

### Related files
- `src/gui/src/i18n/translations/en.js` (reference file)

Thank you for helping to improve the Finnish localization of our project!

**Comment by waltodd** [comment]
Hi Jelveh I have almost all required skills except Fluency in Finnish But I can go deep grammatically and solve it
Required Skills:
- Fluency in both English and Finnish
- Programming experience, particularly with JavaScript
- Proficiency with Git and GitHub workflows
- Experience in submitting and managing Pull Requests
- Familiarity with software localization processes
- Attention to detail and consistency
