### ISSUE TITLE
Complete Igbo translation based on English file

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#539]
The Igbo translation file (`ig.js`) needs to be updated to include all translations present in the English file (`en.js`). Currently, the Igbo translation may be incomplete or outdated compared to the English version.

### Steps to resolve
1. Compare the contents of `src/gui/src/i18n/translations/en.js` and `src/gui/src/i18n/translations/ig.js`
2. For each translation key in `en.js`, ensure a corresponding translation exists in `ig.js`
3. If a translation is missing in `ig.js`, add it with an appropriate Igbo translation
4. If any translations in `ig.js` are outdated or incorrect, update them to match the current English version

### Additional notes
- Please ensure that the translations are culturally appropriate and maintain the intended meaning of the English text
- If certain terms or phrases don't have a direct Igbo equivalent, consider adding translator notes or using transliteration where appropriate

### Files to be updated
- `src/gui/src/i18n/translations/ig.js`

### Related files
- `src/gui/src/i18n/translations/en.js` (reference file)

Thank you for helping to improve the Igbo localization of our project!

**Comment by enweazudaniel** [comment]
Noted thanks

**Comment by jelveh** [comment]
@enweazudaniel thank you! Assigned 😇

**Comment by enweazudaniel** [comment]
Done

**Comment by enweazudaniel** [comment]
Kindly close this issue

**Comment by jelveh** [comment]
@enweazudaniel Thank you for translating Puter into Ingbo and completing it again today. Appreciate your help 😇
