### ISSUE TITLE
Complete Italian translation based on English file

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#540]
The Italian translation file (`it.js`) needs to be updated to include all translations present in the English file (`en.js`). Currently, the Italian translation may be incomplete or outdated compared to the English version.

### Steps to resolve
1. Compare the contents of `src/gui/src/i18n/translations/en.js` and `src/gui/src/i18n/translations/it.js`
2. For each translation key in `en.js`, ensure a corresponding translation exists in `it.js`
3. If a translation is missing in `it.js`, add it with an appropriate Italian translation
4. If any translations in `it.js` are outdated or incorrect, update them to match the current English version

### Additional notes
- Please ensure that the translations are culturally appropriate and maintain the intended meaning of the English text
- If certain terms or phrases don't have a direct Italian equivalent, consider adding translator notes or using transliteration where appropriate

### Files to be updated
- `src/gui/src/i18n/translations/it.js`

### Related files
- `src/gui/src/i18n/translations/en.js` (reference file)

Thank you for helping to improve the Italian localization of our project!

**Comment by micheledinelli** [comment]
Hi! I am working on it! 😄

**Comment by jelveh** [comment]
That's awesome. Thank you! Let us know if you have any questions.
