### ISSUE TITLE
Complete Russian translation based on English file

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#547]
The Russian translation file (`ru.js`) needs to be updated to include all translations present in the English file (`en.js`). Currently, the Russian translation may be incomplete or outdated compared to the English version.

### Steps to resolve
1. Compare the contents of `src/gui/src/i18n/translations/en.js` and `src/gui/src/i18n/translations/ru.js`
2. For each translation key in `en.js`, ensure a corresponding translation exists in `ru.js`
3. If a translation is missing in `ru.js`, add it with an appropriate Russian translation
4. If any translations in `ru.js` are outdated or incorrect, update them to match the current English version

### Additional notes
- Please ensure that the translations are culturally appropriate and maintain the intended meaning of the English text
- If certain terms or phrases don't have a direct Russian equivalent, consider adding translator notes or using transliteration where appropriate

### Files to be updated
- `src/gui/src/i18n/translations/ru.js`

### Related files
- `src/gui/src/i18n/translations/en.js` (reference file)

Thank you for helping to improve the Russian localization of our project!

**Comment by DEVchetan01** [comment]
Hii
I'm skilled in Russian translation and JavaScript programming, ready to update and ensure accuracy in your en.js and ru.js files on GitHub (#547). want to collaborate
Looking forward 

Gmail- chetanjangir42@gmail.com

**Comment by Speedyjet** [comment]
Hi there. I can help you with that as I'm a native Russian speaker

**Comment by Speedyjet** [comment]
Yep, why not. But I need a short call to get on the track worth the project. Is there anyone I could speak?

**Comment by Speedyjet** [comment]
> Hi @Speedyjet. Thank you! Should I assign this issue to you?

I fixed the Russian translation file and about to create the Ukrainian but I need permission. Now I created a fork

**Comment by jelveh** [comment]
closed via #547

**Comment by Speedyjet** [comment]
Guys, you could tell me earlier that someone's already on this ticket.

**Comment by jelveh** [comment]
@Speedyjet sorry about this. The PR came from a contributor that was not assigned to the issue directly and the CLA was in place allowing us to merge immediately. I will gladly merge your PR as well and pick the best of both changes, but first you need to look into the [CLA](https://github.com/HeyPuter/puter/pull/560#issuecomment-2214929345) before I can do anything.

**Comment by Speedyjet** [comment]
Okay, that's sad. Anyway, you can also pick my Ukrainian translation and modified translations.js file

-- реклама -----------------------------------------------------------
Поторопись зарегистрировать самый короткий почтовый адрес @i.ua
https://mail.i.ua/reg - и получи 1Gb для хранения писем

**Comment by jelveh** [comment]
I'd be more than happy to! 😇
