### ISSUE TITLE
Complete Chinese translation based on English file

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#549]
The Chinese translation file (`zh.js`) needs to be updated to include all translations present in the English file (`en.js`). Currently, the Chinese translation may be incomplete or outdated compared to the English version.

### Steps to resolve
1. Compare the contents of `src/gui/src/i18n/translations/en.js` and `src/gui/src/i18n/translations/zh.js`
2. For each translation key in `en.js`, ensure a corresponding translation exists in `zh.js`
3. If a translation is missing in `zh.js`, add it with an appropriate Chinese translation
4. If any translations in `zh.js` are outdated or incorrect, update them to match the current English version

### Additional notes
- Please ensure that the translations are culturally appropriate and maintain the intended meaning of the English text
- If certain terms or phrases don't have a direct Chinese equivalent, consider adding translator notes or using transliteration where appropriate

### Files to be updated
- `src/gui/src/i18n/translations/zh.js`

### Related files
- `src/gui/src/i18n/translations/en.js` (reference file)

Thank you for helping to improve the Chinese localization of our project!

**Comment by chinavampire** [comment]
Hi, I'm a Chinese webdesigner who's able to translate JS files. Could you please provide the access to your repository?

**Comment by jelveh** [comment]
Thank you very much for your interest in contributing to the Chinese translation. We appreciate your willingness to help improve Puter's localization.

However, you don't need direct access to the repository to make these changes. Instead, contributors need to submit their changes as a pull request (PR). Here's how you can proceed:

1. Fork the repository to your own GitHub account.
2. Make the necessary translation updates in the `src/gui/src/i18n/translations/zh.js` file.
3. Commit your changes to your forked repository.
4. When done, create a pull request from your fork to our main repository.

If you need any help on how to create a pull request or if you have any questions about the translation process, please let us know. We're here to help you contribute effectively.

Thank you again for your interest in improving our Chinese localization!

**Comment by chinavampire** [comment]
I have found 10 repositories. Kindly let me know in which one I can find the files you mentioned.

**Comment by chinavampire** [comment]
I apologize that I rarely use GitHub, as this platform has limited accessibility without VPN support.

**Comment by jelveh** [comment]
No worries! The project is: [https://github.com/heyputer/puter](https://github.com/heyputer/puter)

This is the main repository for the Puter project, and it's where you'll find the translation files mentioned in the original issue. To contribute:

1. Fork this repository (https://github.com/heyputer/puter) to your own GitHub account.
2. Locate the `src/gui/src/i18n/translations/zh.js` file in your forked repository.
3. Make the necessary translation updates.
4. Commit your changes to your fork.
5. Create a pull request from your fork to the main heyputer/puter repository.

**Comment by chinavampire** [comment]
It's done.
It looks like the translation lost consistency with the English version.
I left comments "From Yu..." for your review.

**Comment by chinavampire** [comment]
I haven't sent any proposal on upwork yet.
Please review my work, I'll reach out to you on upwork if you're satisfied.

**Comment by jelveh** [comment]
Completed via #559
