### ISSUE TITLE
Create Hindi translation based on English file

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#551]
We currently do not have a Hindi translation file for our project. We need to create a new Hindi translation file (`hi.js`) that includes all translations present in the English file (`en.js`).

### Steps to resolve
1. Create a new file `src/i18n/translations/hi.js`
2. Use the contents of `src/i18n/translations/en.js` as a reference
3. For each translation key in `en.js`, create a corresponding Hindi translation in `hi.js`
4. Ensure all translations are accurate and culturally appropriate

### Additional notes
- Please ensure that the translations maintain the intended meaning of the English text
- If certain terms or phrases don't have a direct Hindi equivalent, consider adding translator notes or using transliteration where appropriate
- Pay attention to any cultural nuances that may need to be adapted for Hindi-speaking users

### Files to be created
- `src/i18n/translations/hi.js`

### Related files
- `src/i18n/translations/en.js` (reference file)

Thank you for helping to create the Hindi localization for our project! This will greatly improve accessibility for Hindi-speaking users.

**Comment by akashlimbani** [comment]
I check you job post on upwork. Sorry but I have not connects at the moment for the bid. @jelveh 
Please give me access of repository. File is ready for the hindi translation.

**Comment by jelveh** [comment]
closed via #557
