### ISSUE TITLE
Create Vietnamese translation based on English file

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#553]
We currently do not have a Vietnamese translation file for our project. We need to create a new Vietnamese translation file (`vi.js`) that includes all translations present in the English file (`en.js`).

### Steps to resolve
1. Create a new file `src/gui/src/i18n/translations/vi.js`
2. Use the contents of `src/gui/src/i18n/translations/en.js` as a reference
3. For each translation key in `en.js`, create a corresponding Vietnamese translation in `vi.js`
4. Ensure all translations are accurate and culturally appropriate

### Additional notes
- Please ensure that the translations maintain the intended meaning of the English text
- If certain terms or phrases don't have a direct Vietnamese equivalent, consider adding translator notes or using transliteration where appropriate
- Pay attention to any cultural nuances that may need to be adapted for Vietnamese-speaking users

### Files to be created
- `src/gui/src/i18n/translations/vi.js`

### Related files
- `src/gui/src/i18n/translations/en.js` (reference file)

Thank you for helping to create the Vietnamese localization for our project! This will greatly improve accessibility for Vietnamese-speaking users.

**Comment by cpwallah** [comment]
hi i would like to work on this issue @jelveh

**Comment by jelveh** [comment]
Let me know if you need help with anything

**Comment by pvhuwung** [comment]
Hi I came from Upwork,may I know that could I work on this issue, if no one is working on this. Thanks

**Comment by jelveh** [comment]
closed via #620
