### ISSUE TITLE
Create Tamil translation based on English file

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#554]
We currently do not have a Tamil translation file for our project. We need to create a new Tamil translation file (`ta.js`) that includes all translations present in the English file (`en.js`).

### Steps to resolve
1. Create a new file `src/gui/src/i18n/translations/ta.js`
2. Use the contents of `src/gui/src/i18n/translations/en.js` as a reference
3. For each translation key in `en.js`, create a corresponding Tamil translation in `ta.js`
4. Ensure all translations are accurate and culturally appropriate

### Additional notes
- Please ensure that the translations maintain the intended meaning of the English text
- If certain terms or phrases don't have a direct Tamil equivalent, consider adding translator notes or using transliteration where appropriate
- Pay attention to any cultural nuances that may need to be adapted for Tamil-speaking users

### Files to be created
- `src/gui/src/i18n/translations/ta.js`

### Related files
- `src/gui/src/i18n/translations/en.js` (reference file)

Thank you for helping to create the Tamil localization for our project! This will greatly improve accessibility for Tamil-speaking users.

**Comment by Varun710** [comment]
Hi. I'd like to work on this issue. Could you please assign it to me?

**Comment by jelveh** [comment]
Yes and thank you :) 
Assigned. Let me know if you need any help.

**Comment by Varun710** [comment]
I just want to clarify. This is to translate the text to Tamil which is spoken in the southern part of India right?

**Comment by jelveh** [comment]
Yes, that's correct.

**Comment by Varun710** [comment]
Awesome. Thanks.

**Comment by Varun710** [comment]
Hey. I forked this repo and I worked on the issue. I have created a PR, from my forked repo. Is that correct? Do I need to do anything else? @jelveh

**Comment by jelveh** [comment]
closed via #593

Thanks again @Varun710

**Comment by jelveh** [comment]
> Hey. I forked this repo and I worked on the issue. I have created a PR, from my forked repo. Is that correct? Do I need to do anything else? @jelveh

Just merged your PR! All set, thank you :)
