### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#569]
### Discussed in https://github.com/HeyPuter/puter/discussions/568

<div type='discussions-op-text'>

<sup>Originally posted by **damaterapolixenidis** July  9, 2024</sup>
Hello,

I was trying to install and run with docker on macOS and I address this issue when docker pull finished and I go to login: 

https://prnt.sc/NvIfkEriLjLt</div>

**Comment by KernelDeimos** [comment]
@damaterapolixenidis I'm not able to reproduce this, but if you can provide some of this additional information that will narrow down the possible issues:

- What method did you use to install the Docker image? We have instructions for use with Docker directly as well as with Docker Compose. It is also possible to build from the Dockerfile in the repo.
- What was the URL in your address bar when you were at the login page?
- Did you add any additional configuration, or was this with default settings?

If you can provide screenshots of either of these, that could also help:
- Output of "Console" tab in browser's Developer Tools
- Output of Puter server console

**Comment by damaterapolixenidis** [comment]
Yes sure the screenshot is this: 

https://prnt.sc/fqd7tsjDfF5j
https://prnt.sc/dsa1iC2ZmTSx
https://prnt.sc/2W3TL9soPeHC

**Comment by jelveh** [comment]
I'm going to close this as we confirmed with @damaterapolixenidis on discord that is was resolved. (changing the browser from Safari to Firefox fixed the issue)

**Comment by damaterapolixenidis** [comment]
I confirm! 
And to run:

HTTP://puter.localhost:4100
