### ISSUE TITLE
Unable to run Puter properly in self hosted (WSL)

### ISSUE THREAD

**Issue by Zac0511** [HeyPuter/puter#577]
**Issue Description**
Puter successfully starts on my terminal, but when i open it, i'm stuck on the BSOL (Blue Screen of _infinite_ loading)

**Steps to Reproduce**
Starts Puter self hosted with WSL on Windows 11

**Expected & Actual Behavior**
Puter should work and show all the UI

**Addition Information or Screenshots (if applicable)**
WSL console output : [puter-wsl-ubuntu-console.log](https://github.com/user-attachments/files/16168916/puter-wsl-ubuntu-console.log)
Chrome console output : [puter.localhost-1720645270230.log](https://github.com/user-attachments/files/16168922/puter.localhost-1720645270230.log)

Chrome version : `Stable 126.0.6478.127 (Official build) (64 bits)`
NPM version : `node v22.4.1 (npm v10.8.1)`
OS : `Windows 11 23H2 - build 22631.3880`
WSL OS : `Ubuntu 22.04.4 LTS`
WSL Kernel : `5.15.153.1-microsoft-standard-WSL2`

What is shown in the browser : 

![image](https://github.com/HeyPuter/puter/assets/83874244/097d1f22-b667-4b97-9030-ce66a75a3b26)

The image is a little bright because of HDR

**Deployment**
- [ ] Production (puter.com)
- [X] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [ ] Docker (via `docker-compose`)

**Puter version**
_unknow, since terminal does not show version at start, but version downloaded and cloned was 2.4.0_

**Comment by Zac0511** [comment]
@KernelDeimos has fixed the problem with push https://github.com/HeyPuter/puter/commit/7aadae58ce1a51f925bf64c3d65ac1fa6971b164
I'm closing this issue

**Comment by KernelDeimos** [comment]
Thanks again for the detailed report!

**Comment by decipher2k** [comment]
Could be caused by a missing dns entry for api.<domain>
