### ISSUE TITLE
Self hosted saying 1.0.0

### ISSUE THREAD

**Issue by Zac0511** [HeyPuter/puter#582]
**Issue Description**
I'm on self hosted 2.4.0, but the settings and the console says 1.0.0

**Steps to Reproduce**
Start Puter self hosted

**Expected & Actual Behavior**
Show the actual version (2.4.0 in my case)

**Deployment**
- [ ] Production (puter.com)
- [X] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [ ] Docker (via `docker-compose`)

**Puter version**
Supposedly 2.4.0 (`git pull` runned 15 minutes before starting it)

**Comment by jelveh** [comment]
You're right this is a bug. We'll fix it in a few minutes.

**Comment by KernelDeimos** [comment]
So version `2.4.0` will be stuck with this issue forever because `release-please` messed it up. I've already noticed it has a tendency to mess things up so I've started working on a replacement.

I'll release version `2.4.1` today which will fix this.

**Comment by KernelDeimos** [comment]
We made [a patch release](https://github.com/HeyPuter/puter/releases/tag/v2.4.1) a little ahead of schedule to fix this, which works out nicely because the branch doesn't have any risky changes and also has a bunch of new translations.
