### ISSUE TITLE
Standalone HTML executables

### ISSUE THREAD

**Issue by Zac0511** [HeyPuter/puter#583]
I was thinking of a feature for both production and self hosted, that would allow to have some sort of standalone HTML executable files (like `.exe` files on Windows).

The way this could work is that the executable is actually just a ZIP with `index.html` and other files, that haves a different file extension, like `.wexe` (web exe) for example.

And when a user runs a standalone app, he could see a warning like this one : 

![image](https://github.com/HeyPuter/puter/assets/83874244/527c50b5-6920-464a-b423-6868d862a7aa)

To create an app, an user would just need to right click a folder, and select "Compress as standalone Puter executable"

So yeah essentially, creating this would just need to make Puter load the content of the ZIP with a different extension in the RAM, then open `index.html` in a Puter window, and then would delete the app from the RAM after closing the window.

**Comment by otlet** [comment]
Isn't that precisely what docker is?

**Comment by jelveh** [comment]
We thought about this a lot. I generally like the idea but it'll open the door to a lot of security issues. We have very strong sandboxing to apps but we also have the ability to completely remove a malicious app from the system using current structure of app publishing, if we allow HTML executables we won't be able to do that. Basically, in the HTML-executable world if a malicious app is spread through the system we can only play whack-a-mole with it.

So with a heavy heart, I need to close this 🥹

**Comment by Zac0511** [comment]
> We thought about this a lot. I generally like the idea but it'll open the door to a lot of security issues. We have very strong sandboxing to apps but we also have the ability to completely remove a malicious app from the system using current structure of app publishing, if we allow HTML executables we won't be able to do that. Basically, in the HTML-executable world if a malicious app is spread through the system we can only play whack-a-mole with it.
> 
> So with a heavy heart, I need to close this 🥹

Yeah, thats why i was thinking of that warning at opening, but if the whole virus thing is to hard, well, no `.wexe` files.
