### ISSUE TITLE
Mobile Port?

### ISSUE THREAD

**Issue by Ocean-OS** [HeyPuter/puter#59]
Using some basic CSS and a little bit of Javascript, could you make the interface adapt to mobile devices? This would just require some small tweaks to the code, but would improve the OS a lot.

**Comment by theEricDevelops** [comment]
It adapts to my device pretty well.

**Comment by Ocean-OS** [comment]
> It adapts to my device pretty well. 

Are you in landscape, or portrait mode?

**Comment by jelveh** [comment]
We could do better on mobile/tablets. It works but it's not optimized. I need to lay some foundation first before going all-in on smaller/touch devices.

**Comment by AtkinsSJ** [comment]
> One app that I noticed doesn't work on any device with an on-screen keyboard is the Terminal app. 

Yeah that's a known issue. https://github.com/HeyPuter/phoenix/issues/18 On-screen keyboard input is sent differently to regular keyboard input, and the library the terminal uses doesn't handle that properly. But that library is open source so it should be fixable when someone finds time.

**Comment by jelveh** [comment]
I'm closing this as this will be an ongoing project and not a one-off issue.
