### ISSUE TITLE
Access shows "Invalid Host header."

### ISSUE THREAD

**Issue by LaoJiuYes** [HeyPuter/puter#596]
**Issue Description**
I deployed with docker on a vps and the log status is 200 after completion, but when I access it remotely with a browser it says "Invalid Host header.". How can I solve this?
**Steps to Reproduce**

**Expected & Actual Behavior**

**Addition Information or Screenshots (if applicable)**

**Deployment**
- [ ] Production (puter.com)
- [ ] Development (`npm run start`)
- [  √] Docker (via `docker run`)
- [  √] Docker (via `docker-compose`)

**Puter version (if accessible)**
ubuntu 22.04
docker 27.0.3
docker-compose 2.28.1
> Click the profile button on the top-right, then "Settings". The version number will be printed at the bottom

**Comment by bryanthaboi** [comment]
type puter.localhost

**Comment by jelveh** [comment]
I suspect this a domain name configuration problem:

[https://github.com/HeyPuter/puter/blob/main/doc/self-hosters/domains.md](https://github.com/HeyPuter/puter/blob/main/doc/self-hosters/domains.md)

Could you follow the instructions above and let us know if it resolves your issue?

**Comment by jelveh** [comment]
I see. For Puter to work you will need a domain name since we use different subdomains for system endpoints such as 'api.domain.tld'. 

Is you instance only accessible via the static IP address? if yes, that should be the problem.

**Comment by jelveh** [comment]
I'm going to close this for now but let us know if you have any questions, we'd be happy to help.

**Comment by obviously-shadow** [comment]
Hello!
I recently tried hosting Puter on a VPS (more specifically, on Linode). I get the same issue, and I am very confused on what to do. I tried doing what you mentioned, @jelveh, but that did not do much help. In my case, the way I can access the website is by using the public IP, and by that, I can't add: "puter.[ip]:4100". Please advise what to do.
(I am new at this kind of stuff)
thanks

**Comment by jelveh** [comment]
Hi @obviously-shadow, at this moment for security reasons a domain (whether local or registrable) is required for self-hosting Puter. So IP address, whether public or private, won't work. Please note this is for your security please don't try to change this.

We're going to try to make this process as easy as possible soon but for now please refrain from setting up self-hosted Puter for production purposes.

**Comment by jelveh** [comment]
Hi @techcow2 , could you try setting the domain name in the config by following these instructions? [https://github.com/HeyPuter/puter/blob/main/doc/self-hosters/instructions.md#domain-name](https://github.com/HeyPuter/puter/blob/main/doc/self-hosters/instructions.md#domain-name)

As for the db error your reported, I'm looping in @KernelDeimos to help out.

**Comment by sugarwsi** [comment]
> Hi @jelveh I am also facing this issue. I have a domain name and I use nginx proxy manager. I config nginx as http > VPS IP > PORT. I have websocket support enabled > force ssl > HTTPS/2. I'm not sure what to do. I'm running docker compose per your instructions. sudo docker ps says container is healthy running on port 4100. Unable to access the page though due to 'Invalid Host header.' (error 400 in browser console). The docker logs keep saying bot detected?
> 
> version: "3.8" services: puter: container_name: puter image: ghcr.io/heyputer/puter:latest pull_policy: always # build: ./ restart: unless-stopped ports: - '4100:4100' environment: # TZ: Europe/Paris # CONFIG_PATH: /etc/puter PUID: 1000 PGID: 1000 volumes: - ./puter/config:/etc/puter - ./puter/data:/var/puter healthcheck: test: wget --no-verbose --tries=1 --spider http://puter.localhost:4100/test || exit 1 interval: 30s timeout: 3s retries: 3 start_period: 30s

Hi, do you have the answer? this case same as mine btw. appriciate if you have solve the problem and post it here thx

**Comment by KernelDeimos** [comment]
> @jelveh Update- There appears to be a database failing:
> 
> ```
> [ERRO::system-validation] (2.731s) Error @ INVALID SYSTEM STATE: failed to initialize services; CompositeError: failed to initialize these services: database
> --- Inner error: SqliteError: FOREIGN KEY constraint failed
> ```

Try a fresh clone on the current `main` and set the environment variable `NO_VAR_RUNTIME=1`. As to why you're getting this error message, I'm not sure yet.

**Comment by KernelDeimos** [comment]
@techcow2 @sugarwsi - if you can post `domain`, `protocol` and `http_port` from the configuration file for Puter itself that will also help to diagnose this issue.

**Comment by SadDarkAngel** [comment]
> Hi [@jelveh](https://github.com/jelveh) I am also facing this issue. I have a domain name and I use nginx proxy manager. I config nginx as http > VPS IP > PORT. I have websocket support enabled > force ssl > HTTPS/2. I'm not sure what to do. I'm running docker compose per your instructions. sudo docker ps says container is healthy running on port 4100. Unable to access the page though due to 'Invalid Host header.' (error 400 in browser console). The docker logs keep saying bot detected?
> 
> version: "3.8" services: puter: container_name: puter image: ghcr.io/heyputer/puter:latest pull_policy: always # build: ./ restart: unless-stopped ports: - '4100:4100' environment: # TZ: Europe/Paris # CONFIG_PATH: /etc/puter PUID: 1000 PGID: 1000 volumes: - ./puter/config:/etc/puter - ./puter/data:/var/puter healthcheck: test: wget --no-verbose --tries=1 --spider http://puter.localhost:4100/test || exit 1 interval: 30s timeout: 3s retries: 3 start_period: 30s

If u are using additional nginx as revers-proxy, try to add proxy_set_header Host $http_host; to ur nginx config. It’s helps me to resolve same "Invalid Host header." error.
