### ISSUE TITLE
Delay Progress Window Display for Quick Move/Copy Operations

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#6]
In the current implementation, whenever a user initiates a move or copy operation for files or folders, a progress window appears immediately. This behavior, while informative for lengthy operations, can be unnecessarily intrusive for operations that are completed within a short time frame (< 2 seconds). To enhance the user experience, the progress window's appearance should be delayed, showing up only if the operation exceeds 2 seconds.

Expected Behavior:

- The progress window for move/copy operations should not immediately pop up after the operation is initiated.
- If the operation is completed within 2 seconds, the progress window should not be displayed at all, to avoid disrupting the user's workflow.
- The progress window should only appear for operations that take longer than the specified threshold of 2 seconds.
- If and once the progress window is triggered for any move/copy operation, it should stay visible for **at least** 2 seconds, regardless of how quickly the operation actually completes.

**Comment by AkshatHotCode** [comment]
Will be happy to contribute on this, assign it on my name!

**Comment by vineeth-vk11** [comment]
@jelveh Currently, there is no progress bar with percentage for copy and move operations, there is just a pop-up showing which files are being copied, is this expected behaviour?

**Comment by jelveh** [comment]
> Will be happy to contribute on this, assign it on my name!

Let's go 🔥

**Comment by jelveh** [comment]
> @jelveh Currently, there is no progress bar with percentage for copy and move operations, there is just a pop-up showing which files are being copied, is this expected behaviour?

No, it's not. We need it. I'm going to open a separate issue for this. This needs to work in [puter.js](https://github.com/HeyPuter/puter.js) as well.
