### ISSUE TITLE
Is it possible run puter not in container, but in windows or in other OS?

### ISSUE THREAD

**Issue by toghrulgasimov** [HeyPuter/puter#601]
Hello, i want to know if it is possible run on windows which npm and node are installed?
Is there any way run it for example in freebsd or windows?

**Comment by toghrulgasimov** [comment]
When I run puter in windows without container and open url. I got black screen.

**Comment by jelveh** [comment]
Thanks for reporting this. We're looking into issues with running Puter from source on Windows. I'm hoping to have a fix out in the next 12-24 hours. ✌️

**Comment by jelveh** [comment]
The problem should be resolved now. You should be able to run Puter in Windows without containers by following [these instructions](https://github.com/heyputer/puter?tab=readme-ov-file#-local-development)
