### ISSUE TITLE
Verify Mastodon link

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#610]
By @secondtruth :
"You could add a <link rel="me" href="https://mastodon.social/@puter"> to puter.com so that the Puter link on the Mastodon profile is verified. This could also be extended to a feature for self-hosted with a variable value that can be set in config."

**Comment by secondtruth** [comment]
The code is missing. :D  `<link rel="me" href="https://mastodon.social/@puter">`

Btw, when you add the Mastodon link to your GitHub org's social links, GitHub will add that `link` tag to the profile as well, so the GitHub link on the Mastodon profile is also verified.

**Comment by jelveh** [comment]
@KernelDeimos did we manage to do this?

**Comment by KernelDeimos** [comment]
This didn't work, but I think I know why:

```<!DOCTYPE html>
<html lang="en">

<head>
    <title>Puter</title>
    <meta name="author" content="Puter Technologies Inc.">
    <meta name="description" content="Puter is a privacy-first personal cloud that houses all your files, apps, and games in one private and secure place, accessible from anywhere at any time.">
    <meta name="facebook-domain-verification" content="e29w3hjbnnnypf4kzk2cewcdaxym1y" />
    <link rel="canonical" href="https://puter.com/">
    <link rel="me" href="https://mastodon.social/@puter">
```

All the examples I can find have an anchor tag on the home page. This seems like an odd choice (what if we don't want to link this on the home page?), but I guess we can make it "behave" as a proper meta tag but putting it in a hidden div element or something.

**Comment by secondtruth** [comment]
> This didn't work

That's weird. According to the documentation it should also work with `link` tags.

https://docs.joinmastodon.org/user/profile/#verification

**Comment by KernelDeimos** [comment]
Oh I see, it's probably just this then
> Make sure to save your profile after adding the rel-me link to your web page! The verification process is triggered when you save your profile, and may take some time before completing.

**Comment by jelveh** [comment]
Verified: https://mastodon.social/@puter
Thanks all!
