### ISSUE TITLE
Folder titles get cut off purely by size and do not honor word breaks

### ISSUE THREAD

**Issue by triptych** [HeyPuter/puter#614]
![image](https://github.com/user-attachments/assets/d55a2501-9c1b-4564-964c-1c0a09de5bc5)

Folder names on the desktop view are seemingly wrapped on a character basis instead of a word break so the names look broken

**Comment by jelveh** [comment]
hmm, what would be a good solution here?

1) keep as is
2) break words:
```
Current
Projects
```
3) Ellipsis 
```
Current Project...
```

I prefer 1, what do you think?

**Comment by triptych** [comment]
Well, I'm not a fan of 1 since I filed the ticket about it. I think it makes most readable sense to break on words...

**Comment by jelveh** [comment]
Thanks again. I need to investigate this a little more on different systems to understand the tradeoffs

**Comment by jelveh** [comment]
@triptych, I thought more about this and did some research. You're right. Looking into a fix right now.

**Comment by jelveh** [comment]
Merged a patch for this 🎉
