### ISSUE TITLE
Switch default AI model to GPT4o-mini

### ISSUE THREAD

**Issue by recursionbane** [HeyPuter/puter#623]
The new GPT4o-mini model is [1/3 the price](https://openai.com/api/pricing/) of GPT3.5 (the current default in Puter) and more capable. 

Can we switch the [default AI model](https://docs.puter.com/AI/chat/) in Puter to GPT4o-mini?

**Comment by jelveh** [comment]
This is a great suggestion, thank you. I'm currently testing GPT4o-mini and it seems to be both faster and better than 3.5. Pending a little more testing I think we could put this on puter.com in a day or two!

**Comment by jelveh** [comment]
Puter's default model is now GPT-4o mini 🎉
