### ISSUE TITLE
Startup sound

### ISSUE THREAD

**Issue by Zac0511** [HeyPuter/puter#634]
A startup sound should be added
Like an user said on Discord, "_is an OS without a startup sound really an OS?_"
He's right. An OS isn't an OS without a startup sound. Puter **NEEDS** a startup sound.

**Comment by KernelDeimos** [comment]
Note: this can work when logging into an account, but likely can't work for temporary accounts as most browsers require a user to click on the page before it can play any sound.

**Comment by KernelDeimos** [comment]
I'm going to close this since #783 is being tracked. I'm considering this to be the issue for making the chime - so it's done - whereas 783 is for making the chime play at startup.
