### ISSUE TITLE
Complete Kurdish translation based on the English file

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#636]
The Kurdish translation file (`ku.js`) exists and contains all the necessary keys, but the translations need to be completed. Currently, the Kurdish file has the same structure as the English file (`en.js`), but the translation values are in English and need to be translated into Kurdish.

## Steps to resolve

1. Open `src/gui/src/i18n/translations/ku.js`
2. Go through each key in the file
3. Translate the English text for each key into Kurdish
4. Ensure that all translations are culturally appropriate and maintain the intended meaning of the English text

## Additional notes

- If certain terms or phrases don't have a direct Kurdish equivalent, consider adding translator notes or using transliteration where appropriate
- Pay attention to any placeholders or variables in the text and ensure they are maintained in the Kurdish translation
- If you're unsure about any translations, mark them for review or consult with a native Kurdish speaker

## Files to be updated

- `src/gui/src/i18n/translations/ku.js`

## Related files

- `src/gui/src/i18n/translations/en.js` (reference file for original English text)

Thank you for helping to complete the Kurdish localization of our project!

**Comment by BryarGh** [comment]
Hey, Thanks for posting this.

**Comment by jelveh** [comment]
Thank you! Assigned.
You're right. We need to add support for RTL. I'm going to add a separate issue for that.

**Comment by BryarGh** [comment]
I am done updating and creating the pull request, please check..

**Comment by jelveh** [comment]
Thank you very much! I'll merge shortly 🫡

**Comment by jelveh** [comment]
closed via #640
