### ISSUE TITLE
After confirming email address, `/whoami` still returns `0` for `email_confirmed` and needs a logout/re-login to return the correct value

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#652]
As reported by @de1eb [here](https://github.com/HeyPuter/puter/pull/650#issue-2441303225), if a user saves their account and confirms their email address the Contact Us form still won't work unless they log out and log back in. This is because `/whoami` is not sending the correct value for `email_confirmed` unless a new session is created. Seems like a caching issue?

**Comment by KernelDeimos** [comment]
I believe this has been fixed by ef245b70df482ff470877459fcb28e1f490fe42d but might need a re-test

**Comment by jelveh** [comment]
I can confirm this has been fixed. ✌️
