### ISSUE TITLE
"Drop your app ... to deploy" isn't working

### ISSUE THREAD

**Issue by KernelDeimos** [HeyPuter/puter#66]
drag-and-drop of a directory from Puter's filemanager results in a no-op.

Chromium: Version 121.0.6167.160 (Official Build) Arch Linux (64-bit)

![image](https://github.com/HeyPuter/puter/assets/7225168/e1ceae58-6fc0-402c-93b9-411257c6803f)

**Comment by jelveh** [comment]
How many files in the directory you're trying to upload?

**Comment by KernelDeimos** [comment]
Two files (`index.html`, `index.js`) and a directory (`2024-03`) with a file in it (`data.json`). Our of curiosity, why would that matter - isn't it a `copy` operation on the directory I drag into it?

**Comment by jelveh** [comment]
Dev Center does a number of checks on the directory you drop on the deploy area. It may take some time if the directory is very big. This is a known UX issue where we need to show some progress indicator while it's happening

**Comment by h43z** [comment]
Cannot drop a simple index.html file in it.

`Uncaught (in promise) TypeError: item is undefined`

**Comment by dagelf** [comment]
works for me on Arch, Chromium 123.0.6312 tested right now... disable extensions and try again? I didn't even have to be logged in. I think this issue can closed. (And I have umatrix blocking almost everything, it still works!)

Wow its a lot faster on Chromium than FF

**Comment by jelveh** [comment]
I've applied multiple patches to Dev Center. Can't reproduce this any longer. Let me know if any of you still experience issues.
