### ISSUE TITLE
When I pass the first parameter of puter.ui.shawSaveFilePicker as an object URL type, I call the/download method and return 404. Upon checking the source code, I found that this method is not implemented

### ISSUE THREAD

**Issue by mailyxf** [HeyPuter/puter#660]
When I pass the first parameter of puter.ui.shawSaveFilePicker as an object URL type, I call the/download method and return 404. Upon checking the source code, I found that this method is not implemented
![image](https://github.com/user-attachments/assets/aa9dd84d-11f4-4aa8-b79f-8b34e4ff90c3)

**Comment by jelveh** [comment]
I'm confused. Why would you pass a URL?

**Comment by mailyxf** [comment]
> 我很困惑。你为什么要传递 URL？

I am not transmitting the file stream effectively
