### ISSUE TITLE
Uploading is not working.

### ISSUE THREAD

**Issue by jmfergeau** [HeyPuter/puter#67]
As title says. When I upload something. it either hangs at 100% or just halfway and never uploads. And yes I made an account.

Is server having problems? Or uploading not completely implemented yet?

Thanks

**Comment by KernelDeimos** [comment]
Hello, please try again. This is a service issue, it shouldn't happen usually.

**Comment by jmfergeau** [comment]
Indeed, it's working now. thanks.
