### ISSUE TITLE
Browser don't close

### ISSUE THREAD

**Issue by plusin** [HeyPuter/puter#684]
**Issue Description** Browser don't close when you click X

**Steps to Reproduce** Open Browser, Try to Close.

**Expected & Actual Behavior** Close the App

**Addition Information or Screenshots (if applicable)**

**Deployment**
- [x] Production (puter.com)
- [ ] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [ ] Docker (via `docker-compose`)

**Puter version (if accessible)**
> 2.1.0

**Comment by jelveh** [comment]
This has been resolved
