### ISSUE TITLE
Proposal: Translate official documentation to Korean

### ISSUE THREAD

**Issue by jsdmas** [HeyPuter/puter#697]
Hello Puter team,

I'd like to contribute to the project by translating the official documentation into Korean. This would help make Puter more accessible to Korean-speaking developers and users.

Some key points:
- I am a native Korean speaker
- I can commit to completing the initial translation within 1 week

Thank you for considering this proposal.  :)

**Comment by jelveh** [comment]
That would be awesome! Thank you very much. I just assigned it to you. Let me know if you need any help 🙌
