### ISSUE TITLE
Improve submenu navigation: Implement grace period for mouse movement

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#7]
Currently, when users hover over a context menu item that has a submenu, the submenu opens as expected. However, if the user's mouse cursor leaves the active menu item even for a brief moment, the submenu immediately closes. This behavior creates a usability issue, as it requires users to maintain hover over the active item while navigating to the submenu. Users naturally tend to move their mouse diagonally towards the submenu, often momentarily leaving the active item's hover area, which results in the submenu closing prematurely.

Current state: This is how the mouse should be moved for the submenu not to close:

<img width="611" alt="298311673-5ff948d8-7225-456f-849b-47a1d5df80ed" src="https://github.com/HeyPuter/puter/assets/1715019/69b82ff5-0a53-4986-b380-4cb7650113c9">

<br/>

<br/>

To address this issue, it would be beneficial to introduce a grace period that allows the submenu to remain open for a short duration after the mouse leaves the active item. This grace period would provide a more forgiving navigation experience, accommodating natural mouse movement patterns without penalizing slight deviations.

<img width="611" alt="298311704-72b3b015-f45d-46f7-a4fc-4a28b135ef34" src="https://github.com/HeyPuter/puter/assets/1715019/d4985dc3-d28d-4caf-8c83-a0ddf5f01f80">

**Comment by Hiya-its-Aya** [comment]
Hi @jelveh I would love to work on this!

**Comment by jelveh** [comment]
Thank you! Let's go! Let me know if you need help.

**Comment by Hiya-its-Aya** [comment]
The closest I've gotten so far is I use a setTimeout to wait to add the `context-menu-active` class to `contextMenu`, so the mouseover does not trigger prematurely and gives some time for the user navigate to the submenu.

Here's the code starting from about line 150 of `UIContextMenu.js`:
```
// when mouse is over an item
    $(contextMenu).find('.context-menu-item').on('mouseover', function (e) {
         //and if conxtext menu is active
        if($(contextMenu).hasClass('context-menu-active')){
            // mark other items as inactive
            $(contextMenu).find('.context-menu-item').removeClass('context-menu-item-active');
            console.log("remove active", contextMenu)
            // mark this item as active
            $(this).addClass('context-menu-item-active');
            console.log("make active", contextMenu)
            // close any submenu that doesn't belong to this item
            $(`.context-menu[data-parent-id="${menu_id}"]`).remove();
            console.log("remove submenu", contextMenu)
            // mark this context menu as active after .7 seconds if submenu is open
            if($(this).attr('data-has-submenu') === 'true'){
                // $(contextMenu).removeClass('context-menu-active');   
                let timeout = setTimeout(() => {
                    console.log("menu is now active", contextMenu)
                    $(contextMenu).addClass('context-menu-active');
                    clearTimeout(timeout);  
                }, 300);    
            }   
        }
    })
```


One issue I'm having is that some items are not responding when hovered, or if I hover too fast past the items with submenus it lags and/or other submenus will pop up. I know it's becuase of the setTimeout so best solution I have is to make it 300ms. I'm sure there's somethng better but I'm trying not to abstract the whole mouseover event to keep it. I pushed it to my : https://github.com/Hiya-its-Aya/puter/tree/slow-submenu

Any sugestions would be awesome! Thanks!

**Comment by jelveh** [comment]
This is such an elegant solution! Thanks @AtkinsSJ

**Comment by Hiya-its-Aya** [comment]
Yes,  thanks @AtkinsSJ ! I did take a look earlier today buit didn't time to implement it and looks like just what I need! I think this would have to be tweaked to account for both left and right since it only accounts for the submenu being on the right. Hopefully this works out!

**Comment by Hiya-its-Aya** [comment]
Okay I've been super close, thanks @AtkinsSJ ! I have implemented the plugin but I also tweaked it in order to have the `menuAim.submenuDirection` so that the direction is detrmined in `UIContextMenu.js`. It works pretty seamlessly,  but I'm still running into an issue that  basically the first time the submenu pop ups up will determine if the menu is left or rigth and won't change until page reload. The idea is to have the `menuAim.submenuDirection` change each time a main menu pops up. Any help would be great. Thanks
I made a new branch you can check out here: https://github.com/Hiya-its-Aya/puter/tree/slow-sub-v2

**Comment by jelveh** [comment]
Awesome! 
I'll look into this. @AtkinsSJ you're welcome to chime in as well.

**Comment by Hiya-its-Aya** [comment]
Sure thing! @jelveh

**Comment by Hiya-its-Aya** [comment]
Hey @jelveh  I pulled the latest and merged the latest changes from the HeyPuter/Puter repo and its throwing an error when I try to start up the dev server.

```
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'dotenv'
Require stack:s
- /Users/ayamoosa/puter/puter/dev-server.js
```

**Comment by Hiya-its-Aya** [comment]
You know what @jelveh I think I got it! I'll clean it up and do a PR soon.

**Comment by jelveh** [comment]
Nice!! Can't wait to see it in action
