### ISSUE TITLE
Custom network configuration via .env

### ISSUE THREAD

**Issue by pkirsche** [HeyPuter/puter#714]
Hello and first of all: THANKS!
Great project and great work.

Running puter within a docker compose enviroment, I run into an issue with networking. It seems that puter creates it's own network with a subnet of 192.168.80.x/20. 
Unfortunately, within my setup, this network causes issues and I need to change the subnet somehow.

Is there any change to do this via enviromental variables (e.g. within .env) already?
If not, this would be a great option and would help me a lot.

**Comment by KernelDeimos** [comment]
I believe this is related to Docker rather than Puter. Although, the subnet you mentioned is not [Docker's default subnet range](https://support.hyperglance.com/knowledge/changing-the-default-docker-subnet) so I'm not sure what's happening here. What I do know is Puter itself does not create any network on the host OS.

**Comment by pkirsche** [comment]
Thanks for your reply @KernelDeimos 
Indeed, the pre-chosen subnet 192.168.80.x/20 is not within the default docker subnet range. Thats what makes me believe, it comes from the container itself. I also don't have any DHCP server running which would and could deliver IPs from this subnet range.
So if it's insight the image, it would be a great improvement if the subnet could be configured via enviroment variable or other kind of way.

**Comment by KernelDeimos** [comment]
Hi, I'm going through all the issues on our GH today - I'm going to close this one because we don't have any hard-coded subnet for Docker.
