### ISSUE TITLE
`/sign` call is requesting write access for non-writable files

### ISSUE THREAD

**Issue by KernelDeimos** [HeyPuter/puter#722]
**Issue Description**
Calls to `/sign` are request write access but this results in a 403 response

**Steps to Reproduce**
Open a Public folder of a different user
Right click file -> open with -> (choose an app)

**Expected & Actual Behavior**
works

**Addition Information or Screenshots (if applicable)**

**Deployment**
- [😢] Production (puter.com)
- [😢] Development (`npm run start`)
- [?] Docker (via `docker run`)
- [?] Docker (via `docker-compose`)

**Puter version (if accessible)**
`main`

**Comment by jelveh** [comment]
Is this resolved?

**Comment by KernelDeimos** [comment]
Backend does the fallback now but I think gui should also request read if it knows the file isn't writable (to avoid surprises in the future). This issue is resolved now though so I'll close it
