### ISSUE TITLE
Replace broken in move action

### ISSUE THREAD

**Issue by vineeth-vk11** [HeyPuter/puter#73]
The old file is not getting replaced properly. The old file icon is still visible.

https://github.com/HeyPuter/puter/assets/46136355/600a6b0d-bbf5-4da1-84dc-b17576fdc154

**Comment by vineeth-vk11** [comment]
@jelveh This code is responsible for removing the old file, but resp.overwritten?.id in resp
<img width="591" alt="Screenshot 2024-03-11 at 12 50 39 AM" src="https://github.com/HeyPuter/puter/assets/46136355/887815f0-ed2b-4bac-99b8-466a4365e414">

**Comment by jelveh** [comment]
Thanks for reporting this. I'll be home in about an hour and will look into it. We had this bug a long time ago and it just came back 🤔

**Comment by jelveh** [comment]
> @jelveh This code is responsible for removing the old file, but resp.overwritten?.id does not exist in resp <img alt="Screenshot 2024-03-11 at 12 50 39 AM" width="591" src="https://private-user-images.githubusercontent.com/46136355/311538549-887815f0-ed2b-4bac-99b8-466a4365e414.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMDk4NzAsIm5iZiI6MTcxMDEwOTU3MCwicGF0aCI6Ii80NjEzNjM1NS8zMTE1Mzg1NDktODg3ODE1ZjAtZWQyYi00YmFjLTk5YjgtNDY2YTQzNjVlNDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDIyMjYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYzkxMWRmODM4MTEzNTJlZjAxZjg2Nzg4NTIxMTYxOTk1YWMyODcyNjlmY2I1NGQzMjAyYjYwOTFhMTkwNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QvMv5TUQ0Bo6yGBTazj6hDvMd8vDxVxYOIvBrY9tzb4">

That's exactly the issue. This is a backend issue. @KernelDeimos could you take a look at this?

**Comment by KernelDeimos** [comment]
Thanks for the detailed report! We're deploying v1.2.42 now so you should see this fixed in a few minutes.

**Comment by jelveh** [comment]
It's resolved for me. @vineeth-vk11 can you confirm as well?

**Comment by vineeth-vk11** [comment]
@KernelDeimos @jelveh can
