### ISSUE TITLE
Can Chinese be supported?

### ISSUE THREAD

**Issue by kokojacket** [HeyPuter/puter#74]
Can Chinese be supported?

**Comment by jelveh** [comment]
Of course! We're gonna have i8n guidelines and tools soon. I'm keeping this issue open to update you on it.

**Comment by jelveh** [comment]
I have a preliminary implementation of i18n. I have added Chinese as well, but it's automated and it might not make sense. If anybody here could help with proof reading that would be really great: [Chinese translation](https://github.com/HeyPuter/puter/blob/5b9577c31e71b472f66c6ceb5ce99fbf5719bfd1/src/i18n/i18n.js#L335)

**Comment by jelveh** [comment]
We now support Chinese. Please help us improve the translations here:  
[Chinese](https://github.com/HeyPuter/puter/blob/main/src/i18n/translations/zh.js)
[Traditional Chinese](https://github.com/HeyPuter/puter/blob/main/src/i18n/translations/zhtw.js)
