### ISSUE TITLE
Error when using KV: {success: false, error: 'HOUR is not defined'}

### ISSUE THREAD

**Issue by KernelDeimos** [HeyPuter/puter#750]
[on Discord](https://discord.com/channels/1071986474041495705/1280174615888527380)

**Comment by bitsnaps** [comment]
@KernelDeimos 
The issue appears to be related to the `puter.kv.get()` function. Unlike the `list()` function, which does not raise this exception, when you try to `get(someKey)` for a key that does not exist in the KV store, it throws an error `{success: false, error: 'HOUR is not defined'}`. According to the [documentation](https://docs.puter.com/KV/get/), this should return `null` instead.

The [todo example](https://docs.puter.com/playground/?example=app-todo&autorun=1) encounters this error immediately upon execution. A minimal reproducible example would be simply calling `get()` with a non-existent key:

```js
puter.kv.get('todos').then((todos) => {
    console.log(todos);
});
```

**P.S.:** Attempting to load `puter.js` at the `<head>` or at the bottom of the `<body>` did not resolve the issue.

**Comment by KernelDeimos** [comment]
This is fixed and deployed now, thanks for reporting!
