### ISSUE TITLE
2FA Email Option Unavailable After Changing Email Address

### ISSUE THREAD

**Issue by ECHOlinuxWarrior** [HeyPuter/puter#759]
**Steps to Reproduce**
1. Register a new account using `test@mail.com`.
2. Change the registered email address to `test2@mail.com`.
3. Confirm the new email address (`test2@mail.com`) through the provided confirmation link.
4. Now if I need 2fa active it is not available on my account.

**Expected & Actual Behavior**
- The 2FA option should be available after confirming the new email address (`test2@mail.com`).
- The 2FA option is not available after confirming test2@mail.com because the confirmation link is sent to the old email (test@mail.com), not the updated email.

**Comment by KernelDeimos** [comment]
Thanks for reporting this! It is now fixed (33de98107f6e3284acb180b1a44bb02ae082642f) and will be deployed soon.

**Comment by KernelDeimos** [comment]
This is deployed now! This will not affect accounts retroactively as there's no safe way to do this, but if you change the email to the old one, then back to the new one and confirm it, you should have 2FA available for your account.
