### ISSUE TITLE
Network And Docment Need !

### ISSUE THREAD

**Issue by sang8052** [HeyPuter/puter#77]
This is a very interesting project , but i think something import is need .
1. Internet socket support. It 'can run a plugin on your pc , than i can connect network by using websocket with the desktop's plugin or  something that on another server .
2. Development Docment need ! Just tell me how to create a api server like (api.puter.com) and something other !

**Comment by jelveh** [comment]
Hi there, 2 is coming in about 3 weeks. Please see [this issue](https://github.com/HeyPuter/puter/issues/54).

I'm not sure about number 1, could you elaborate more?
