### ISSUE TITLE
ОС недоступна

### ISSUE THREAD

**Issue by VladLore** [HeyPuter/puter#797]
Добрый день.
Установка успешна.
ОС запущена
Но по адресу http://puter.localhost:4100/ недоступна.
Порт не занят.
У локального пк есть доменное имя ubuntu-pc.local.
По такому адресу так же недоступна.
Подскажите пожалуйста, что проверить?

**Comment by KernelDeimos** [comment]
Hello. I'm using Google Translate to communicate, so this message might be unclear or incorrect in some ways. Please provide any error message you see, and let us know what host operating system you're running Puter on.

Здравствуйте. Я использую Google Translate для общения, поэтому это сообщение может быть неясным или неверным в некоторых отношениях. Пожалуйста, предоставьте любое сообщение об ошибке, которое вы видите, и сообщите нам, на какой операционной системе хоста вы используете Puter.

**Comment by VladLore** [comment]
добрый день
ОС Ubuntu 24.04.1 LTS


чт, 10 окт. 2024 г. в 17:44, Eric Dubé ***@***.***>:

**Comment by KernelDeimos** [comment]
Please check the docs for domain configuration. This might be the issue you're experiencing.

- [domain configuration doc](https://github.com/HeyPuter/puter/blob/main/doc/self-hosters/domains.md)
- [self-hosting instructions](https://github.com/HeyPuter/puter/blob/main/doc/self-hosters/instructions.md)
