### ISSUE TITLE
Weird bug on topbar

### ISSUE THREAD

**Issue by Zac0511** [HeyPuter/puter#798]
**Issue Description**
While i was using _VJS_, i encountered a weird bug with the topbar, and the text started going up and showed scrollbars.

**Steps to Reproduce**
Use the top bar on an app

**Expected & Actual Behavior**
Not creating scrollbars

**Addition Information or Screenshots (if applicable)**

https://github.com/user-attachments/assets/cfaad653-2122-4b50-be13-7eecbb11e323

**Deployment**
- [X] Production (puter.com)
- [ ] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [ ] Docker (via `docker-compose`)

**Puter version**

Version: 2.4.1 • Server: london • Deployed: 10/10/2024 17:13:56

**Comment by jelveh** [comment]
Thank you Zac. Nice catch as always. I'll fix it in a second.
