### ISSUE TITLE
Api call for copy with overwrite set to true is failing with 500

### ISSUE THREAD

**Issue by vineeth-vk11** [HeyPuter/puter#80]
### Steps to reproduce
Copy a file to a directory which already has a file with the same name

<img width="555" alt="Screenshot 2024-03-12 at 9 46 33 AM" src="https://github.com/HeyPuter/puter/assets/46136355/bdd5c178-a875-4124-8528-9308327f5b6f">

**Comment by jelveh** [comment]
Looking into it. @KernelDeimos knows much more about this.

**Comment by KernelDeimos** [comment]
Hello, we have a bit of backlog but this is next on the roster and I'll probably have an update for you tomorrow
