### ISSUE TITLE
Feature Request: Allow apps to determine their initial window dimensions

### ISSUE THREAD

**Issue by triptych** [HeyPuter/puter#81]
As an app developer I would like to have a way to suggest the window height and width of my app on initial load. Either 
1) in the developer app as part of the config for my app
2) some way for the app itself to know what it's dimensions are and to be able to resize them on the fly

**Comment by Axorax** [comment]
You can already know the app window dimensions but you cannot resize them. Using `window.innerWidth` and `window.innerHeight` you can get the size of the window that your app was opened in. I am using these properties to determine the window size in my app. https://puter.com/app/livewinsize

**Comment by triptych** [comment]
I've seen other implementations where if the size is below or above certain thresholds, they are ignored - this prevents abuse with too large or too small.

**Comment by jelveh** [comment]
> I've seen other implementations where if the size is below or above certain thresholds, they are ignored - this prevents abuse with too large or too small.

I think this is the most appropriate implementation.

**Comment by jelveh** [comment]
> I would think that it would be okay to resize as long as permission is granted by the user.

this could work too but I wonder if displaying a dialog asking for resize permission is a little *unfamiliar* to the user.
