### ISSUE TITLE
Bug: on wsl/win11, clone the latest code, failed see project after npm run start

### ISSUE THREAD

**Issue by mclxly** [HeyPuter/puter#813]
### Issue Description

index.js:128 
        
        
       GET http://puter.localhost:4100/sdk/puter.dev.js net::ERR_ABORTED 404 (Not Found)
(anonymous) @ index.js:128
__webpack_modules__.2173.window.loadScript @ index.js:96
__webpack_modules__.2173.window.gui @ index.js:63
(anonymous) @ (index):88
load
(anonymous) @ (index):87
puter.localhost/:1 Refused to execute script from 'http://puter.localhost:4100/sdk/puter.dev.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
index.js:125 Uncaught (in promise) Error: Failed to load script at url: /sdk/puter.dev.js
    at script.onerror (index.js:125:1)

### Steps to reproduce

npm run start

![1729519584013](https://github.com/user-attachments/assets/73f80c49-90aa-4c13-9fa6-2346d95cb912)

### Expected behaviour

see project after npm run start

### Deployment

- [ ] Production (puter.com)
- [X] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [ ] Docker (via `docker-compose`)

### Puter version (if accessible)

commit 99ce3bde199de729c4796a681c188c4a0da9165e (grafted, HEAD -> main, origin/main, origin/HEAD) Author: jelveh <nj@puter.com> Date:   Sun Oct 20 20:42:34 2024 -0700

**Comment by KernelDeimos** [comment]
Is this part coming from the browser? I see "webpack" in the output which suggests a build issue, but then a URL which suggests it's in the browser, so I'm a little confused.
```
(anonymous) @ (index):87
puter.localhost/:1 Refused to execute script from 'http://puter.localhost:4100/sdk/puter.dev.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

**Comment by mclxly** [comment]
@KernelDeimos Yes, it's from browser.

git clone, npm install, npm run start, changed host file, and then open http://puter.localhost:4100 in Chrome, display nothing but only deep blue background, console print these error info:

![1729563072165](https://github.com/user-attachments/assets/f0bc09c4-5c67-4fb7-9b8f-a25f6126669a)

**Comment by mclxly** [comment]
Fix the error after upgrading node & npm.

Thanks~

**Comment by anmolrathodzws** [comment]
> Fix the error after upgrading node & npm.
> 
> Thanks~

Which version did you upgrade to ?
