### ISSUE TITLE
The latest Claude 3.5 Sonnet version.

### ISSUE THREAD

**Issue by Aknyzor** [HeyPuter/puter#826]
Do you plan to add the Claude 3.5 Sonnet version claude-3-5-sonnet-20241022? If I saw correctly, the current version is claude-3-5-sonnet-20240620.

**Comment by jelveh** [comment]
I think this should be fine. Let me CC @KernelDeimos to look into this. Please stay tuned.

**Comment by jelveh** [comment]
We have updated the API to use the latest Claude Sonnet 3.5. Can't wait to see what you'll build! 😇
