### ISSUE TITLE
Follow-Up on Pending Security Vulnerability Reports in HackerOne Bug Bounty Program

### ISSUE THREAD

**Issue by secone1** [HeyPuter/puter#832]
Hi @KernelDeimos,

We’ve reported several security vulnerabilities through your **HackerOne** **Bug Bounty Program,** but we haven’t received any responses yet. We wanted to kindly follow up to check if there are any updates regarding pending submissions.

I apologize for reaching out here on your GitHub Issues but I wanted to ensure this message reaches you.

Thank you for your time and attention!

**Comment by jelveh** [comment]
It's against out H1 policy to discuss security issues publicly. Why do you think it's a good idea to post on our repo? Did you read the policy?
