### ISSUE TITLE
Complete the Armenian (Հայերեն) translation of Puter

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#866]
The Armenian version of Puter is missing a number of translations. This task involves updating the Armenian translation file to ensure that all English text is accurately translated and culturally appropriate.

### Steps to resolve
1. Scroll to the bottom of [`src/gui/src/i18n/translations/hy.js`](https://github.com/HeyPuter/puter/tree/main/src/gui/src/i18n/translations/hy.js) to find the list of missing translations
2. For each translation key that is missing the value is left as `undefined`, however the English translation is provided in the comment next to it.
3. Replace `undefined` with the Armenian translation of the English text provided in the comment

### Additional notes
- Please pick up this task only if you're fluent in Armenian. This is to make sure the nuances of the language are observed accurately.
- Please ensure that the translations are culturally appropriate and maintain the intended meaning of the English text
- If certain terms or phrases don't have a direct Armenian equivalent, consider adding translator notes or using transliteration where appropriate
- Please be mindful of placeholders such as `%strong%` and try to appropriately place them in the translated text

### Files to be updated
- [`src/gui/src/i18n/translations/hy.js`](https://github.com/HeyPuter/puter/tree/main/src/gui/src/i18n/translations/hy.js)

Thank you for helping to improve the Armenian localization of our project!

**Comment by MherFrangyan** [comment]
“change”: “Փոփոխել”,
“clock_visibility”: “Ժամացույցի տեսանելիություն”,
“reading”: “Ընթերցում”,
“writing”: “Գրում”,
“unzipping”: “Արխիվը բացել”,
“sequencing”: “Հաջորդականություն”,
“zipping”: “Արխիվացում”,
“Editor”: “Խմբագրիչ”,
“Viewer”: “Դիտորդ”,
“People with access”: “Մուտքի իրավունք ունեցող անձինք”,
“Share With…”: “Կիսվել…”,
“Owner”: “Սեփականատեր”,
“You can’t share with yourself.”: “Դուք չեք կարող կիսվել ինքներդ ձեզ հետ։”,
“This user already has access to this item”: “Այս օգտատերն արդեն մուտքի իրավունք ունի։”

**Comment by jelveh** [comment]
Hi @MherFrangyan Thanks again for contributing to Puter! I appreciate it. Could you please submit this as a PR? I know it's a relatively small change but we have this process where we want clear logs of who contributed what as part of our commit history, not to mention the CLA we use. 

Thanks again!

**Comment by MherFrangyan** [comment]
Hi @jelveh you are welcome. No problem I will try to create PR tomorrow and ping you.
