### ISSUE TITLE
Is there a user guide

### ISSUE THREAD

**Issue by mrraghur** [HeyPuter/puter#87]
Hi. I am coming here from hacker news. Is there a user guide on how I can install apps on puter? 

In my case, I want to host koodo-reader (https://github.com/koodo-reader/koodo-reader) on puter and access it over a browser. koodo-reader is a standard "react"app (It starts with react-scrips start). Can you plz help explain how to make it work over puter

**Comment by jelveh** [comment]
I'm going to close this as this will be an ongoing project and not a one-off issue.
