### ISSUE TITLE
Enable Save button in Dev Center only when app settings have changed

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#880]
Currently in the [Dev Center](https://puter.com/app/dev-center), the Save button in app editing mode is always enabled, regardless of whether any changes have been made. This can lead to confusion about whether changes need to be saved and unnecessary API calls.

All the relevant code resides in [`dev-center.js`](https://github.com/HeyPuter/puter/blob/main/src/dev-center/js/dev-center.js)

### Technical Requirements:
1. Track original values of all editable fields when app editing form is loaded
2. Enable Save button only when current values differ from original values
3. Disable Save button when:
   - No changes have been made
   - After successful save (values become the new original state)
   - When changes are reverted to original values

### Fields to Track:
- Title
- Name
- Index URL
- Description
- Icon
- File Associations
- Window settings (height, width, position)
- All checkboxes (background, maximize on start, resizable window, etc.)

and any other fields in the settings form...

### Design Considerations:
- Compare values on each field change
- Handle special cases like icon changes (base64/URL comparisons)
- Consider adding a "Reset" button to revert all changes

**Comment by ria147** [comment]
Hello @jelveh , 

I am new to this repository. Looking to contribute as part of my Software Engineering course project for my bachelor's degree. Is this issue still open and in need of work? 

If so, could you please assign it to me? Thank you

**Comment by jelveh** [comment]
Hi @ria147,

Thank you for your interest in contributing to Puter. Just assigned the issue to you. Let us know if you have any questions or need help.

**Comment by jelveh** [comment]
Hi @ria147, did you have any luck with this? Let me know if you need any help.

**Comment by ria147** [comment]
Hi @jelveh , thank you for checking in! I am trying to run things locally, and when I click on the Dev Center, this is what it looks like as of now for me, so can't replicate the issue locally. However this doesn't happen in the deployed version, where I am able to replicate the issue. Can you help me understand if I'm doing something differently, or am I missing something? 

I forked main, ran npm install and npm start.
![image](https://github.com/user-attachments/assets/b0c1ed93-a4ea-4388-b2a8-f2116741aab7)

**Comment by jelveh** [comment]
Could you send me a screenshot of your browser's dev console? Also, is this an incognito window? if not, can you try in an incognito session?

**Comment by jelveh** [comment]
Copying any errors here would be helpful.

**Comment by ria147** [comment]
Tried it in incognito, still not able to replicate the issue locally. 
Here is errors shown on the dev console
![image](https://github.com/user-attachments/assets/23839a98-cbfb-4638-910c-c694fc3fb337)

**Comment by jelveh** [comment]
@ria147 just pushed a fix for this. Could you pull the latest version and `npm start` again?

**Comment by ria147** [comment]
@jelveh resolved the above issue, thank you for your prompt assistance! It now shows I don't have any apps the create button. Clicking on it prompts input for app name, after entering now it's stuck at the loading for creating new app. Not an issue in the deployed version once again, only locally.
![image](https://github.com/user-attachments/assets/628334a0-f7c9-41f1-b6e9-5043ec5c9a53)

**Comment by ria147** [comment]
After reloading the site, I do see the new created app, which is odd. it was stuck at loading the entire time before that.

**Comment by jelveh** [comment]
oof when did dev-center become so buggy! :/
If the issue comes up again could you send me a screenshot of your terminal? seems to be a backend issue since there is a 500 error in the browser console.

**Comment by ria147** [comment]
@jelveh created a pull request(https://github.com/HeyPuter/puter/pull/934), please review and let me know if any changes are required. Hope my changes get merged(Will be awarded bonus points for my course if merged)!

Note: Thank you for this incredible opportunity to polish my skills and be able to contribute to an OSS project. As my first official good-first-issue, I really enjoyed working on this one. The detailed description for the issue helped me get this done faster then I expected, and thank you for assisting quickly and efficiently whenever any challenges arose. Looking to contribute more and get familiar with Puter in the future.

**Comment by jelveh** [comment]
@ria147 Thank you very much for your contribution. I'm glad you found the process enjoyable, that's how it should be :)

Please do come back to Puter if you ever find the time! 😇
