### ISSUE TITLE
Improve flexibility of file association format in Dev Center

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#881]
Currently in [Dev Center](https://puter.com/app/dev-center), file associations must be entered in a specific format. The system should be more tolerant of common file extension formats that developers might naturally use.

Main code resides in [`dev-center.js`](https://github.com/HeyPuter/puter/blob/main/src/dev-center/js/dev-center.js)

### Technical Requirements:
1. Normalize input formats to handle variations like:
   - Plain extension: `psd`, `txt`, `jpg`
   - Dot prefix: `.psd`, `.txt`, `.jpg`
   - Wildcard format: `*.psd`, `*.txt`, `*.jpg`
   - Case variations: `PSD`, `TXT`, `JPG`

2. Standardize storage format:
   - Convert all variations to a consistent format before saving
   - Maintain existing compatibility with file opening system

3. Handle multiple formats in comma-separated list:
   - `*.psd, .txt, JPG, *.PNG` → should all work

### Design Considerations:
- Keep the current comma-separated input UX
- Consider showing normalized format after input (e.g., in a preview)
- Maintain backward compatibility with existing apps
- Add examples in the input field placeholder

**Comment by rowin-C** [comment]
Hello, i was trying to work on this issue and what i can understand is that it is just splitting the line and saving it in a array
![image](https://github.com/user-attachments/assets/5e09cbec-039a-47b7-922f-0478ccb661e2)

i wanted to know where are the validation of the file type is happening ? if that is important for this issue or should i just work on the input format .

Also 
> Convert all variations to a consistent format before saving

is there a format i should follow? or  just (. lowercaseName)

> Maintain existing compatibility with file opening system
Maintain backward compatibility with existing apps

I'm confused on these two, it will be helpful if you can explain it.

I really a noob in open source , this will be the first project I'll be contributing. If I'm making any mistake plz let me know.

**Comment by jelveh** [comment]
Hey @rowin-C, welcome to our project, and thank you for picking Puter as your first open-source project!

No need for validation aside from the very basics (i.e. not empty, not null, not undefined) as I think that'll open the door to a lot of complexity right now.

> is there a format i should follow? or just (. lowercaseName)

you're right I should've mentioned this. Two types of strings are acceptable for each array element:

1. **File Extensions**: i.e. `.pdf`, `.txt`, ... For these you need to follow the `.lowercase` format. So,  `*.pdf, PDF, *.PDF, .pdf, pDf, ...` should all be converted to `.pdf`
2. MIME Types: e.g. `text/plain` or `text/plain`. for these you don't really have to do anything other than making sure they're lowercase.

> Maintain backward compatibility with existing apps
Again, I could've phrased this better, it's vague now. But what I meant is that the change you make should not leave any of existing filetype association out. This shouldn't be any problem as long as the above implementation is done well since there is no way for things to break if we're only normalizing file extension. TLDR: just test and make sure the normalization doesn't leave any type of extension out.

Let me know if you have other questions. I'd be happy to help.

**Comment by rowin-C** [comment]
I tried to catch the error first and then formatted the valid types
I move the filetype_association code above the error block so that i could show the error.

![image](https://github.com/user-attachments/assets/25b65080-0870-4d19-b3bd-bad6c3ad3d5c)

I was wondering how would i show the preview of the corrected types before the submit currently after a save when the setting are reopened the corrected types are there.
also ,
although we are formatting the incorrect user input but would it be wise to show examples of "not standard" type (e.g. *.pdf, PDF, *.PDF, ) in the placeholder ?

**Comment by mariatouil** [comment]
Hi! I'd like to work on this issue. Could you please assign it to me?

**Comment by jelveh** [comment]
looking great! if you open a PR I could help with testing and finalizing it

**Comment by rowin-C** [comment]
sure, I'll add the finishing touches and then open a PR tomorrow.

**Comment by rowin-C** [comment]
@jelveh i noticed that in my previous pull request my formatted had edited a bunch of commas and spaces , which made the change huge (6k lines) i have made another pull request with only the code that is meant to be change , have a look and let me know.

**Comment by jelveh** [comment]
Thank you @rowin-C. The PR is looking pretty great. I'm still testing and will merge soon

**Comment by jelveh** [comment]
Donzo! Thank you @rowin-C for the awesome PR ✌️
