### ISSUE TITLE
Implement Undo and Redo

### ISSUE THREAD

**Issue by jelveh** [HeyPuter/puter#9]
Users should be able to undo/redo their last action(s). These actions are the minimum we need to support:

- copy
- move
- delete
- rename
- New File/New Folder
- Upload (?)

Additionally, we need keyboard shortcuts (e.g., Ctrl/Cmd+Z for undo and Ctrl/Cmd+Y or Ctrl/Cmd+Shift+Z for redo).

**Comment by jelveh** [comment]
Of course! Let's go!!

**Comment by vineeth-vk11** [comment]
@bharat9806 are you working on this? If not I would like to take this up.

**Comment by jelveh** [comment]
@bharat9806 let us know if you're still working on this issue, otherwise I can assign it to @vineeth-vk11

**Comment by bharat9806** [comment]
@jelveh yeah u can I got a little office work to finish so Hardly getting any time right now

**Comment by jelveh** [comment]
@vineeth-vk11 I'm assigning this to you. Let me know if you don't have time or if you need any help.

**Comment by jelveh** [comment]
@vineeth-vk11 yes, we need to go for the last n actions. The actions should not be stored in the clipboard but a separate array (e.g. `actions` or `commands`). Here's a simple implementation in JS: [https://stackoverflow.com/a/54416376](https://stackoverflow.com/a/54416376), under **Command Pattern**

Let me know your thoughts on this.

**Comment by vineeth-vk11** [comment]
An array should work, I will create a PR in a while.
