### ISSUE TITLE
Login form not center aligned

### ISSUE THREAD

**Issue by nepalivai** [HeyPuter/puter#90]
I was trying yo signup and saw this.
![image](https://github.com/HeyPuter/puter/assets/108126089/8cbb6816-ac02-4d68-a4fd-1b113c71732e)

Additionally when i reach 100% zoom normal value i use the login button disappers
![image](https://github.com/HeyPuter/puter/assets/108126089/5097b53c-9994-4ead-a039-97b15f85f0a1)

**Comment by jelveh** [comment]
Thanks for reporting this. Just to double-check, in the first picture did you resize the browser window?

**Comment by meetqy** [comment]
https://github.com/HeyPuter/puter/assets/18411315/bbbc4809-6dfe-4213-bc3e-35fd362f8872

Like this.

**Comment by jelveh** [comment]
Thank you for the video, this makes it clear. We *could* potentially center some of these forms dynamically to resolve the issue but I need to investigate further whether this'll break anything in terms of styling.

**Comment by meetqy** [comment]
> Thank you for the video, this makes it clear. We _could_ potentially center some of these forms dynamically to resolve the issue but I need to investigate further whether this'll break anything in terms of styling.

Is it possible to re-render the UI by detecting that the user has adjusted the window?

**Comment by jelveh** [comment]
We don't really need to re-render everything but there are some cases like the above that need to be addressed. I have an open issue for similar behaviour: [https://github.com/HeyPuter/puter/issues/12](https://github.com/HeyPuter/puter/issues/12)

**Comment by meetqy** [comment]
> We don't really need to re-render everything but there are some cases like the above that need to be addressed. I have an open issue for similar behaviour: #12

OK,i can try.

**Comment by nepalivai** [comment]
@meetqy great work fixing the issue....but i found it happing on other app to Like on about , terminal and recorder. 
So, @jelveh have a look at that is restored??? (I don't know the exact term)

![image](https://github.com/HeyPuter/puter/assets/108126089/fdadab97-ed32-4805-9ab0-30ffaf6b5d53)
![image](https://github.com/HeyPuter/puter/assets/108126089/02cf605a-91e6-4d2e-820e-43fa9557aa79)

**Comment by jelveh** [comment]
ah, that's because puter.com's version is behind this repo. This repo is the bleeding edge, so if you run it locally this problem should be resolved
