### ISSUE TITLE
Toggling apps to minimize once it clicked

### ISSUE THREAD

**Issue by Ayush412-art** [HeyPuter/puter#944]
In operating systems like Windows, when we open an application, there are two ways to minimize it: either by clicking the Minimize button (located at the top-right corner) or by clicking on the application's icon (at the bottom of the screen). This enhances the user interface and improves the overall user experience

**Comment by mariatouil** [comment]
Hi! I'd like to work on this issue. Could you please assign it to me?

**Comment by jelveh** [comment]
This makes sense, but only if there is one window open of that specific app (similar to Windows/MacOS behaviour)

@mariatouil appreciate the interest to pick this up, before I assign this to you and updates on the other issue assigned? I don't want to overwhelm you with issue assignments.

**Comment by arthur-adriansens** [comment]
I added it ;) and I added fun animations for taskbar icons!

**Comment by jelveh** [comment]
Donzo by @arthur-adriansens 🫡
