### ISSUE TITLE
How to Deploy Remote Desktop Mode

### ISSUE THREAD

**Issue by RuningBird** [HeyPuter/puter#95]
By default, the deployment method is not remote desktop, and there is only 500M of independent space. 

I want to manage the entire computer's disk space.

And the provided terminal is also different from the one on the computer

thanks

**Comment by jelveh** [comment]
This is what we call the "self-hosted" version which is coming out in about 3 weeks, it'll allow you to store files to your local disk. As for the terminal, please redirect your question to [https://github.com/heyputer/phoenix](https://github.com/heyputer/phoenix)
