### ISSUE TITLE
‌‌How to deploy a Node.js project?

### ISSUE THREAD

**Issue by kankanai** [HeyPuter/puter#96]
‌‌‌My project includes static resources and a node part. It is usually started using "npm run start". How can I deploy them?

**Comment by jelveh** [comment]
This is not currently possible. One possible solution for now: the [Puter FUSE Driver](https://github.com/HeyPuter/puter-fuse) allows you to mount puter's filesystem on a local computer which can run node, that works and we've tested it but it's still in alpha stage.
