### ISSUE TITLE
‌‌‌‌About the issue of open source licenses

### ISSUE THREAD

**Issue by kankanai** [HeyPuter/puter#97]
‌‌‌‌‌If my project wants to be released on Puter, then I need to guide users to Puter. However, their space is limited, only 500M (by default). I need users to be able to set up their own server (including Puter and my project) by themselves, and the code of my own project should not be open source for users. Currently, AGPL is too strict and may not be feasible. Can I request you to modify the open-source license to LGPL? Thank you and wish Puter better and better.

**Comment by jelveh** [comment]
Could be a little more specific about your project? When you say project, are you talking about adding features to Puter or publishing your project as an app for your users to use?

**Comment by kankanai** [comment]
> Could be a little more specific about your project? When you say project, are you talking about adding features to Puter or publishing your project as an app for your users to use?

‌‌‌‌‌‌The project is a nodejs with sqlite3 as the backend and vue packaging as the frontend, but there are multiple frontend interfaces. For example, if my project is a note-taking software, I want to use Puter as the desktop program, which includes several functional apps such as "write notes," "note list," "AI-generated notes," and "recycle bin." In other words, I want to incorporate Puter's desktop UI interface and default file management functionality to attract users more effectively. Finally, my project allows users to deploy it on their own servers so that they don't have to worry about storage space and running memory limitations. Users can upgrade their servers themselves.

**Comment by jelveh** [comment]
I've thought a lot about the license under which we release Puter and I'm confident AGPL is a great fit. It requires changes to be released under the same license which in turn helps Puter grow in a very healthy way. If AGPL is not compatible with your plans, unfortunately I don't think Puter is a good fit for your use cases; but I do hope you consider using AGPL as well! :)

**Comment by kankanai** [comment]
Okay, never mind, thanks for your open-source. By the way, can I publish my own app on Puter?it only support html project?
